(()=>{'use strict';const P=window.MiraePush,esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let cfg={},user=null,pending=null;
const day=d=>new Date(d).toLocaleDateString('sv-SE',{timeZone:'Asia/Seoul'}),ago=n=>day(Date.now()-n*86400000),stamp=v=>v?new Date(v).toLocaleString('ko-KR'):'접속 기록 없음';
async function start(u,kind='auto'){user=u;let saved;try{saved=JSON.parse(sessionStorage.getItem('mirae-visit')||'null')}catch{}if(kind==='login'||!saved||saved.owner!==u.id||Date.now()-saved.time>30*60000)saved={id:crypto.randomUUID(),owner:u.id,time:Date.now()};sessionStorage.setItem('mirae-visit',JSON.stringify(saved));try{await P.ensureSession();await P.rpc('visit',{id:saved.id,device_id:P.deviceID(),kind,platform:P.mobile()?(P.installContext().ios?'iOS':'Android'):'PC'})}catch{}}
function recordView(id,kind){if(!user||!id)return;const k=user.id+'|'+id+'|'+kind;if(pending===k)return;pending=k;setTimeout(()=>pending=null,1500);P.ensureSession().then(()=>P.rpc('view',{id:crypto.randomUUID(),target_id:id,kind})).catch(()=>{})}
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&user&&cfg.user?.()?.id===user.id)start(user,'auto')});
async function mount(node){node.innerHTML='<div class="page-head"><div><h1>로그인 이력</h1><p>조회 기간의 접속 횟수와 방문일, 학생 기록 조회를 확인합니다.</p></div></div><section class="section"><div class="activity-period"><label class="period-days"><span>최근 기간</span><span class="input-suffix"><input class="input" type="number" min="1" max="3650" value="30" data-days aria-label="최근 조회 일수"><span>일</span></span></label><button class="btn period-apply" data-quick>기간 적용</button><label class="period-start">시작일<input class="input" type="date" data-start value="'+ago(29)+'"></label><label class="period-end">종료일<input class="input" type="date" data-end value="'+ago(0)+'"></label><button class="btn primary period-load" data-load>조회</button></div><div class="compact-filters activity-search"><input class="input" data-query placeholder="이름 · 아이디 · 학생명 검색"><select class="input" data-role><option value="">전체 사용자</option><option value="parent">학부모</option><option value="teacher">강사·임직원</option><option value="admin">관리자</option></select><select class="input" data-active><option value="">전체 접속</option><option value="yes">기간 내 접속</option><option value="no">기간 내 미접속</option></select></div><div data-status role="status"></div></section><div data-stats class="activity-stats"></div><section class="section"><h2>날짜별 접속</h2><div data-chart class="activity-chart"></div></section><section class="section"><div class="table-scroll" data-activity-table></div><p class="push-note">자동로그인도 집계합니다. 같은 탭의 30분 이내 새로고침은 중복 집계하지 않습니다. 조회 횟수가 관심도나 이해도를 확정하는 지표는 아닙니다. 기록은 이 업데이트 이후부터 쌓입니다.</p></section>';
 let rows=[];const get=k=>node.querySelector('[data-'+k+']');get('quick').onclick=()=>{const n=Math.max(1,Math.min(3650,Number(get('days').value)||30));get('start').value=ago(n-1);get('end').value=ago(0);load()};get('load').onclick=load;get('query').oninput=draw;get('role').onchange=draw;get('active').onchange=draw;
 function draw(){const query=get('query').value.toLowerCase(),role=get('role').value,active=get('active').value,list=rows.filter(r=>(!role||r.role===role)&&(!query||[r.name,r.login_id,r.students].join(' ').toLowerCase().includes(query))&&(!active||(Number(r.visits)>0)===(active==='yes'))),counts=list.reduce((v,r)=>v+Number(r.visits),0),entered=list.filter(r=>Number(r.visits)>0).length;get('stats').innerHTML=[['접속 횟수',counts+'회'],['접속 사용자',entered+'명'],['미접속 사용자',(list.length-entered)+'명'],['학생 기록 조회',list.reduce((v,r)=>v+Number(r.views),0)+'회']].map(([t,v])=>'<article><small>'+t+'</small><strong>'+v+'</strong></article>').join('');get('activity-table').innerHTML='<table class="one-line-table"><thead><tr><th>이름</th><th>아이디</th><th>구분</th><th>연결 학생</th><th>접속 횟수</th><th>방문일 수</th><th>기록 조회</th><th>마지막 접속</th><th>상세</th></tr></thead><tbody>'+list.map(r=>'<tr><td>'+esc(r.name)+'</td><td>'+esc(r.login_id)+'</td><td>'+(r.role==='parent'?'학부모':r.role==='admin'?'관리자':'강사·임직원')+'</td><td>'+esc(r.students||'—')+'</td><td>'+r.visits+'</td><td>'+r.days+'</td><td>'+r.views+'</td><td>'+esc(stamp(r.last_visit))+'</td><td><button class="btn sm" data-person="'+esc(r.id)+'">기록 보기</button></td></tr>').join('')+'</tbody></table>';node.querySelectorAll('[data-person]').forEach(b=>b.onclick=()=>detail(rows.find(r=>r.id===b.dataset.person)))}
 async function load(){get('status').textContent='접속 기록을 확인하고 있습니다.';get('load').disabled=true;try{await P.ensureSession();const r=await P.rpc('activity',{start:get('start').value,end:get('end').value});if(!node.isConnected)return;rows=r.rows;get('status').textContent=(r.scope==='all'?'모든 사용자':'내 강좌 학생·학부모')+' · '+rows.length+'명';const max=Math.max(1,...r.daily.map(x=>Number(x.count)));get('chart').innerHTML=r.daily.length?r.daily.map(x=>'<div title="'+esc(x.day)+' · '+x.count+'회"><i style="height:'+Math.max(3,Number(x.count)/max*100)+'%"></i><small>'+esc(x.day.slice(5))+'</small><b>'+x.count+'</b></div>').join(''):'이 기간의 접속 기록이 없습니다.';draw()}catch(e){get('status').textContent='기록 조회에 실패했습니다. 조회 권한과 추가 설치를 확인해 주세요.'}finally{get('load').disabled=false}}
 async function detail(person){try{const r=await P.rpc('activity_detail',{target_id:person.id,start:get('start').value,end:get('end').value});cfg.modal(person.name+' · 로그인 및 조회 이력','<h3>접속 기록 · 최근 500건</h3><div class="table-scroll"><table class="one-line-table"><thead><tr><th>접속 시간</th><th>기기</th><th>로그인 방식</th></tr></thead><tbody>'+r.visits.map(x=>'<tr><td>'+esc(stamp(x.visited_at))+'</td><td>'+esc(x.platform)+'</td><td>'+(x.kind==='login'?'직접 로그인':'자동로그인 · 재방문')+'</td></tr>').join('')+'</tbody></table></div><h3>학생 기록 조회 · 최근 500건</h3><div class="table-scroll"><table class="one-line-table"><thead><tr><th>조회 시간</th><th>학생</th><th>조회 내용</th></tr></thead><tbody>'+r.views.map(x=>'<tr><td>'+esc(stamp(x.viewed_at))+'</td><td>'+esc(x.target_name||'삭제된 학생')+'</td><td>'+({student:'학생 정보',report:'학습 리포트',lesson:'수업 기록'}[x.kind]||'기록')+'</td></tr>').join('')+'</tbody></table></div>')}catch(e){get('status').textContent='선택한 사용자의 기록을 조회할 수 없습니다.'}}
 await load();
}
window.MiraeActivity={VERSION:'3.8.0',configure(c){cfg=c},start,recordView,mount};})();
