(()=>{'use strict';
const A=window.MiraeAttendanceCore,esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let cfg={},actor='',generation=0,root=null,data=null,view='live',classID='',month='',draft=new Map(),roster=null,busy=false,mounted=0;
const $=s=>root?.querySelector(s),day=()=>A.korea().date,log=(event,d={})=>window.MiraeStore.log('attendance.'+event,d);
const notificationLabels={pending:'대기',dispatching:'접수 결과 확인 중',accepted:'접수 완료',failed:'접수 전 실패',unknown:'결과 불명 · 발송내역 확인',cancelled:'취소'};
function post(path,body){return cfg.api('/api/attendance/'+path,{method:'POST',body})}
function liveStudents(){return(data?.students||[]).filter(s=>data.enrollments.some(e=>e.student_id===s.id&&e.status!=='inactive'&&e.joined_on<=day()&&(!e.left_on||e.left_on>=day())))}
function record(sid,date){return data.records.find(r=>r.student_id===sid&&r.date===date)}
function value(sid,date){return draft.get(sid+'|'+date)?.status||record(sid,date)?.status||''}
function matching(s){roster=window.MiraeSMS.cachedRoster||roster;return roster?A.matchStudent(s,roster,data.links.find(l=>l.student_id===s.id),roster.account_username):{kind:'not_loaded',candidates:[]}}
function matchInfo(s){const m=matching(s),hasPhone=(s.parent_phones||[]).some(p=>String(p).replace(/\D/g,'').length>=9),hasCandidatePhone=(m.candidates||[]).some(t=>(t.parent_phones||[]).some(p=>String(p).replace(/\D/g,'').length>=9));if(m.kind==='auto'||m.kind==='manual')return{tone:'ok',text:'문자 연결됨'};if(m.kind==='no_phone'||!hasPhone&&!hasCandidatePhone)return{tone:'danger',text:'학부모 번호 없음'};return{tone:'warn',text:m.kind==='not_loaded'?'문자 연결 확인중':'문자 연결 필요'}}
function matchText(s){return matchInfo(s).text}
function setDraft(sid,date,status){const old=record(sid,date);draft.set(sid+'|'+date,{student_id:sid,date,status,expected_version:old?.version||0,...(view==='live'&&['present','late'].includes(status)?{arrival_at:old?.arrival_at||new Date().toISOString()}:{} )})}
function loadLogs(){const box=$('[data-att-log]');if(box)box.value=window.MiraeStore.logs()}
function buttons(){return `<div class="attendance-tabs"><button class="${view==='live'?'active':''}" data-att-view="live">실시간 출결</button><button class="${view==='book'?'active':''}" data-att-view="book">출석부</button></div><div class="attendance-toolbar"><label>수강반<select data-att-class><option value="">반을 선택하세요</option>${(cfg.base().classes||[]).map(c=>`<option value="${esc(c.id)}" ${c.id===classID?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label>${view==='book'?`<label>조회 월<input type="month" data-att-month value="${esc(month)}"></label><button class="btn" data-att-month-step="-1">이전 달</button><button class="btn" data-att-month-step="1">다음 달</button>`:`<div class="attendance-date">${day()} · 실시간 등원 확인</div>`}<button class="btn" data-att-refresh>새로 불러오기</button>${classID?'<button class="btn" data-att-schedule>반 일정 수정</button>':''}</div>`}
function paint(){
 if(!root?.isConnected||!cfg.active?.())return;const c=data?.class;
 root.innerHTML=`<div class="page-head attendance-page-head"><div><p class="eyebrow">학생의 하루</p><h1>출결</h1><p>실시간 등원 알림과 날짜별 출석 기록을 함께 관리합니다.</p></div></div>${buttons()}<div data-att-status role="status"></div><div data-att-work></div>${cfg.isAdmin?.()?'<section class="section attendance-logs"><details><summary>출결 처리 로그</summary><p>오류가 있으면 아래 로그를 복사해 주세요. 학생 연결 자료는 별도 매칭 진단에 기록합니다.</p><textarea class="v2-log" data-att-log readonly aria-label="출결 로그"></textarea><button class="btn" data-att-copy>로그 복사</button><button class="btn" data-att-diag>매칭 진단 저장</button></details></section>':''}`;
 const work=$('[data-att-work]');if(!c){work.innerHTML='<div class="empty"><strong>현재 시간에 해당하는 반이 없습니다.</strong><p>반을 선택하거나 반 설정에서 수업 요일과 시간을 입력하세요.</p></div>'}else if(view==='live')paintLive(work);else paintBook(work);
 if(!cfg.can?.('class_edit'))$('[data-att-schedule]')?.remove();root.querySelectorAll('[data-att-view]').forEach(b=>b.onclick=()=>{if(!discard())return;view=b.dataset.attView;month=day().slice(0,7);load()});
 $('[data-att-class]').onchange=e=>{if(!discard()){e.target.value=classID;return}classID=e.target.value;load()};
 $('[data-att-month]')?.addEventListener('change',e=>{if(!discard()){e.target.value=month;return}month=e.target.value;load()});
 root.querySelectorAll('[data-att-month-step]').forEach(b=>b.onclick=()=>{if(!discard())return;const d=new Date(month+'-01T12:00:00Z');d.setUTCMonth(d.getUTCMonth()+Number(b.dataset.attMonthStep));month=d.toISOString().slice(0,7);load()});
 $('[data-att-refresh]').onclick=()=>{if(discard())load()};$('[data-att-schedule]')?.addEventListener('click',()=>cfg.editClass(classID));
 $('[data-att-copy]')?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(window.MiraeStore.logs());cfg.toast('로그를 복사했습니다.')}catch{$('[data-att-log]').focus();$('[data-att-log]').select()}});$('[data-att-diag]')?.addEventListener('click',diagnostic);
 root.querySelectorAll('[data-att-link]').forEach(b=>b.onclick=()=>linkDialog(b.dataset.attLink));
 $('[data-att-load-msw]')?.addEventListener('click',async()=>{if(busy)return;busy=true;const op=window.MiraeProgress.begin('출결 학부모 연결 명단');if(!op){busy=false;return}try{roster=await window.MiraeSMS.getRoster(true,p=>op.update(p));op.done('학부모 연결 명단 준비 완료');paint()}catch(e){op.fail(e.message);status(e.message,true)}finally{busy=false}});
 $('[data-att-save]')?.addEventListener('click',save);$('[data-att-send-pending]')?.addEventListener('click',()=>sendPending());loadLogs();
}
function discard(){if(busy){cfg.toast('출결을 처리 중입니다. 완료 후 변경해 주세요.');return false}if(draft.size&&!confirm('저장하지 않은 출결 입력을 바꿀까요?'))return false;draft.clear();return true}
function status(message,error=false){const box=$('[data-att-status]');if(box){box.className='attendance-status '+(error?'error':'');box.textContent=message}}
function paintLive(work){
 const c=data.class,students=liveStudents();
 work.innerHTML=`<section class="section attendance-live"><div class="attendance-heading"><div><h2>${esc(c.name)}</h2><p>${(c.weekdays||[]).map(d=>['일','월','화','수','목','금','토'][d]).join(' · ')} ${esc(c.start_time||'시간 미설정')}–${esc(c.end_time||'')} · 학생 ${students.length}명</p></div><button class="btn" data-att-load-msw>학부모 연결 확인</button></div><p class="muted">등원·지각을 저장하면 개인 엠스위치 계정으로 출결 문자가 발송됩니다. 결석에는 문자를 보내지 않습니다.</p><div class="attendance-live-list">${students.map(s=>{const r=record(s.id,day()),v=value(s.id,day()),msg=data.messages.find(m=>m.student_id===s.id&&m.date===day());return`<article class="attendance-student" data-att-student="${esc(s.id)}"><div class="attendance-person"><strong>${esc(s.name)}</strong><small>${esc(s.school||'')} ${esc(s.grade||'')} · ${esc(s.student_no)}</small><span class="attendance-match"><b class="attendance-warning ${matchInfo(s).tone}">${esc(matchText(s))}</b> <button class="btn sm ghost attendance-link-button" data-att-link="${esc(s.id)}">수신자 연결</button></span></div><div class="attendance-picks">${[['present','등원'],['absent','결석'],['late','지각']].map(([k,l])=>`<button data-att-pick="${esc(s.id)}" aria-label="${esc(s.name+' '+l)}" data-status="${k}" class="${v===k?'selected '+k:''}" aria-pressed="${v===k}">${l}</button>`).join('')}<span data-att-time="${esc(s.id)}">${r?.arrival_at?A.korea(new Date(r.arrival_at)).time:''}</span></div><div class="attendance-notification">${msg?esc(notificationLabels[msg.state]||msg.state):r?'기록 저장 · 문자 없음':'미저장'}${msg?.state==='failed'&&msg.owner_id===cfg.user().id?` <button class="btn sm" data-att-retry="${esc(msg.id)}">접수 전 실패 재시도</button>`:''}</div></article>`}).join('')||'<p>이 날짜에 등록된 학생이 없습니다.</p>'}</div><div class="attendance-save-row"><button class="btn primary" data-att-save>저장하기</button><button class="btn" data-att-send-pending>대기 알림 보내기</button><span>${draft.size?'수정 '+draft.size+'건':'등원 확인 버튼을 선택해 주세요.'}</span></div></section>`;
 if(!cfg.can?.('attendance_edit'))root.querySelectorAll('[data-att-pick],[data-att-save]').forEach(b=>b.disabled=true);if(!cfg.can?.('attendance_notify'))root.querySelectorAll('[data-att-send-pending],[data-att-load-msw],[data-att-link]').forEach(b=>b.hidden=true);root.querySelectorAll('[data-att-pick]').forEach(b=>b.onclick=()=>{if(busy||!cfg.can?.('attendance_edit'))return;setDraft(b.dataset.attPick,day(),b.dataset.status);const row=b.closest('.attendance-student');row.querySelectorAll('[data-att-pick]').forEach(x=>{const picked=x===b;x.className=picked?'selected '+x.dataset.status:'';x.setAttribute('aria-pressed',String(picked))});const d=draft.get(b.dataset.attPick+'|'+day());const time=row.querySelector('[data-att-time]');if(time)time.textContent=d.arrival_at?A.korea(new Date(d.arrival_at)).time:'';const count=$('.attendance-save-row span');if(count)count.textContent='수정 '+draft.size+'건';});
 root.querySelectorAll('[data-att-retry]').forEach(b=>b.onclick=async()=>{if(busy)return;try{await post('retry',{id:b.dataset.attRetry});await load();await sendPending()}catch(e){status(e.message,true)}});
}
function bookDates(){const c=data.class,d=new Date(month+'-01T12:00:00Z'),dates=new Set(data.records.map(r=>r.date));while(d.toISOString().startsWith(month)){const date=d.toISOString().slice(0,10);if(c.start_date<=date&&c.end_date>=date&&c.weekdays?.includes(d.getUTCDay()))dates.add(date);d.setUTCDate(d.getUTCDate()+1)}for(const row of draft.values())dates.add(row.date);return[...dates].sort()}
function paintBook(work){const dates=bookDates(),students=[...data.students].sort((a,b)=>Boolean(data.row_status?.[a.id])-Boolean(data.row_status?.[b.id])||a.name.localeCompare(b.name,'ko'));
 work.innerHTML=`<section class="section attendance-book" id="attendance-print"><div class="attendance-heading"><div><h2>${esc(data.class.name)} · 출석부</h2><p>${esc(month)} · ${dates.length}회 · 학생 ${students.length}명</p></div><div class="attendance-no-print"><button class="btn primary" data-att-save>출석부 저장</button><button class="btn" data-att-print>저장하고 출력</button></div></div><p class="attendance-no-print muted">출석부 수정은 기록만 저장합니다. 학부모 문자를 보내지 않습니다.</p><div class="attendance-no-print attendance-add-date"><label>보강 등 추가 날짜<input type="date" data-att-extra-date value="${month+'-01'}"></label><button class="btn" data-att-add-date>날짜 추가</button></div><div class="attendance-book-scroll"><table class="attendance-book-table"><thead><tr><th>학생명</th><th>원생번호</th>${dates.map(d=>`<th>${Number(d.slice(5,7))}/${Number(d.slice(8))}<small>${['일','월','화','수','목','금','토'][A.weekday(d)]}</small></th>`).join('')}</tr></thead><tbody>${students.map(s=>{const style=data.row_status?.[s.id]||'';return`<tr class="attendance-row-${style}"><th>${esc(s.name)}</th><td>${esc(s.student_no)}</td>${dates.map(d=>{const val=value(s.id,d);return`<td><select aria-label="${esc(s.name+' '+d+' 출결')}" data-att-cell="${esc(s.id)}" data-date="${d}"><option value="">미기록</option>${Object.entries(A.STATUS).map(([k,l])=>`<option value="${k}" ${k===val?'selected':''}>${l}</option>`).join('')}</select><span class="attendance-print-status">${esc(A.STATUS[val]||'—')}</span></td>`}).join('')}</tr>`}).join('')}</tbody></table></div><p class="attendance-book-legend">전출 · 전입 · 전관 · 퇴원 학생은 하단에 배치합니다. 전입: 초록색 / 전관: 하늘색 / 퇴원: 빨간색.</p></section>`;
 if(!cfg.can?.('attendance_edit'))root.querySelectorAll('[data-att-cell],[data-att-save],[data-att-add-date]').forEach(b=>b.disabled=true);root.querySelectorAll('[data-att-cell]').forEach(s=>s.onchange=()=>{if(busy)return;if(!s.value){s.value=record(s.dataset.attCell,s.dataset.date)?.status||'';cfg.toast('미기록으로 지우기는 지원하지 않습니다. 올바른 상태를 선택하세요.');return}setDraft(s.dataset.attCell,s.dataset.date,s.value)});
 $('[data-att-add-date]').onclick=()=>{const date=$('[data-att-extra-date]').value;if(!A.validDay(date)||!date.startsWith(month)){cfg.toast('현재 조회 월의 날짜를 선택하세요.',true);return}for(const s of data.students){if(!record(s.id,date)&&!draft.has(s.id+'|'+date))draft.set(s.id+'|'+date,{student_id:s.id,date,status:'',expected_version:0})}paint()};
 $('[data-att-print]').onclick=async()=>{if(busy)return;if([...draft.values()].some(x=>x.status)&&!await save(false))return;document.body.classList.add('printing-attendance');window.print();document.body.classList.remove('printing-attendance')};
}
async function load(){const g=generation,tag=++mounted;if(!classID){data=null;paint();return}try{status('출결 기록을 불러오는 중입니다.');const d=await cfg.api('/api/attendance/read?'+new URLSearchParams({class_id:classID,month}));if(g!==generation||tag!==mounted)return;data=d;paint();await recover(false)}catch(e){if(g===generation)status(e.message,true)}}
async function save(notify=true){if(!cfg.can?.('attendance_edit'))return false;if(busy)return false;const rows=[...draft.values()].filter(r=>r.status);if(!rows.length){if(view==='live'&&notify)await sendPending();else cfg.toast('변경한 출결이 없습니다.');return true}busy=true;const g=generation,mode=view;try{const r=await post('save',{class_id:classID,mode,rows});if(g!==generation)return false;draft.clear();log('saved',{mode,records:r.saved.length,notifications:r.notification_count});await load();status('저장완료');busy=false;if(mode==='live'&&notify)await sendPending();return true}catch(e){if(g===generation){status(e.message,true);log('save.failed',{message:e.message})}return false}finally{busy=false}}
async function report(job,result){await post('report',{job_id:job,results:result.results||[],message:result.message||''})}
async function recover(resume){
 if(!data)return;const g=generation,id=actor,cid=classID,mon=month,snapshot=data;const current=()=>g===generation&&id===actor&&cid===classID&&mon===month;let changed=false;const jobs=[...new Set(snapshot.messages.filter(m=>m.owner_id===cfg.user()?.id&&m.state==='dispatching').map(m=>m.job_id))];
 for(const job of jobs){if(!current())return;try{const d=await window.MiraePC.status(job);if(!current())return;if(['done','failed','unknown'].includes(d.state)){const r=d.result||{};if(d.state==='failed'&&!r.attempted&&!r.results){const messages=snapshot.messages.filter(m=>m.job_id===job);r.results=messages.map(m=>({notification_id:m.id,state:'failed',attempted:false,message:r.message||'접수 전 실패'}))}await report(job,r);changed=true;log('recovered',{job_id:job,state:d.state})}}
  catch(e){if(!current())return;if(e.code==='JOB_NOT_FOUND'&&resume){const messages=snapshot.messages.filter(m=>m.job_id===job&&m.state==='dispatching');const r=await window.MiraeSMS.sendAttendance(messages.map(m=>({notification_id:m.id,selected:m.selected,message:m.message})),job,null,messages[0]?.account_username);if(!current())return;await report(job,r);changed=true}else log('recovery.wait',{job_id:job,message:e.message})}
 }
 if(changed&&current()){const fresh=await cfg.api('/api/attendance/read?'+new URLSearchParams({class_id:cid,month:mon}));if(current()){data=fresh;paint()}}
}
async function sendPending(){
 if(busy||!data||view!=='live'||!cfg.can?.('attendance_notify'))return;busy=true;const g=generation,op=window.MiraeProgress.begin('출결 알림 저장 · 학부모 연결');if(!op){busy=false;return}
 try{
  await recover(true);if(g!==generation)return;const fresh=await cfg.api('/api/attendance/read?'+new URLSearchParams({class_id:classID,month}));if(g!==generation)return;data=fresh;
  const pending=data.messages.filter(m=>m.owner_id===cfg.user().id&&m.date===day()&&m.state==='pending');if(!pending.length){op.done('새로 보낼 출결 알림이 없습니다.');paint();return}
  if(window.MiraePC?.isMobile&&window.MiraePC.state!=='connected'&&!await window.MiraePC.connect(false)){op.fail('출결은 저장했습니다. 내 PC 연결 후 대기 알림 보내기를 눌러 주세요.');paint();status('출결 저장 완료 · 내 PC 미연결로 문자 알림은 대기합니다.',true);return}roster=await window.MiraeSMS.getRoster(false,p=>op.update(p));if(g!==generation)return;
  const ready=[],unmatched=[];for(const m of pending){const s=data.students.find(s=>s.id===m.student_id),match=s&&matching(s);if(match&&['auto','manual'].includes(match.kind))ready.push({id:m.id,selected:match.target.rows});else unmatched.push(m)}
  log('matching.summary',{pending:pending.length,matched:ready.length,unmatched:unmatched.length,source_fields:[...new Set(data.students.flatMap(s=>s.source_fields||[]))]});
  if(!ready.length){op.fail('학부모 연결을 확인할 학생이 '+unmatched.length+'명 있습니다. 출결 기록은 저장되어 있습니다.');paint();status('수신자 연결 버튼에서 학생을 확인한 뒤 대기 알림 보내기를 누르세요.',true);return}
  let accepted=0,stopped=false;for(let i=0;i<ready.length;i+=100){const job=crypto.randomUUID(),claim=await post('claim',{job_id:job,account_username:roster.account_username,items:ready.slice(i,i+100)});if(g!==generation)return;if(!claim.messages.length)continue;
   try{const r=await window.MiraeSMS.sendAttendance(claim.messages.map(m=>({notification_id:m.id,selected:m.selected,message:m.message})),job,p=>op.update(p),roster.account_username);if(g!==generation)return;await report(job,r);accepted+=r.accepted||0;if(r.accepted!==r.total){stopped=true;break}}
   catch(e){if(g!==generation)return;if(e.result?.state==='failed'&&!e.result?.attempted&&!e.result?.results)await report(job,{results:claim.messages.map(m=>({notification_id:m.id,state:'failed',attempted:false,message:e.message}))});throw e}
  }
  if(g!==generation)return;await load();const summary='엠스위치 접수 '+accepted+'건'+(unmatched.length?' · 연결 확인 필요 '+unmatched.length+'명':'');if(stopped)op.fail(summary+' · 일부 알림 처리를 멈췄습니다. 학생별 접수 상태를 확인하세요.');else op.done(summary);status('출결 기록 저장 완료 · '+summary+(stopped?' · 결과 불명인 알림은 공식 발송내역을 확인하세요.':''),stopped);
 }catch(e){if(g===generation){log('notification.failed',{message:e.message});op.fail('출결은 저장했습니다. '+e.message);await load();status('출결 저장 완료 · 문자 결과는 아래 기록을 확인하세요. '+e.message,true)}}finally{busy=false}
}
async function linkDialog(sid){if(busy||!data)return;const s=data.students.find(x=>x.id===sid);if(!s)return;
 const initialGeneration=generation;if(!roster){busy=true;try{roster=await window.MiraeSMS.getRoster(false)}catch(e){status(e.message,true);return}finally{busy=false}}
 if(initialGeneration!==generation||!data)return;const g=generation,dialog=document.createElement('div');dialog.className='modal-overlay attendance-link-dialog';dialog.innerHTML=`<section class="modal"><header class="modal-head"><h2>${esc(s.name)} · 학부모 수신자 연결</h2><button class="btn" data-link-close>닫기</button></header><div class="modal-body"><p>타임넷 원생번호 ${esc(s.student_no)} · ${esc((s.parent_phones||[]).join(' / ')||'학부모 연락처 미수신')}</p><p>엠스위치의 동일 학생을 선택해 한 번 연결해 주세요. 반 이름은 같을 필요가 없습니다.</p><input class="input" data-link-query placeholder="엠스위치 학생명 검색" value="${esc(s.name)}"><div data-link-list></div><p data-link-result role="status"></p></div></section>`;document.body.append(dialog);
 const list=dialog.querySelector('[data-link-list]'),all=A.targets(roster);function draw(){const q=dialog.querySelector('[data-link-query]').value.trim();const rows=all.filter(x=>!q||x.name.includes(q));list.innerHTML=rows.slice(0,100).map((x,i)=>`<button class="attendance-candidate" data-link-index="${i}"><strong>${esc(x.name)}</strong><span>${esc(x.school)} ${esc(x.grade)}</span><small>학부모 ${esc(x.parent_phones.join(' / ')||'번호 없음')}</small></button>`).join('')||'<p>검색 결과가 없습니다.</p>';list.querySelectorAll('button').forEach(b=>b.onclick=async()=>{const x=rows[Number(b.dataset.linkIndex)];if(!x.rows.length)return;try{const d=await post('link',{class_id:classID,student_id:sid,account_username:roster.account_username,cmem_seq:x.key,center:x.center,confirmed_name:x.name});if(g!==generation){dialog.remove();return}data.links=data.links.filter(l=>l.student_id!==sid);data.links.push(d.link);dialog.remove();paint();status(s.name+' 학생의 수신자를 연결했습니다. 대기 알림 보내기를 누르면 알림을 보냅니다.')}catch(e){dialog.querySelector('[data-link-result]').textContent=e.message}})}
 dialog.querySelector('[data-link-query]').oninput=draw;dialog.querySelector('[data-link-close]').onclick=()=>dialog.remove();draw();dialog.querySelector('[data-link-query]').focus();
}
function diagnostic(){if(!data){cfg.toast('반을 먼저 선택하세요.');return}const rows=data.students.map(s=>{const m=matching(s);return{site_student:{id:s.id,student_no:s.student_no,name:s.name,school:s.school,grade:s.grade,parent_phones:s.parent_phones,student_phone:s.student_phone,source_fields:s.source_fields,source_contact_fields:s.source_contact_fields},match:m.kind,mswitch_candidates:(m.candidates||[]).slice(0,5).map(x=>({name:x.name,raw:x.raw}))}});const report={version:'2.4.0',created_at:new Date().toISOString(),class_name:data.class.name,mswitch_fields:roster?[...new Set(roster.students.flatMap(s=>Object.keys(s.raw||{})))]:[],students:rows};const u=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download='미래탐구_출결_매칭진단.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),3000);cfg.toast('학생명·연락처가 포함된 매칭 진단을 저장했습니다. 비밀번호는 포함하지 않습니다.')}
async function mount(node){const user=cfg.user();if(!user||!cfg.can?.('attendance'))return;if(actor!==user.id)reset();actor=user.id;root=node;month||=day().slice(0,7);if(!classID){const k=A.korea();classID=A.pickClass(cfg.base().classes,user,k.date,k.time)?.id||''}paint();await load()}
function reset(){generation++;actor='';data=null;root=null;classID='';month='';view='live';draft.clear();roster=null;busy=false;document.querySelectorAll('.attendance-link-dialog').forEach(x=>x.remove())}
window.addEventListener('mirae-mswitch-roster',()=>{roster=window.MiraeSMS.cachedRoster;if(root?.isConnected&&cfg.active?.())paint()});window.addEventListener('mirae-log',loadLogs);window.MiraeAttendance={configure(c){cfg=c},mount,enter(){if(busy)return;view='live';classID='';month=day().slice(0,7);draft.clear()},reset};
})();
