/* Persistent parent contact workspace. Loading does not lock selection or input. */
(()=>{'use strict';let cfg={},owner='',registry=[],fetched=0,pending=null,state=null,host=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),digits=v=>String(v||'').replace(/\D/g,''),norm=v=>String(v||'').normalize('NFKC').replace(/\s/g,'').toLowerCase();
function matches(s,rows){let a=rows.filter(r=>r.name===s.name);if(s.student_no){const x=a.filter(r=>String(r.student_no)===String(s.student_no));if(x.length)return x}if(a.length>1&&s.school){const x=a.filter(r=>r.school===s.school);if(x.length)return x}return a}
function reset(){owner='';registry=[];fetched=0;pending=null;state=null;host=null}
function ensure(){const id=cfg.user?.()?.id;if(owner!==id){reset();owner=id;state={query:'',filter:'missing',upper:new Set(),work:new Map(),busy:false,message:'',results:[],error:null,lastAttempt:0}}return state}
function info(source){ensure();const candidates=matches(source,registry),r=candidates.length===1?candidates[0]:null;return{candidates,phone:digits(r?.parent_phone),kind:!fetched?'checking':!candidates.length?'unmatched':candidates.length>1?'ambiguous':digits(r.parent_phone)?'ok':'missing'}}
function summaries(){return(cfg.sources?.()||[]).map(source=>({...source,...info(source)}))}
function count(){const rows=summaries();return{ready:!!fetched,error:!!state?.error,missing:new Set(rows.filter(r=>r.kind==='missing').map(r=>r.parent_id||rowKey(r))).size,needs:new Set(rows.filter(r=>['missing','unmatched','ambiguous'].includes(r.kind)).map(r=>r.parent_id||rowKey(r))).size}}
function notify(){window.dispatchEvent(new Event('mirae-contact-status'));paint()}
async function prefetch(refresh=false){if(!cfg.can?.('mswitch_contact'))return;const st=ensure(),id=owner;if(pending)return pending;if(!refresh&&fetched&&Date.now()-fetched<30*60000)return registry;if(!refresh&&st.error&&Date.now()-st.lastAttempt<30000)return null;st.lastAttempt=Date.now();const progress=window.MiraeProgress?.begin('엠스위치에서 정보를 가져오는 중');st.message='엠스위치로부터 정보를 가져오는 중…';notify();
 const task=(async()=>{const creds=await cfg.credentials();if(owner!==id||cfg.user?.()?.id!==id)return;const r=await MiraePC.run('mswitch.contact.registry',{...creds,_site_owner:id,refresh},{onProgress:p=>{if(owner===id){st.message='엠스위치로부터 정보를 가져오는 중…';progress?.update(p);notify()}}});if(owner!==id||cfg.user?.()?.id!==id)return;registry=r.students||[];fetched=Date.now();st.error=null;st.message='연락처 확인 완료 · '+registry.length+'명';for(const row of st.work.values()){const a=matches(row.source,registry);row.candidates=a;if(!a.some(x=>x.mem_seq===row.chosen))row.chosen=a.length===1?a[0].mem_seq:'';row.original_phone=digits(a.find(x=>x.mem_seq===row.chosen)?.parent_phone);if(!row.edited){row.phone=row.original_phone;row.mode=row.original_phone?'replace':'add'}}progress?.done('연락처 확인 완료');notify();return registry})().catch(e=>{if(owner===id){st.error=e;st.message=e.message;progress?.fail('연락처 확인이 필요합니다.');notify()}return null}).finally(()=>{if(pending===task)pending=null;notify()});pending=task;notify();return task;
}
function status(r){return{checking:['checking','확인 중'],missing:['danger','전화번호 없음'],unmatched:['warn','학생 연결 확인'],ambiguous:['warn','동명이인 선택 필요'],ok:['ok','등록됨']}[r.kind]}
function rowKey(s){return s.id||String(s.student_no||s.name)}
function mount(node){if(!cfg.can?.('mswitch_contact'))return;ensure();host=node;node.innerHTML='<div class="page-head"><div><div class="eyebrow">학부모 관리</div><h1>전화번호 관리</h1><p class="subtitle">대상을 모은 뒤 전화번호를 함께 추가하거나 변경합니다.</p></div><button class="btn" data-contact-back>학부모 목록</button></div><div class="contact-fetch-strip" role="status"><span class="contact-fetch-dot"></span><span data-contact-status></span><button class="btn sm" data-refresh>명단 새로고침</button></div><section class="section contact-search-section"><div class="section-heading"><h2>학부모 찾기</h2><span data-catalog-count></span></div><div class="contact-catalog-tools"><input class="input" type="search" data-contact-query placeholder="학부모 · 학생 · 학교 · 전화번호 검색" aria-label="학부모 연락처 검색"><select class="input" data-contact-filter aria-label="연락처 상태"><option value="missing">확인이 필요한 연락처</option><option value="all">전체 연락처</option><option value="ok">전화번호 등록됨</option></select><button class="btn primary" data-move>선택한 대상 아래로 추가 ↓</button></div><div class="table-scroll contact-catalog-scroll"><table class="one-line-table contact-catalog"><thead><tr><th><input type="checkbox" data-catalog-all aria-label="검색 결과 전체 선택"></th><th>학부모</th><th>학생</th><th>학교 · 학년</th><th>현재 전화번호</th><th>상태</th></tr></thead><tbody></tbody></table></div></section><section class="section contact-work-section"><div class="section-heading"><h2>전화번호 입력</h2><span data-work-count></span></div><p class="sheet-help">여러 번호를 복사해 붙여넣을 수 있습니다. Enter와 방향키로 다음 행으로 이동합니다.</p><div class="table-scroll"><table class="one-line-table contact-sheet"><thead><tr><th>학부모 · 학생</th><th>엠스위치 학생 확인</th><th>현재 번호</th><th>입력할 번호</th><th>처리 방식</th><th>결과</th><th></th></tr></thead><tbody></tbody></table></div><div class="contact-savebar"><span data-save-result role="status"></span><button class="btn primary" data-save>목록의 연락처 순차 저장</button></div><details hidden data-contact-diagnostics><summary>오류 정보</summary><textarea class="input" rows="6" readonly aria-label="오류 정보"></textarea><button class="btn sm" data-copy>오류 정보 복사</button></details></section>';
 node.querySelector('[data-contact-back]').onclick=cfg.back;const q=node.querySelector('[data-contact-query]'),filter=node.querySelector('[data-contact-filter]');q.value=state.query;filter.value=state.filter;q.oninput=()=>{state.query=q.value;if(norm(state.query))state.filter='all';filter.value=state.filter;paintCatalog()};filter.onchange=()=>{state.filter=filter.value;paintCatalog()};node.querySelector('[data-refresh]').onclick=()=>prefetch(true);node.querySelector('[data-move]').onclick=move;node.querySelector('[data-save]').onclick=save;node.querySelector('[data-catalog-all]').onchange=e=>{for(const r of filtered())e.target.checked?state.upper.add(rowKey(r)):state.upper.delete(rowKey(r));paintCatalog()};node.querySelector('[data-copy]').onclick=async()=>{const x=node.querySelector('[data-contact-diagnostics] textarea');try{await navigator.clipboard.writeText(x.value);cfg.toast('복사완료')}catch{x.focus();x.select()}};paint();prefetch();
}
function filtered(){const key=norm(state?.query);return summaries().filter(r=>{const text=norm([r.parent_name,r.name,r.school,r.grade,r.phone].join(' '));return(!key||text.includes(key))&&(key||state.filter==='all'||state.filter==='ok'&&r.kind==='ok'||state.filter==='missing'&&r.kind!=='ok')}).sort((a,b)=>a.name.localeCompare(b.name,'ko'))}
function paintCatalog(){if(!host?.isConnected||!state||!host.querySelector('[data-contact-status]'))return;const rows=filtered();host.querySelector('[data-catalog-count]').textContent='조회 '+rows.length+'명';host.querySelector('.contact-catalog tbody').innerHTML=rows.map(r=>{const key=rowKey(r),[tone,label]=status(r);return'<tr><td><input type="checkbox" data-source="'+esc(key)+'" aria-label="'+esc(r.parent_name||r.name+' 학부모')+' 선택" '+(state.upper.has(key)?'checked':'')+' '+(state.work.has(key)?'disabled':'')+'></td><td>'+esc(r.parent_name||r.name+' 학부모')+'</td><td>'+esc(r.name)+'</td><td>'+esc([r.school,r.grade].filter(Boolean).join(' · '))+'</td><td>'+esc(r.phone||(r.kind==='checking'?'확인 중':'없음'))+'</td><td><strong class="connection-state '+tone+'">'+label+'</strong></td></tr>'}).join('')||'<tr><td colspan="6" class="muted">일치하는 대상이 없습니다.</td></tr>';host.querySelectorAll('[data-source]').forEach(x=>x.onchange=()=>{x.checked?state.upper.add(x.dataset.source):state.upper.delete(x.dataset.source)});const all=host.querySelector('[data-catalog-all]');const available=rows.filter(r=>!state.work.has(rowKey(r)));all.disabled=!available.length;all.checked=!!available.length&&available.every(r=>state.upper.has(rowKey(r)));all.indeterminate=available.some(r=>state.upper.has(rowKey(r)))&&!all.checked}
function move(){const rows=summaries();for(const key of state.upper){if(state.work.size>=100){cfg.toast('한 번에 최대 100명까지 처리합니다.',true);break}const source=rows.find(r=>rowKey(r)===key);if(!source||state.work.has(key))continue;state.work.set(key,{source,key,row_id:key,candidates:source.candidates,chosen:source.candidates.length===1?source.candidates[0].mem_seq:'',phone:source.phone||'',original_phone:source.phone||'',mode:source.phone?'replace':'add',edited:false,done:false,message:''})}state.upper.clear();paint()}
function paint(){if(!host?.isConnected||!state||!host.querySelector('[data-contact-status]'))return;const active=document.activeElement,focus=active?.dataset.cell&&active.closest('[data-row]')?{key:active.closest('[data-row]').dataset.row,cell:active.dataset.cell,start:active.selectionStart,end:active.selectionEnd}:null;host.querySelector('[data-contact-status]').textContent=state.message||'엠스위치로부터 정보를 가져오는 중…';host.querySelector('.contact-fetch-strip').classList.toggle('loading',!!pending);host.querySelector('[data-refresh]').disabled=!!pending||state.busy;paintCatalog();const rows=[...state.work.values()];host.querySelector('[data-work-count]').textContent=rows.length+'명';host.querySelector('.contact-sheet tbody').innerHTML=rows.map(r=>'<tr data-row="'+esc(r.key)+'"><td>'+esc(r.source.parent_name||r.source.name+' 학부모')+' <small>· '+esc(r.source.name)+'</small></td><td><select class="input" data-cell="chosen" aria-label="'+esc(r.source.name)+' 엠스위치 학생" '+(r.done||state.busy?'disabled':'')+'><option value="">'+(!fetched?'조회 중':r.candidates.length>1?'동명이인 선택':'학생 확인')+'</option>'+r.candidates.map(x=>'<option value="'+esc(x.mem_seq)+'" '+(r.chosen===x.mem_seq?'selected':'')+'>'+esc([x.name,x.school,x.grade,x.classes].filter(Boolean).join(' · '))+'</option>').join('')+'</select></td><td>'+esc(r.original_phone||'없음')+'</td><td><input class="input" type="tel" inputmode="tel" data-cell="phone" maxlength="20" placeholder="010-0000-0000" value="'+esc(r.phone)+'" aria-label="'+esc(r.source.name)+' 학부모 전화번호" '+(r.done||state.busy?'disabled':'')+'></td><td><select class="input" data-cell="mode" '+(r.done||state.busy?'disabled':'')+'><option value="replace" '+(r.mode==='replace'?'selected':'')+'>대표번호 수정</option><option value="add" '+(r.mode==='add'?'selected':'')+'>새 번호 추가</option></select></td><td class="'+(r.done&&r.ok?'contact-done':r.message?'contact-error':'')+'">'+esc(r.message||(!fetched?'번호 먼저 입력 가능':'입력 대기'))+'</td><td><button class="icon-btn" data-remove="'+esc(r.key)+'" aria-label="'+esc(r.source.name)+' 목록에서 빼기" '+(state.busy?'disabled':'')+'>×</button></td></tr>').join('')||'<tr><td colspan="7" class="contact-empty">위 목록에서 수정할 학부모를 선택해 아래로 추가하세요.</td></tr>';
 host.querySelectorAll('[data-cell]').forEach(x=>{const row=state.work.get(x.closest('tr').dataset.row);x.addEventListener(x.tagName==='SELECT'?'change':'input',()=>{row[x.dataset.cell]=x.value;row.edited=true;if(x.dataset.cell==='chosen'){row.original_phone=digits(row.candidates.find(c=>c.mem_seq===x.value)?.parent_phone);paint()}})});host.querySelectorAll('[data-remove]').forEach(x=>x.onclick=()=>{state.work.delete(x.dataset.remove);paint()});const inputs=[...host.querySelectorAll('[data-cell=phone]:not(:disabled)')];inputs.forEach((x,i)=>{x.onkeydown=e=>{if(['Enter','ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();inputs[i+(e.key==='ArrowUp'?-1:1)]?.focus()}};x.onpaste=e=>{const text=e.clipboardData?.getData('text/plain');if(!text||!/[\r\n]/.test(text))return;e.preventDefault();text.trim().split(/\r?\n/).forEach((v,n)=>{const el=inputs[i+n];if(el){el.value=v.split('\t').at(-1).trim();el.dispatchEvent(new Event('input'))}})}});
 host.querySelector('[data-save]').disabled=state.busy||!fetched||!rows.some(r=>!r.done);host.querySelector('[data-save-result]').textContent=state.result||'';const d=host.querySelector('[data-contact-diagnostics]');d.hidden=!state.error;if(state.error)d.querySelector('textarea').value=JSON.stringify({time:new Date().toISOString(),version:'3.7.0',message:state.error.message,results:state.results,code:state.error.result?.code,logs:state.error.result?.logs||[]},null,2);if(focus){const el=[...host.querySelectorAll('[data-row]')].find(x=>x.dataset.row===focus.key)?.querySelector('[data-cell='+focus.cell+']');el?.focus();if(focus.start!=null)try{el?.setSelectionRange(focus.start,focus.end)}catch{}}
}
async function save(){if(state.busy)return;const st=state,id=owner,selection=[...st.work.values()].filter(r=>!r.done),ids=new Set();if(!selection.length)return;for(const r of selection){r.phone=digits(r.phone);if(!r.chosen)return cfg.toast(r.source.name+' 학생을 확인하세요.',true);if(!/^01[016789]\d{7,8}$/.test(r.phone))return cfg.toast(r.source.name+' 학부모 전화번호를 확인하세요.',true);if(ids.has(r.chosen))return cfg.toast('같은 학생이 중복 선택되어 있습니다.',true);ids.add(r.chosen)}if(!confirm(selection.length+'명의 학부모 연락처를 저장할까요?'))return;
 st.busy=true;st.error=null;st.results=[];const progress=window.MiraeProgress?.begin('학부모 연락처를 저장하는 중');st.result='연락처를 순차 저장하는 중';paint();let submitted=false;
 try{const creds=await cfg.credentials();if(id!==cfg.user?.()?.id||owner!==id)throw Error('로그인 계정이 변경되었습니다.');submitted=true;const r=await MiraePC.run('mswitch.contact.batch',{...creds,_site_owner:id,items:selection.map(x=>({row_id:x.row_id,mem_seq:x.chosen,name:x.candidates.find(c=>c.mem_seq===x.chosen).name,phone:x.phone,mode:x.mode}))},{onProgress:p=>{if(owner===id){st.result='연락처를 저장하는 중 · '+(p.done||0)+' / '+(p.total||selection.length);progress?.update(p);paint()}}});if(owner!==id||cfg.user?.()?.id!==id)return;st.results=r.results||[];const saved=[];for(const result of st.results){const row=selection.find(x=>x.row_id===result.row_id);if(!row)continue;row.done=result.ok===true||result.attempted===true;row.ok=result.ok===true;row.message=result.message;if(result.ok){saved.push({source:row.source,result:{...result,account_username:creds.username,mode:row.mode,old_phone:row.original_phone}});const item=registry.find(x=>x.mem_seq===row.chosen);if(item)item.parent_phone=result.phone;row.original_phone=result.phone}}
  paint();if(saved.length){st.result='저장 완료 · 연락처 목록을 갱신하는 중';paint();let roster;try{roster=await MiraeSMS.getRoster(true,p=>progress?.update(p))}catch(e){st.error=e}if(owner!==id)return;for(const x of saved){const a=(roster?.rows||[]).filter(v=>v.name===x.result.name&&digits(v.phone)===x.result.phone),keys=[...new Set(a.map(v=>String(v.raw.CMEM_SEQ)))];x.result.cmem_seq=keys.length===1?keys[0]:'';x.result.center=keys.length===1?String(a[0].raw.CENTER_SEQ):''}await cfg.onSavedBatch?.(saved)}
  st.result='등록 확인 '+saved.length+'명 · 미완료 '+(selection.length-saved.length)+'명';if(st.results.some(x=>!x.ok))st.error=Error(st.result);progress?.done(st.result);cfg.toast('연락처 처리 완료');notify();
 }catch(e){if(owner===id){st.error=e;st.result=e.message;if(submitted&&!st.results.length)selection.forEach(r=>{r.done=true;r.message='결과 확인 필요 · 명단 확인 후 재처리'});progress?.fail('연락처 처리 결과를 확인해 주세요.')}}finally{if(owner===id){st.busy=false;notify()}}
}
function open(){return cfg.open?.()}function openBatch(){return open()}
window.MiraeContacts={VERSION:'3.7.0',configure(c){cfg=c},mount,prefetch,count,reset,open,openBatch,matches,info};})();
