/* Registry fetched once; edits share one PC job and one final SMS roster refresh. */
(()=>{'use strict';let cfg={},active=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function matches(source,rows){let a=rows.filter(r=>r.name===source.name);const no=String(source.student_no||'');if(no){const x=a.filter(r=>String(r.student_no)===no);if(x.length)return x}if(a.length>1&&source.school){const x=a.filter(r=>r.school===source.school);if(x.length)return x}return a}
async function open(source){return openBatch(source?[source]:cfg.sources?.()||[])}
async function openBatch(sources){
 if(!cfg.can?.('mswitch_contact'))return cfg.toast?.('전화번호 등록 권한이 없습니다.',true);if(active)return;
 sources=sources.slice(0,100);if(!sources.length)return cfg.toast?.('등록할 학생을 선택해 주세요.',true);
 const owner=cfg.user()?.id,previous=document.activeElement,box=document.createElement('div');active=box;
 box.className='modal-overlay contact-overlay';box.innerHTML=`<section class="modal wide contact-batch-modal" role="dialog" aria-modal="true" aria-labelledby="contact-title"><header class="modal-head"><div><h2 id="contact-title">학부모 연락처 일괄 등록</h2><small>학생 확인 → 번호 입력 → 한 번에 저장</small></div><button class="icon-btn" data-close aria-label="닫기">×</button></header><div class="modal-body"><p class="management-intro">명단을 한 번 불러와 함께 처리합니다. 추가한 번호를 대표 연락처로 지정하며 다른 학부모 연락처는 보존합니다.</p><div class="contact-batch-tools"><button class="btn" data-refresh>학생 명단 다시 불러오기</button><span data-contact-status role="status">학생 명단을 가져오는 중</span></div><div class="table-scroll contact-sheet-scroll"><table class="one-line-table contact-sheet"><thead><tr><th><input type="checkbox" data-check-all aria-label="전체 선택" checked></th><th>학생</th><th>엠스위치 학생 확인</th><th>현재 대표번호</th><th>등록할 전화번호</th><th>등록 방식</th><th>결과</th></tr></thead><tbody></tbody></table></div><details hidden data-contact-diagnostics><summary>오류 정보</summary><textarea class="input" rows="7" readonly aria-label="오류 정보"></textarea><button class="btn sm" data-copy>오류 정보 복사</button></details></div><footer class="modal-footer"><button class="btn" data-close>닫기</button><button class="btn primary" data-save disabled>선택한 연락처 일괄 저장</button></footer></section>`;
 document.body.append(box);document.body.classList.add('modal-open');const $=s=>box.querySelector(s),status=$('[data-contact-status]');let busy=false,creds,students=[],results=[],ready=false;
 const rows=sources.map((source,i)=>({source,row_id:String(i),candidates:[],chosen:'',phone:'',mode:'add',checked:true,done:false,message:''}));
 const current=()=>box.isConnected&&cfg.user()?.id===owner;
 const error=e=>{status.textContent=e.message;status.classList.add('error');const d=$('[data-contact-diagnostics]');d.hidden=false;d.querySelector('textarea').value=JSON.stringify({time:new Date().toISOString(),version:'3.5.0',operation:'contact_batch',message:e.message,code:e.result?.code||e.code,results,diagnostics:e.result?.logs||[]},null,2)};
 function locks(value){busy=value;box.querySelectorAll('button,input,select').forEach(b=>b.disabled=value);box.querySelectorAll('[data-row]').forEach(el=>{if(rows[+el.dataset.row].done)el.querySelectorAll('input,select').forEach(x=>x.disabled=true)});$('[data-save]').disabled=value||!ready}
 function close(){if(busy)return;box.remove();active=null;if(!document.querySelector('.modal-overlay'))document.body.classList.remove('modal-open');previous?.focus?.()}
 box.querySelectorAll('[data-close]').forEach(b=>b.onclick=close);box.onkeydown=e=>{if(e.key==='Escape'){e.preventDefault();close()}if(e.key==='Tab'){const a=[...box.querySelectorAll('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea')].filter(x=>x.offsetParent!==null),first=a[0],last=a.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};
 function draw(){
  $('tbody').innerHTML=rows.map(r=>{const c=r.candidates.find(x=>x.mem_seq===r.chosen);return `<tr data-row="${r.row_id}"><td><input type="checkbox" data-cell="checked" ${r.checked?'checked':''} ${r.done?'disabled':''} aria-label="${esc(r.source.name)} 선택"></td><td>${esc(r.source.name)}</td><td><select class="input" data-cell="chosen" ${r.done?'disabled':''} aria-label="${esc(r.source.name)} 엠스위치 학생">${r.candidates.length!==1?'<option value="">'+(r.candidates.length?'동명이인 선택 필요':'일치하는 학생 없음')+'</option>':''}${r.candidates.map(x=>'<option value="'+esc(x.mem_seq)+'" '+(r.chosen===x.mem_seq?'selected':'')+'>'+esc([x.name,x.school,x.grade,x.classes].filter(Boolean).join(' · '))+'</option>').join('')}</select></td><td data-current-phone>${esc(c?.parent_phone||'없음')}</td><td><input class="input" type="tel" inputmode="tel" data-cell="phone" value="${esc(r.phone)}" ${r.done?'disabled':''} maxlength="20" placeholder="010-0000-0000" aria-label="${esc(r.source.name)} 전화번호"></td><td><select class="input" data-cell="mode" ${r.done?'disabled':''} aria-label="${esc(r.source.name)} 등록 방식"><option value="add" ${r.mode==='add'?'selected':''}>번호 추가</option><option value="replace" ${r.mode==='replace'?'selected':''}>대표번호 변경</option></select></td><td data-row-result class="${r.done?'contact-done':r.message?'contact-error':''}">${esc(r.message||'입력 대기')}</td></tr>`}).join('');
  box.querySelectorAll('[data-cell]').forEach(el=>{const r=rows[+el.closest('[data-row]').dataset.row];el.addEventListener(el.type==='checkbox'||el.tagName==='SELECT'?'change':'input',()=>{r[el.dataset.cell]=el.type==='checkbox'?el.checked:el.value;if(el.dataset.cell==='chosen')el.closest('tr').querySelector('[data-current-phone]').textContent=r.candidates.find(x=>x.mem_seq===r.chosen)?.parent_phone||'없음'})});
  box.querySelectorAll('[data-cell=phone]').forEach(el=>{el.onkeydown=e=>{if(['Enter','ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();const j=+el.closest('tr').dataset.row+(e.key==='ArrowUp'?-1:1);box.querySelector('[data-row="'+j+'"] [data-cell=phone]:not(:disabled)')?.focus()}};el.onpaste=e=>{const text=e.clipboardData?.getData('text/plain');if(!text||!/[\n\r]/.test(text))return;e.preventDefault();const start=+el.closest('tr').dataset.row;text.trim().split(/\r?\n/).forEach((v,n)=>{const r=rows[start+n];if(r&&!r.done){r.phone=v.split('\t').at(-1).trim();box.querySelector('[data-row="'+r.row_id+'"] [data-cell=phone]').value=r.phone}})}})
 }
 $('[data-check-all]').onchange=e=>{rows.forEach(r=>{if(!r.done)r.checked=e.target.checked});draw()};
 $('[data-copy]').onclick=async()=>{const t=$('[data-contact-diagnostics] textarea');try{await navigator.clipboard.writeText(t.value);cfg.toast?.('복사완료')}catch{t.focus();t.select()}};
 async function load(refresh=false){if(busy)return;locks(true);status.classList.remove('error');try{creds=await cfg.credentials();const r=await MiraePC.run('mswitch.contact.registry',{...creds,_site_owner:owner,refresh},{onProgress:p=>{if(current())status.textContent=p.label||'학생 명단을 가져오는 중'}});if(!current())return;students=r.students||[];rows.forEach(r=>{r.candidates=matches(r.source,students);if(!r.candidates.some(c=>c.mem_seq===r.chosen))r.chosen=r.candidates.length===1?r.candidates[0].mem_seq:''});ready=true;draw();status.textContent='명단 '+students.length+'명 · 아래 번호를 입력해 주세요.'}catch(e){if(current())error(e)}finally{locks(false)}}
 $('[data-refresh]').onclick=()=>load(true);
 $('[data-save]').onclick=async()=>{
  if(busy||!current())return;const selection=rows.filter(r=>r.checked&&!r.done);if(!selection.length)return cfg.toast?.('처리할 학생을 선택해 주세요.',true);
  const ids=new Set();for(const r of selection){r.phone=r.phone.replace(/\D/g,'');if(!r.chosen)return cfg.toast?.(r.source.name+' 학생을 먼저 확인해 주세요.',true);if(!/^01[016789]\d{7,8}$/.test(r.phone))return cfg.toast?.(r.source.name+' 학생의 전화번호를 확인해 주세요.',true);if(ids.has(r.chosen))return cfg.toast?.('같은 학생을 중복 선택했습니다.',true);ids.add(r.chosen)}
  if(!confirm(selection.length+'명의 연락처를 엠스위치에 저장할까요? 추가한 번호가 대표 연락처가 됩니다.'))return;
  locks(true);status.classList.remove('error');try{
   const r=await MiraePC.run('mswitch.contact.batch',{...creds,_site_owner:owner,items:selection.map(x=>({row_id:x.row_id,mem_seq:x.chosen,name:x.candidates.find(c=>c.mem_seq===x.chosen).name,phone:x.phone,mode:x.mode}))},{onProgress:p=>{if(current())status.textContent=(p.label||'등록하는 중')+(p.total?' · '+(p.done||0)+' / '+p.total:'')}});if(!current())return;
   results=r.results||[];const saved=[];results.forEach(result=>{const row=rows.find(x=>x.row_id===result.row_id);if(!row)return;row.message=result.message;row.done=result.ok===true||result.attempted===true;row.checked=false;if(result.ok)saved.push({source:row.source,result:{...result,account_username:creds.username}})});draw();
   let rosterError=null;if(saved.length){status.textContent='저장 완료 · 문자 명단을 한 번 새로고침하는 중';let roster;try{roster=await MiraeSMS.getRoster(true,p=>{if(current())status.textContent=p.label||'명단을 가져오는 중'})}catch(e){rosterError=e}
    if(!current())return;for(const x of saved){const a=(roster?.rows||[]).filter(r=>r.name===x.result.name&&String(r.phone).replace(/\D/g,'')===x.result.phone),ids=[...new Set(a.map(r=>String(r.raw.CMEM_SEQ)))];x.result.cmem_seq=ids.length===1?ids[0]:'';x.result.center=ids.length===1?String(a[0].raw.CENTER_SEQ):''}await cfg.onSavedBatch?.(saved);window.dispatchEvent(new Event('mirae-mswitch-roster'));
   }
   status.textContent='등록 확인 '+saved.length+'명 · 미완료 '+(selection.length-saved.length)+'명'+(rosterError?' · 문자 명단 새로고침 필요':'');if(results.some(r=>!r.ok)||rosterError)error(Error(status.textContent+(rosterError?' · '+rosterError.message:'')));cfg.toast?.('연락처 처리 완료');
  }catch(e){if(current()){selection.forEach(r=>{r.done=true;r.checked=false;r.message='결과 확인 필요 · 명단 확인 후 다시 처리'});draw();error(e)}}finally{locks(false)}
 };
 draw();await load();
}
window.MiraeContacts={VERSION:'3.5.0',configure(c){cfg=c},open,openBatch,matches};})();
