(()=>{'use strict';const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let cfg={};
function validateLinks(rows){if(!Array.isArray(rows)||rows.length>20)throw Error('링크는 종류별 최대 20개입니다.');return rows.map(r=>{const u=new URL(String(r.url||''));if(!['http:','https:'].includes(u.protocol)||u.username||u.password||u.href.length>2000)throw Error('올바른 http/https 링크를 입력하세요.');return{title:String(r.title||'열기').trim().slice(0,120)||'열기',url:u.href}})}
function parseLinks(text){return validateLinks(String(text||'').split('\n').map(x=>x.trim()).filter(Boolean).map(x=>{const i=x.indexOf('|');return{title:i<0?'열기':x.slice(0,i).trim(),url:i<0?x:x.slice(i+1).trim()}}))}
function linkText(rows){return(rows||[]).map(r=>r.title+' | '+r.url).join('\n')}
function linksHTML(l){return[['수업 영상',l.video_links],['추가 자료',l.material_links]].filter(([,v])=>v?.length).map(([title,rows])=>'<section class="detail-section"><h3>'+title+'</h3>'+rows.map(r=>'<a class="btn sm" target="_blank" rel="noopener noreferrer" href="'+esc(r.url)+'">'+esc(r.title)+'</a>').join(' ')+'</section>').join('')}
async function mount(node,id,tab){const family=['parent','student'].includes(cfg.user().role);node.innerHTML='<div class="page-head"><div><h1>강좌 설정</h1></div><button class="btn" data-course-back>강좌 목록</button></div><div role="status" data-course-body>강좌를 확인하고 있습니다.</div>';node.querySelector('[data-course-back]').onclick=cfg.back;let records;
 try{records=await cfg.api('/api/course-records?class_id='+encodeURIComponent(id));if(!node.isConnected)return;draw(tab)}catch(e){if(node.isConnected)node.querySelector('[data-course-body]').textContent=e.message}
 function draw(tab){if(family)tab='records';cfg.tab(tab);const c=records.class;node.querySelector('h1').textContent=c.name;const b=node.querySelector('[data-course-body]');b.innerHTML=(!family?'<div class="sub-tabs"><button class="'+(tab==='settings'?'active':'')+'" data-course-tab="settings">강좌 설정</button><button class="'+(tab==='records'?'active':'')+'" data-course-tab="records">수업 기록</button></div>':'');b.querySelectorAll('[data-course-tab]').forEach(x=>x.onclick=()=>draw(x.dataset.courseTab));
 if(tab==='settings'){b.insertAdjacentHTML('beforeend','<section class="section course-info"><dl><dt>담당강사</dt><dd>'+esc(cfg.base().teachers?.find(t=>t.id===c.teacher_id)?.name||'')+'</dd><dt>운영 상태</dt><dd>'+(c.status==='active'?'개설':'종강 · 폐강')+'</dd><dt>개강 · 종강</dt><dd>'+esc(c.start_date)+' ~ '+esc(c.end_date||'미지정')+'</dd><dt>요일 · 시간</dt><dd>'+esc((c.weekdays||[]).map(d=>['일','월','화','수','목','금','토'][d]).join(' · '))+' '+esc(c.start_time||'')+' ~ '+esc(c.end_time||'')+'</dd><dt>과목</dt><dd>'+esc(c.subject||'')+'</dd></dl><div class="flex wrap"><button class="btn" data-plan>강의계획</button>'+(cfg.can('class_edit')?'<button class="btn primary" data-course-edit>강좌 정보 · 개설/종강 수정</button>':'')+'<button class="btn" data-records>수업 기록</button></div></section>');b.querySelector('[data-plan]').onclick=()=>cfg.syllabus(id);b.querySelector('[data-course-edit]')?.addEventListener('click',()=>cfg.editClass(id));b.querySelector('[data-records]').onclick=()=>draw('records');return}
 b.insertAdjacentHTML('beforeend','<section class="section"><div class="compact-filters"><input class="input" data-lesson-query placeholder="날짜 · 진도 · 숙제 검색"><button class="btn" data-plan>강의계획</button>'+(!family&&cfg.can('lesson_edit')?'<button class="btn primary" data-lesson-new>수업 기록 추가</button>':'')+'</div><div class="table-scroll" data-record-list></div></section>');b.querySelector('[data-plan]').onclick=()=>cfg.syllabus(id);b.querySelector('[data-lesson-new]')?.addEventListener('click',()=>cfg.editLesson(null,id));b.querySelector('[data-lesson-query]').oninput=list;list();
 function list(){const key=b.querySelector('[data-lesson-query]').value.toLowerCase(),rows=records.lessons.filter(l=>!key||[l.lesson_date,l.title,l.progress,l.homework].join(' ').toLowerCase().includes(key)).sort((a,b)=>b.lesson_date.localeCompare(a.lesson_date));b.querySelector('[data-record-list]').innerHTML='<table class="one-line-table"><thead><tr><th>수업일</th><th>수업 제목</th><th>진도</th><th>숙제</th><th>영상</th><th>추가 자료</th><th>학생 피드백</th><th>공개</th><th>확인</th></tr></thead><tbody>'+rows.map(l=>{const v=records.videos.filter(v=>v.lesson_id===l.id||!v.lesson_id&&v.video_date===l.lesson_date),f=records.feedback.filter(f=>f.lesson_id===l.id),video=(l.video_links||[]).length+v.length;return'<tr><td>'+esc(l.lesson_date)+'</td><td>'+esc(l.title)+'</td><td>'+esc(l.progress||'—')+'</td><td>'+esc(l.homework||'—')+'</td><td>'+video+'개'+(family&&video?'<button class="btn sm" data-lesson-show="'+esc(l.id)+'">영상 보기</button>':'')+'</td><td>'+(l.material_links||[]).length+'개</td><td>'+esc(family?f.map(f=>f.comment).filter(Boolean).join(' · ')||'—':f.filter(f=>f.comment).length+'명')+'</td><td>'+(l.published===false?'비공개':'공개')+'</td><td><button class="btn sm" data-lesson-show="'+esc(l.id)+'">보기</button>'+(!family&&cfg.can('lesson_edit')?'<button class="btn sm" data-lesson-edit="'+esc(l.id)+'">수정</button>':'')+(!family&&cfg.reportAllowed?.(c)?'<button class="btn sm" data-lesson-report="'+esc(l.id)+'">'+(cfg.can('report_send')?'레포트 발송':'알림 상태')+'</button>':'')+'</td></tr>'}).join('')+'</tbody></table>'+(!rows.length?'<p>등록된 수업 기록이 없습니다.</p>':'');b.querySelectorAll('[data-lesson-show]').forEach(x=>x.onclick=()=>cfg.detail(x.dataset.lessonShow,id));b.querySelectorAll('[data-lesson-edit]').forEach(x=>x.onclick=()=>cfg.editLesson(x.dataset.lessonEdit,id));b.querySelectorAll('[data-lesson-report]').forEach(x=>x.onclick=()=>cfg.report(x.dataset.lessonReport))}
 }
}
window.MiraeCourses={VERSION:'3.5.0',configure(c){cfg=c},openLesson:(id,cid)=>cfg.detail(id,cid),validateLinks,parseLinks,linkText,linksHTML,mount};})();
