/* Browser-direct MSwitch. Success requires readable credentialed CORS responses from MSwitch. */
(()=>{'use strict';
const LOGIN='https://mswitch.t-ime.com',REMOTE='https://pmams.t-ime.com',SMS='/sms/SmsSendMngtN/';
let cfg={},meta=null,owner='',generation=0,selected=new Map(),busy=false,blockedSend=false,lastAuto='',pending=null;
const $=(s,r=document)=>r.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),digits=s=>String(s||'').replace(/\D/g,''),log=(event,d={})=>window.MiraeStore.log('mswitch.'+event,d);
function official(){return '<a class="btn" href="https://mswitch.t-ime.com/login.do" target="_blank" rel="noopener noreferrer">엠스위치 공식 사이트 열기</a>'}
function logsHTML(){return '<p>계정 저장과 실제 로그인 성공은 별개입니다. 응답을 읽지 못하면 발송 성공으로 표시하지 않습니다.</p><textarea class="v2-log msw-log" readonly aria-label="엠스위치 로그"></textarea><button class="btn" data-msw-copy>로그 복사</button> <button class="btn" data-msw-save-log>텍스트 파일 저장</button>'}
function bindLogs(root){const area=$('.msw-log',root);const paint=()=>{if(area.isConnected){area.value=window.MiraeStore.logs();area.scrollTop=area.scrollHeight}else window.removeEventListener('mirae-log',paint)};paint();window.addEventListener('mirae-log',paint);$('[data-msw-copy]',root).onclick=async()=>{try{await navigator.clipboard.writeText(area.value);cfg.toast('복사했습니다.')}catch{area.focus();area.select();cfg.toast('Ctrl+C로 복사하세요.')}};$('[data-msw-save-log]',root).onclick=()=>{const u=URL.createObjectURL(new Blob([area.value],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download='mirae-v2-mswitch-log.txt';a.click();setTimeout(()=>URL.revokeObjectURL(u),3000)}}
async function request(base,path,{form,json,credentials=true}={}){
 const url=new URL(path,base);if(![LOGIN,REMOTE].includes(url.origin))throw Error('허용되지 않은 연동 주소입니다.');
 const method=form||json?'POST':'GET',headers={},opts={method,credentials:credentials?'include':'omit',mode:'cors',redirect:'follow',signal:AbortSignal.timeout(15000)};
 if(form){headers['Content-Type']='application/x-www-form-urlencoded;charset=UTF-8';opts.body=new URLSearchParams(form)}
 if(json){headers['Content-Type']='application/json;charset=UTF-8';headers['X-Requested-With']='XMLHttpRequest';opts.body=JSON.stringify(json)}opts.headers=headers;
 log('request',{host:url.hostname,path:url.pathname,method,credentialed:credentials});let r;
 try{r=await fetch(url,opts)}catch(e){log('response_unreadable',{host:url.hostname,path:url.pathname,kind:e.name});throw Error('브라우저에서 엠스위치 응답을 읽지 못했습니다. CORS·쿠키 제한 또는 네트워크 오류일 수 있습니다. HTML에서 이 제한을 해제할 수 없습니다.')}
 log('response',{host:url.hostname,path:url.pathname,status:r.status});if(!r.ok)throw Error('엠스위치 HTTP '+r.status+' 응답입니다.');return r;
}
async function post(path,form={}){const r=await request(REMOTE,path,{form});let d;try{d=await r.json()}catch{throw Error('엠스위치 세션이 종료되었거나 응답 형식이 바뀌었습니다. 다시 연동하세요.')}return d}
async function connect(credentials,keepSelection=false){
 const g=generation,id=cfg.user()?.id;meta=null;if(!keepSelection||owner!==id)selected.clear();
 const d=await(await request(LOGIN,'/login.json',{form:{LOGIN_ID:credentials.username,LOGIN_PWD:credentials.password}})).json();
 const ticket=d.S_ARI_SECURE_TOKEN||d.LOGIN_TOKEN,center=String(d.S_CENTER_SEQ||d.CENTER_SEQ||'');
 log('login.first_stage',{code:String(d.result_code||''),has_ticket:!!ticket});
 if(String(d.result_code||'0000')!=='0000'||!ticket||!center)throw Error('엠스위치 아이디·비밀번호를 확인하세요.');
 if(d.WWW&&d.WWW.replace(/\/$/,'')!==REMOTE)throw Error('이 계정은 기존 HAR과 다른 서버를 사용합니다. 새 로그인 기록이 필요합니다.');
 await request(REMOTE,'/tokenLogin.do?'+new URLSearchParams({CENTER_SEQ:center,LOGIN_TOKEN:ticket}));
 let name='';for(const path of ['/main/profile.do','/main/top.do']){const html=await(await request(REMOTE,path)).text();const dom=new DOMParser().parseFromString(html,'text/html');name=dom.querySelector('.log_info_btn strong')?.textContent?.trim()||'';if(name)break}
 if(!name)throw Error('로그인한 이름을 확인하지 못했습니다. 연동 성공으로 처리하지 않았습니다.');
 const b=(await post('/main/balanceInfo.json')).balanceInfoMngt||{},group=String(b.GROUP_CODE||'');if(!group||b.CENTER_SEQ!=null&&String(b.CENTER_SEQ)!==center)throw Error('로그인 센터 정보를 확인하지 못했습니다.');
 const service=String((await post(SMS+'selectCenterServiceCode.json',{strCenterSeq:center})).info?.SERVICE_CODE||'');
 const list=(await post(SMS+'selectReplyList.json')).info;const replies=Array.isArray(list)?list.map(x=>digits(x.ORG_REPLY_TEL||x.REPLY_TEL)).filter(Boolean):[];
 if(!service||!replies.length)throw Error('문자 서비스 코드 또는 발신번호를 확인하지 못했습니다.');
 if(g!==generation||id!==cfg.user()?.id)throw Error('로그인한 사이트 계정이 변경되었습니다. 다시 연동하세요.');
 meta={name,center,group,service,replies,until:Date.now()+15*60000};owner=id;blockedSend=false;log('login.verified',{sender_count:replies.length});return meta;
}
async function connectSaved(keepSelection=false){if(pending)return pending;pending=(async()=>{const c=await cfg.api('/api/mswitch/credentials');if(!c.username)throw Error('개인설정 → 엠스위치 연동에서 계정을 저장해 주세요.');return connect(c,keepSelection)})();try{return await pending}finally{pending=null}}
async function ready(force=false){if(force||!meta||owner!==cfg.user()?.id||meta.until<Date.now())await connectSaved(true);return meta}
async function mountLink(root,message=''){
 root.innerHTML='<p><b>브라우저 직접 연결 시험</b> · 앞선 테스트에서는 엠스위치 응답을 읽지 못했습니다. 별도 중계 서버는 사용하지 않습니다.</p><form class="msw-link-form"><label class="field">엠스위치 아이디<input name="username" autocomplete="username" required></label><label class="field">엠스위치 비밀번호<input name="password" type="password" autocomplete="current-password" required></label><button class="btn primary" type="submit">저장 · 연동하기</button> <button class="btn" type="button" data-msw-diag>비밀번호 없이 연결 진단</button> <button class="btn" type="button" data-msw-remove>저장 계정 삭제</button></form><p class="msw-result" role="status"></p>'+official()+logsHTML();bindLogs(root);const result=$('.msw-result',root);result.textContent=message;
 try{const c=await cfg.api('/api/mswitch/credentials');if(root.isConnected){$('[name=username]',root).value=c.username||'';$('[name=password]',root).value=c.password||'';if(!message)result.textContent=c.username?'이 사이트 사용자에게 계정이 저장되어 있습니다. 현재 탭에서 연동을 확인하세요.':'저장된 엠스위치 계정이 없습니다.'}}catch(e){result.textContent=e.message}
 $('.msw-link-form',root).onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;const b=$('[type=submit]',root);b.disabled=true;result.textContent='계정 저장 및 로그인 확인 중…';try{const c={username:$('[name=username]',root).value.trim(),password:$('[name=password]',root).value};await cfg.api('/api/mswitch/credentials',{method:'POST',body:c});const m=await connect(c);result.textContent=m.name+'님, 실제 엠스위치 로그인을 확인했습니다.';cfg.changed?.()}catch(err){result.textContent='계정 저장 후 연동 확인 실패: '+err.message;log('link.failed',{message:err.message})}finally{busy=false;b.disabled=false}};
 $('[data-msw-remove]',root).onclick=async()=>{if(busy)return;try{await cfg.api('/api/mswitch/credentials',{method:'POST',body:{remove:true}});reset();$('[name=username]',root).value='';$('[name=password]',root).value='';result.textContent='저장된 계정을 삭제했습니다.'}catch(e){result.textContent=e.message}};
 $('[data-msw-diag]',root).onclick=async()=>{if(busy)return;busy=true;result.textContent='진단 중…';const lines=[];try{for(const host of [LOGIN,REMOTE])try{await request(host,host===LOGIN?'/login.do':'/index.do',{credentials:false});lines.push(host+' · 응답 읽기 성공')}catch(e){lines.push(host+' · 응답 읽기 실패')}result.textContent=lines.join('\n')+'\n이 진단은 비밀번호 없이 실행하며, 로그인·문자 API 허용 여부를 확정하지 않습니다.'}finally{busy=false}};
}
async function mount(root){
 selected.clear();let page=1,lastKeyword='';root.innerHTML='<h1>문자보내기</h1><p>엠스위치 직접 연결이 성공한 경우에만 이 화면에서 발송할 수 있습니다.</p><button class="btn" data-msw-link>엠스위치 연동</button> '+official()+'<div class="msw-result" role="status"></div><div class="v2-sms-grid"><section class="section"><h2>받는 학부모</h2><form data-msw-search><input name="keyword" class="input" placeholder="학생명" required><button class="btn" type="submit">엠스위치 검색</button> <button type="button" class="btn" data-msw-local>사이트에 등록한 번호 조회</button></form><div data-msw-results></div><button class="btn" data-msw-more hidden>다음 검색 결과</button><p data-msw-count>학생 0명 · 학부모 0명</p></section><section class="section"><h2>문자 내용</h2><label class="field">종류<select name="mode"><option value="info">정보성</option><option value="ad">광고성 · (광고) 자동 추가</option></select></label><label class="field">발송 경로<select name="channels"><option value="har">HAR 기준 · SMS/앱/알림톡</option><option value="sms">SMS만</option></select></label><label class="field">발신번호<select name="sender"><option value="">연동 후 불러옵니다</option></select></label><textarea name="message" class="v2-message" maxlength="2000" placeholder="문자 내용을 입력하세요"></textarea><button class="btn primary" data-msw-send>발송</button><button class="btn" data-msw-unlock hidden>발송내역 확인 완료 · 새 발송 준비</button><p>엠스위치에 없는 수신자는 공식 사이트에서 직접 입력해 주세요. 필수 학생 식별값을 임의로 만들지 않습니다.</p></section></div>'+logsHTML();bindLogs(root);
 const result=$('.msw-result',root),renderSenders=()=>{if(meta)$('[name=sender]',root).innerHTML=meta.replies.map(p=>'<option>'+p+'</option>').join('')};renderSenders();result.textContent=meta?meta.name+'님 · 현재 탭에서 연결 확인됨':'현재 엠스위치 연결이 확인되지 않았습니다.';
 $('[data-msw-link]',root).onclick=()=>cfg.openLink();
 const display=rows=>{$('[data-msw-results]',root).innerHTML=rows.length?rows.map((x,i)=>`<label class="v2-recipient"><input type="checkbox" data-recipient="${i}" ${selected.has(x.key)?'checked':''}>${esc(x.name)} · 학부모 ${x.slot==='2'?2:1} · ${esc(x.phone)}</label>`).join(''):'검색 결과가 없습니다.';root.querySelectorAll('[data-recipient]').forEach(el=>el.onchange=()=>{const x=rows[+el.dataset.recipient];el.checked?selected.set(x.key,x):selected.delete(x.key);$('[data-msw-count]',root).textContent='학생 0명 · 학부모 '+selected.size+'명'})};
 async function search(next=false){if(busy)return;busy=true;try{const keyword=$('[name=keyword]',root).value.trim();if(!keyword)throw Error('학생명을 입력하세요.');if(!next||keyword!==lastKeyword){page=1;lastKeyword=keyword}const m=await ready();renderSenders();const d=await(await request(REMOTE,SMS+'selectMemList.json',{json:{s2id_autogen2:'',s2id_autogen2_search:'',strGrpCd:m.group,s2id_autogen3:'',s2id_autogen3_search:'',strCenterSeq:m.center,strStsCd:'10',strGradeCd:'',strKeyWordType:'01',strKeyWord:keyword,s2id_autogen1:'',s2id_autogen1_search:'',strClassSeq:'',page_num:'',page_size:'',sort_asc:'ASC',page}})).json();if(d.result!==true||!Array.isArray(d.data?.contents))throw Error('학생 검색 응답을 확인하지 못했습니다.');const rows=[];for(const raw of d.data.contents){if(String(raw.CENTER_SEQ)!==m.center||['CMEM_SEQ','MEM_SEQ','GRP_FIND_KEY','PRT_ORD'].some(k=>raw[k]==null||raw[k]===''))continue;for(const slot of ['','2']){const phone=digits(raw['PMPHONE'+slot]);if(phone.length>=9)rows.push({raw,slot,phone,key:raw.CMEM_SEQ+':'+slot,name:raw.CMEM_NAME||raw.MEM_NAME||''})}}display(rows);$('[data-msw-more]',root).hidden=d.data.contents.length===0;result.textContent=page+'페이지 · 학부모 '+rows.length+'명';log('search.complete',{page,parents:rows.length})}catch(e){result.textContent=e.message;log('search.failed',{message:e.message})}finally{busy=false}}
 $('[data-msw-search]',root).onsubmit=e=>{e.preventDefault();search()};$('[data-msw-more]',root).onclick=()=>{page++;search(true)};
 $('[data-msw-local]',root).onclick=async()=>{try{const d=await cfg.api('/api/mswitch/local-parents?q='+encodeURIComponent($('[name=keyword]',root).value.trim()));$('[data-msw-results]',root).innerHTML=d.rows.map(x=>`<p>${esc(x.name)} · ${esc(x.phone||'학부모 전화번호 미등록')}</p>`).join('')||'등록 학생이 없습니다.';result.textContent='사이트에 저장된 연락처입니다. 이 목록에는 엠스위치 발송용 식별값이 없어 발송 대상으로 추가하지 않습니다.'}catch(e){result.textContent=e.message}};
 $('[data-msw-send]',root).onclick=async()=>{if(busy||blockedSend)return;const button=$('[data-msw-send]',root),sendOwner=cfg.user()?.id,sendGeneration=generation;busy=true;button.disabled=true;let attempted=false;try{const m=await ready(true),content=$('[name=message]',root).value.trim();if(!content||!selected.size||selected.size>100)throw Error('문자 내용과 학부모 1~100명을 선택하세요.');const sender=$('[name=sender]',root).value;if(!m.replies.includes(sender))throw Error('발신번호를 선택하세요.');if(!confirm('선택한 학부모 '+selected.size+'명에게 실제 문자를 발송할까요?'))return;busy=true;button.disabled=true;
 const auth=(await post(SMS+'chkSmsAuth.json')).info||{};if(auth.SMS_USER_YN!=='Y'||auth.SMS_YN!=='Y')throw Error('엠스위치 문자 발송 권한이 없습니다.');const balance=await post(SMS+'chkBalance.json',{strCenterSeq:m.center,strSendCnt:String(selected.size),strInterLockSystemCode:'80'});if(String(balance.result_code)!=='0000')throw Error('발송 잔액 확인에 실패했습니다.');
 const rows=new Map();for(const x of selected.values()){const id=x.raw.CENTER_SEQ+':'+x.raw.CMEM_SEQ;if(!rows.has(id)){const n=rows.size;rows.set(id,{...x.raw,CAPP_YN:null,PAPP_YN:null,PAPP_YN2:null,rowKey:n,_attributes:{rowNum:n+1,checked:true,disabled:false,checkDisabled:false,className:{row:[],column:{}}}})}rows.get(id)['PAPP_YN'+x.slot]='Y'}
 const ad=$('[name=mode]',root).value==='ad',har=$('[name=channels]',root).value==='har',payload={KIND_CODE:'70',strIsStdYn:'0',strIsPrntYn:String(selected.size),BOOKING_DT:new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()),BOOKING_TIME:'0000',BOOKING_YN:'N',REPLY_TEL:sender,WEB_LINK:'',TEST_RECV_TEL:'',strIsTest:'N',strCenterSeq:m.center,MSTRGRIDROWS:'[]',SUBGRIDROWS:JSON.stringify([...rows.values()]),EXISTS_YN:'N',MSG_TEMPLATE_SEQ:'',ATTACH_FILE:'',ORI_ATTACH_FILE:'',ATTACH_FILE_TITLE:'',THUMBNAIL_FILE:'',IS_APP_PUSH:har?'Y':'N',IS_SMS:'Y',SERVICE_CODE:m.service,CONTENTS:ad&&!content.startsWith('(광고)')?'(광고)'+content:content,TITLE:'',IS_ALARM_TALK:har?'Y':'N',IS_AD:ad?'Y':'N',TALK_TEMPLATE_SEQ:'',KAKAO_PROFILE_CODE:'',TEMPLATE_BTN:''};
 if(sendOwner!==cfg.user()?.id||sendGeneration!==generation||owner!==sendOwner)throw Error('사이트 계정이 변경되어 발송을 중단했습니다.');if([...selected.values()].some(x=>String(x.raw.CENTER_SEQ)!==m.center))throw Error('문자 센터가 변경되었습니다. 학생을 다시 검색하세요.');attempted=true;blockedSend=true;sessionStorage.setItem('mirae-v2-send-pending','1');log('send.started',{parents:selected.size,students:0,fields:Object.keys(payload)});const d=await post(SMS+'alarmSend.json',payload),count=Number(d.strCount),fault=Number(d.strFault),accepted=String(d.result_code)==='0000'&&count===selected.size&&fault===0;log('send.result',{code:String(d.result_code||''),count:Number.isFinite(count)?count:null,faults:Number.isFinite(fault)?fault:null,accepted});result.textContent=accepted?'엠스위치가 '+count+'명 발송 요청을 접수했습니다. 실제 수신은 공식 사이트 발송내역에서 확인하세요.':'발송 결과가 불확실하거나 일부만 접수되었습니다. 재발송 전에 공식 사이트 발송내역을 확인하세요.';
 }catch(e){result.textContent=attempted?'발송 결과 확인 불가. 이미 접수됐을 수 있으므로 공식 사이트 발송내역을 먼저 확인하세요.':e.message;log('send.failed',{attempted,message:attempted?'발송 결과 확인 불가':e.message})}finally{busy=false;button.disabled=blockedSend;$('[data-msw-unlock]',root).hidden=!blockedSend}};
 if(sessionStorage.getItem('mirae-v2-send-pending')){blockedSend=true;$('[data-msw-send]',root).disabled=true;$('[data-msw-unlock]',root).hidden=false;result.textContent='이 탭에서 이전 발송을 시도했습니다. 공식 사이트 발송내역을 확인하고 새 발송을 준비하세요.'}
 $('[data-msw-unlock]',root).onclick=()=>{if(!confirm('공식 엠스위치 발송내역을 확인했고, 새로운 발송을 준비할까요?'))return;sessionStorage.removeItem('mirae-v2-send-pending');blockedSend=false;selected.clear();$('[data-msw-results]',root).replaceChildren();$('[data-msw-count]',root).textContent='학생 0명 · 학부모 0명';$('[data-msw-send]',root).disabled=false;$('[data-msw-unlock]',root).hidden=true;result.textContent='학생을 다시 검색해서 선택하세요.'};
}
function reset(){generation++;meta=null;owner='';selected.clear();lastAuto='';}
async function auto(){const u=cfg.user?.();if(!u||['parent','student'].includes(u.role)||lastAuto===u.id)return;lastAuto=u.id;try{const c=await cfg.api('/api/mswitch/credentials');if(!c.username)return;await connect(c)}catch(e){log('auto.failed',{message:e.message});cfg.openLink('엠스위치와의 자동 연동이 해지된 상태입니다. 다시 연동해주세요. '+e.message)}}
window.MiraeSMS={configure(c){cfg=c},mount,mountLink,auto,reset};
})();
