/* MSwitch operations run in the paired PC connector via Supabase HTTPS jobs. */
(()=>{'use strict';
const LOGIN='https://mswitch.t-ime.com',REMOTE='https://pmams.t-ime.com',SMS='/sms/SmsSendMngtN/';
let cfg={},meta=null,owner='',generation=0,selected=new Map(),busy=false,blockedSend=false,lastAuto='',pending=null;
const $=(s,r=document)=>r.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),digits=s=>String(s||'').replace(/\D/g,''),log=(event,d={})=>window.MiraeStore.log('mswitch.'+event,d);
function official(){return '<a class="btn" href="https://mswitch.t-ime.com/login.do" target="_blank" rel="noopener noreferrer">엠스위치 공식 사이트 열기</a>'}
function logsHTML(){return '<p>PC 처리 결과와 오류를 아래에 기록합니다. 오류 문의 시 로그를 복사해 주세요.</p><textarea class="v2-log msw-log" readonly aria-label="엠스위치 로그"></textarea><button class="btn" data-msw-copy>로그 복사</button> <button class="btn" data-msw-save-log>텍스트 파일 저장</button>'}
function bindLogs(root){const area=$('.msw-log',root);const paint=()=>{if(area.isConnected){area.value=window.MiraeStore.logs();area.scrollTop=area.scrollHeight}else window.removeEventListener('mirae-log',paint)};paint();window.addEventListener('mirae-log',paint);$('[data-msw-copy]',root).onclick=async()=>{try{await navigator.clipboard.writeText(area.value);cfg.toast('복사했습니다.')}catch{area.focus();area.select();cfg.toast('Ctrl+C로 복사하세요.')}};$('[data-msw-save-log]',root).onclick=()=>{const u=URL.createObjectURL(new Blob([area.value],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download='mirae-v2-mswitch-log.txt';a.click();setTimeout(()=>URL.revokeObjectURL(u),3000)}}
async function credentials(){const id=cfg.user()?.id,g=generation,c=await cfg.api('/api/mswitch/credentials');if(id!==cfg.user()?.id||g!==generation)throw Error('사이트 계정이 변경되어 작업을 중단했습니다.');if(!c.username||!c.password)throw Error('개인설정 → 엠스위치 연동에서 본인 계정을 저장해 주세요.');return {...c,_site_owner:id}}
async function connect(c,keepSelection=false){const g=generation,id=cfg.user()?.id;if(!id||c._site_owner!==id)throw Error('사이트 계정이 변경되어 작업을 중단했습니다.');if(!keepSelection||owner!==id)selected.clear();const d=await window.MiraePC.run('mswitch.login',c);if(g!==generation||id!==cfg.user()?.id)throw Error('로그인한 사이트 계정이 변경되었습니다.');meta={...d.meta,until:Date.now()+15*60000};owner=id;return meta}
async function connectSaved(keepSelection=false){if(pending)return pending;pending=(async()=>{const c=await credentials();return connect(c,keepSelection)})();try{return await pending}finally{pending=null}}
async function ready(force=false){if(force||!meta||owner!==cfg.user()?.id||meta.until<Date.now())await connectSaved(true);return meta}
async function mountLink(root,message=''){
 root.innerHTML='<p><b>내 엠스위치 계정 연결</b> · 이 PC의 프로그램이 로그인과 문자 발송을 처리합니다. 사용자마다 자신의 계정을 사용합니다.</p><form class="msw-link-form"><label class="field">엠스위치 아이디<input name="username" autocomplete="username" required></label><label class="field">엠스위치 비밀번호<input name="password" type="password" autocomplete="current-password" required></label><button class="btn primary" type="submit">저장 · 연동하기</button> <button class="btn" type="button" data-msw-diag>비밀번호 없이 연결 진단</button> <button class="btn" type="button" data-msw-remove>저장 계정 삭제</button></form><p class="msw-result" role="status"></p>'+official()+logsHTML();bindLogs(root);const result=$('.msw-result',root);result.textContent=message;
 try{const c=await cfg.api('/api/mswitch/credentials');if(root.isConnected){$('[name=username]',root).value=c.username||'';$('[name=password]',root).value=c.password||'';if(!message)result.textContent=c.username?'이 사이트 사용자에게 계정이 저장되어 있습니다. 현재 탭에서 연동을 확인하세요.':'저장된 엠스위치 계정이 없습니다.'}}catch(e){result.textContent=e.message}
 $('.msw-link-form',root).onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;const b=$('[type=submit]',root);b.disabled=true;result.textContent='계정 저장 및 로그인 확인 중…';try{const c={username:$('[name=username]',root).value.trim(),password:$('[name=password]',root).value,_site_owner:cfg.user()?.id};await cfg.api('/api/mswitch/credentials',{method:'POST',body:c});const m=await connect(c);result.textContent=m.name+'님, 실제 엠스위치 로그인을 확인했습니다.';cfg.changed?.()}catch(err){result.textContent='계정 저장 후 연동 확인 실패: '+err.message;log('link.failed',{message:err.message})}finally{busy=false;b.disabled=false}};
 $('[data-msw-remove]',root).onclick=async()=>{if(busy)return;try{await cfg.api('/api/mswitch/credentials',{method:'POST',body:{remove:true}});reset();$('[name=username]',root).value='';$('[name=password]',root).value='';result.textContent='저장된 계정을 삭제했습니다.'}catch(e){result.textContent=e.message}};
 $('[data-msw-diag]',root).onclick=async()=>{if(busy)return;busy=true;result.textContent='PC에서 연결 진단 중…';try{const d=await window.MiraePC.run('mswitch.diagnostics');result.textContent=d.results.map(x=>x.host+' · '+(x.ok?'연결 성공':'연결 실패')).join('\n')}catch(e){result.textContent=e.message}finally{busy=false}};
}
async function mount(root){
 selected.clear();let page=1,lastKeyword='';root.innerHTML='<h1>문자보내기</h1><p>PC 연결과 엠스위치 로그인이 확인되면 학부모에게 문자를 보낼 수 있습니다.</p><button class="btn" data-msw-link>엠스위치 연동</button> '+official()+'<div class="msw-result" role="status"></div><div class="v2-sms-grid"><section class="section"><h2>받는 학부모</h2><form data-msw-search><input name="keyword" class="input" placeholder="학생명" required><button class="btn" type="submit">엠스위치 검색</button> <button type="button" class="btn" data-msw-local>사이트에 등록한 번호 조회</button></form><div data-msw-results></div><button class="btn" data-msw-more hidden>다음 검색 결과</button><p data-msw-count>학생 0명 · 학부모 0명</p></section><section class="section"><h2>문자 내용</h2><label class="field">종류<select name="mode"><option value="info">정보성</option><option value="ad">광고성 · (광고) 자동 추가</option></select></label><label class="field">발송 경로<select name="channels"><option value="har">HAR 기준 · SMS/앱/알림톡</option><option value="sms">SMS만</option></select></label><label class="field">발신번호<select name="sender"><option value="">연동 후 불러옵니다</option></select></label><textarea name="message" class="v2-message" maxlength="2000" placeholder="문자 내용을 입력하세요"></textarea><button class="btn primary" data-msw-send>발송</button><button class="btn" data-msw-unlock hidden>발송내역 확인 완료 · 새 발송 준비</button><p>엠스위치에 없는 수신자는 공식 사이트에서 직접 입력해 주세요. 필수 학생 식별값을 임의로 만들지 않습니다.</p></section></div>'+logsHTML();bindLogs(root);
 const result=$('.msw-result',root),renderSenders=()=>{if(meta)$('[name=sender]',root).innerHTML=meta.replies.map(p=>'<option>'+p+'</option>').join('')};renderSenders();result.textContent=meta?meta.name+'님 · PC에서 로그인 확인됨':'현재 엠스위치 연결이 확인되지 않았습니다.';
 $('[data-msw-link]',root).onclick=()=>cfg.openLink();
 const display=rows=>{$('[data-msw-results]',root).innerHTML=rows.length?rows.map((x,i)=>`<label class="v2-recipient"><input type="checkbox" data-recipient="${i}" ${selected.has(x.key)?'checked':''}>${esc(x.name)} · 학부모 ${x.slot==='2'?2:1} · ${esc(x.phone)}</label>`).join(''):'검색 결과가 없습니다.';root.querySelectorAll('[data-recipient]').forEach(el=>el.onchange=()=>{const x=rows[+el.dataset.recipient];el.checked?selected.set(x.key,x):selected.delete(x.key);$('[data-msw-count]',root).textContent='학생 0명 · 학부모 '+selected.size+'명'})};
 async function search(next=false){if(busy)return;busy=true;try{const keyword=$('[name=keyword]',root).value.trim();if(!keyword)throw Error('학생명을 입력하세요.');if(!next||keyword!==lastKeyword){page=1;lastKeyword=keyword}const id=cfg.user()?.id,d=await window.MiraePC.run('mswitch.search',{...await credentials(),keyword,page});if(id!==cfg.user()?.id)return;meta={...d.meta,until:Date.now()+15*60000};owner=id;renderSenders();display(d.rows);$('[data-msw-more]',root).hidden=!d.more;result.textContent=page+'페이지 · 학부모 '+d.rows.length+'명'}catch(e){result.textContent=e.message;log('search.failed',{message:e.message})}finally{busy=false}}
 $('[data-msw-search]',root).onsubmit=e=>{e.preventDefault();search()};$('[data-msw-more]',root).onclick=()=>{page++;search(true)};
 $('[data-msw-local]',root).onclick=async()=>{try{const d=await cfg.api('/api/mswitch/local-parents?q='+encodeURIComponent($('[name=keyword]',root).value.trim()));$('[data-msw-results]',root).innerHTML=d.rows.map(x=>`<p>${esc(x.name)} · ${esc(x.phone||'학부모 전화번호 미등록')}</p>`).join('')||'등록 학생이 없습니다.';result.textContent='사이트에 저장된 연락처입니다. 이 목록에는 엠스위치 발송용 식별값이 없어 발송 대상으로 추가하지 않습니다.'}catch(e){result.textContent=e.message}};
 $('[data-msw-send]',root).onclick=async()=>{if(busy||blockedSend)return;const button=$('[data-msw-send]',root),sendOwner=cfg.user()?.id,sendGeneration=generation;busy=true;button.disabled=true;let attempted=false;try{const m=await ready(),content=$('[name=message]',root).value.trim();if(!content||!selected.size||selected.size>100)throw Error('문자 내용과 학부모 1~100명을 선택하세요.');const sender=$('[name=sender]',root).value;if(!m.replies.includes(sender))throw Error('발신번호를 선택하세요.');if(!confirm('선택한 학부모 '+selected.size+'명에게 실제 문자를 발송할까요?'))return;busy=true;button.disabled=true;
 if(sendOwner!==cfg.user()?.id||sendGeneration!==generation||owner!==sendOwner)throw Error('사이트 계정이 변경되어 발송을 중단했습니다.');attempted=true;blockedSend=true;sessionStorage.setItem('mirae-v2-send-pending','1');log('send.started',{parents:selected.size,students:0});const d=await window.MiraePC.run('mswitch.send',{...await credentials(),selected:[...selected.values()],sender,message:content,mode:$('[name=mode]',root).value,channels:$('[name=channels]',root).value});result.textContent=d.message;
 }catch(e){result.textContent=attempted?'발송 결과 확인 불가. 이미 접수됐을 수 있으므로 공식 사이트 발송내역을 먼저 확인하세요.':e.message;log('send.failed',{attempted,message:attempted?'발송 결과 확인 불가':e.message})}finally{busy=false;button.disabled=blockedSend;$('[data-msw-unlock]',root).hidden=!blockedSend}};
 if(sessionStorage.getItem('mirae-v2-send-pending')){blockedSend=true;$('[data-msw-send]',root).disabled=true;$('[data-msw-unlock]',root).hidden=false;result.textContent='이 탭에서 이전 발송을 시도했습니다. 공식 사이트 발송내역을 확인하고 새 발송을 준비하세요.'}
 $('[data-msw-unlock]',root).onclick=()=>{if(!confirm('공식 엠스위치 발송내역을 확인했고, 새로운 발송을 준비할까요?'))return;sessionStorage.removeItem('mirae-v2-send-pending');blockedSend=false;selected.clear();$('[data-msw-results]',root).replaceChildren();$('[data-msw-count]',root).textContent='학생 0명 · 학부모 0명';$('[data-msw-send]',root).disabled=false;$('[data-msw-unlock]',root).hidden=true;result.textContent='학생을 다시 검색해서 선택하세요.'};
}
function reset(){generation++;meta=null;owner='';selected.clear();lastAuto='';}
async function auto(){const u=cfg.user?.();if(!u||['parent','student'].includes(u.role)||lastAuto===u.id||window.MiraePC?.state!=='connected')return;lastAuto=u.id;try{const g=generation,c=await cfg.api('/api/mswitch/credentials');if(g!==generation||u.id!==cfg.user()?.id||!c.username)return;await connect({...c,_site_owner:u.id})}catch(e){if(u.id!==cfg.user()?.id)return;log('auto.failed',{message:e.message});cfg.openLink('엠스위치와의 자동 연동이 해지된 상태입니다. 다시 연동해주세요. '+e.message)}}
window.MiraeSMS={configure(c){cfg=c},mount,mountLink,auto,reset};
})();
