(function(root){'use strict';
const WEIGHTS={lessons:30,comments:25,attendance:20,scores:15,plans:10},round=n=>Math.round(n*10)/10;
function query(D,filters={},now=new Date()){
 const A=root.MiraeAttendanceCore,today=A.korea(now).date,start=filters.start||'0000',end=(filters.end||today)>today?today:filters.end||today;
 if(filters.start&&!A.validDay(filters.start)||filters.end&&!A.validDay(filters.end)||start>end)throw Error('조회 기간을 확인하세요.');
 const classes=D.classes.filter(c=>!filters.class_id||c.id===filters.class_id),within=d=>d>=start&&d<=end,active=(c,date)=>[...new Set(D.enrollments.filter(e=>e.class_id===c.id&&e.status!=='inactive'&&e.joined_on<=date&&(!e.left_on||e.left_on>=date)).map(e=>e.student_id))];
 function classStats(c){const lessons=D.lessons.filter(l=>l.class_id===c.id&&within(l.lesson_date)),exams=D.exams.filter(e=>e.class_id===c.id&&within(e.exam_date)),dates=new Set(lessons.map(l=>l.lesson_date));let from=c.start_date>start?c.start_date:start,to=c.end_date<end?c.end_date:end;
  if(A.validDay(from)&&A.validDay(to)&&c.weekdays?.length){if((new Date(to)-new Date(from))/86400000>3660)throw Error('조회 기간을 줄여 주세요.');for(let d=new Date(from+'T12:00:00Z'),last=new Date(to+'T12:00:00Z');d<=last;d.setUTCDate(d.getUTCDate()+1))if(c.weekdays.includes(d.getUTCDay()))dates.add(d.toISOString().slice(0,10))}
  const feedback=D.feedback.filter(f=>lessons.some(l=>l.id===f.lesson_id)),comments=feedback.filter(f=>String(f.comment||'').trim()),scoreRows=D.scores.filter(s=>exams.some(e=>e.id===s.exam_id)),scores=scoreRows.filter(s=>s.score!==null&&s.score!==undefined&&s.score!==''&&!s.absent),attendance=(D.attendance||[]).filter(r=>r.class_id===c.id&&within(r.date));for(const r of attendance)dates.add(r.date);
  const lessonExpected=dates.size,commentExpected=lessons.reduce((n,l)=>n+active(c,l.lesson_date).length,0),scoreExpected=exams.reduce((n,e)=>n+active(c,e.exam_date).length,0),attExpected=[...dates].reduce((n,d)=>n+active(c,d).length,0),planRows=c.syllabus||[],planDone=[...dates].filter(date=>planRows.some(r=>r.date===date&&String(r.content||'').trim())).length;
  return{lessons:lessons.length,exams:exams.length,comments:comments.length,scores:scores.length,attendance:attendance.length,plans:planDone,expected:{lessons:lessonExpected,comments:commentExpected,attendance:attExpected,scores:scoreExpected,plans:dates.size},done:{lessons:new Set(lessons.map(l=>l.lesson_date)).size,comments:comments.length,attendance:new Set(attendance.map(r=>r.date+'|'+r.student_id)).size,scores:scores.length+scoreRows.filter(s=>s.absent).length,plans:planDone},last:[...lessons,...exams,...feedback,...scoreRows,...attendance].map(r=>r.updated_at||r.created_at||r.arrival_at||'').sort().at(-1)||''}}
 const stats=new Map(classes.map(c=>[c.id,classStats(c)])),rows=D.accounts.filter(t=>['teacher','admin'].includes(t.role)&&t.status==='active').map(t=>{const own=classes.filter(c=>[c.teacher_id,c.assistant_teacher_id].includes(t.id)),parts=own.map(c=>stats.get(c.id)),r={id:t.id,name:t.name,subject:root.MiraeSubject.label(t),classes:own.length,class_names:own.map(c=>c.name),last:parts.map(s=>s.last).sort().at(-1)||'',expected:{},rates:{},shares:{}};
  for(const k of ['lessons','exams','comments','scores','attendance','plans'])r[k]=parts.reduce((n,s)=>n+s[k],0);
  let weighted=0,totalWeight=0;for(const [k,w]of Object.entries(WEIGHTS)){r.expected[k]=parts.reduce((n,s)=>n+s.expected[k],0);r.rates[k]=r.expected[k]?Math.min(100,parts.reduce((n,s)=>n+s.done[k],0)/r.expected[k]*100):null;if(r.rates[k]!==null){weighted+=r.rates[k]*w;totalWeight+=w}}r.score=totalWeight?round(weighted/totalWeight):null;return r}).filter(r=>r.classes>0);
 const totals=Object.fromEntries(['lessons','exams','comments','scores','attendance','plans'].map(k=>[k,rows.reduce((n,r)=>n+r[k],0)]));for(const r of rows)for(const k of Object.keys(totals))r.shares[k]=totals[k]?round(r[k]/totals[k]*100):0;
 const eligible=rows.filter(r=>r.score!==null),watch=[...eligible].sort((a,b)=>a.score-b.score||a.name.localeCompare(b.name,'ko')).slice(0,3).map(r=>r.id);
 return{rows,totals,watch,weights:WEIGHTS,start,end,average:eligible.length?round(eligible.reduce((n,r)=>n+r.score,0)/eligible.length):null};
}
const api={VERSION:'3.3.0',query,WEIGHTS};root.MiraeOversight=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
