/* Outbound HTTPS relay. No localhost requests, protocol launch, or browser policy changes. */
(()=>{'use strict';
const VERSION='261004',PROTOCOL=1,MIN_VERSION='2.7.0',PAIR='mirae-pc-pair-v21';
const mobile=/Android|iPhone|iPad|iPod|Mobile/i.test(navigator.userAgent||'')||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1)||(navigator.maxTouchPoints>0&&/Linux|Android|iPad|iPhone/.test(navigator.platform||'')&&matchMedia('(pointer:coarse)').matches);document.documentElement.classList.toggle('mobile-device',mobile);
let cfg={},pair=null,state='idle',detail='',seenVersion='',timer=null,generation=0,connecting=null,loginOwner='',boundOwner='',binding=null,limited=false;
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const log=(event,d={})=>window.MiraeStore.log('pc.'+event,d),sleep=ms=>new Promise(r=>setTimeout(r,ms));
function compare(a,b){const x=String(a).split('.').map(Number),y=String(b).split('.').map(Number);if(x.length!==3||y.length!==3||[...x,...y].some(n=>!Number.isInteger(n)||n<0))return-1;for(let i=0;i<3;i++){if(x[i]!==y[i])return x[i]>y[i]?1:-1}return 0}
function siteURL(){return new URL('.',location.href).href}
function pairing(){const c=window.MIRAE_CONFIG||{},project=c.SUPABASE_URL;try{pair=JSON.parse(localStorage.getItem(PAIR)||'null')}catch{}if(!pair||pair.project!==project||!/^[a-f0-9]{64}$/.test(pair.key||'')){const b=new Uint8Array(32);crypto.getRandomValues(b);pair={id:crypto.randomUUID(),key:[...b].map(x=>x.toString(16).padStart(2,'0')).join(''),project};localStorage.setItem(PAIR,JSON.stringify(pair))}return pair}
async function mobileRPC(action,data={},timeout=8000){
 const c=window.MIRAE_CONFIG||{},key=c.SUPABASE_KEY,headers={apikey:key,'Content-Type':'application/json'};if(key?.startsWith('eyJ'))headers.Authorization='Bearer '+key;
 let r;try{r=await fetch(c.SUPABASE_URL.replace(/\/$/,'')+'/rest/v1/rpc/mirae_pc_mobile',{method:'POST',headers,credentials:'omit',signal:AbortSignal.timeout(timeout),body:JSON.stringify({p_session:cfg.token?.()||'',p_action:action,p_data:{...data,site_url:siteURL()}})})}catch(e){throw Error('내 PC 연결 응답을 받지 못했습니다. 인터넷 연결을 확인해 주세요.')}
 const d=await r.json();if(!r.ok){const message=String(d.message||'');log('mobile.relay_failed',{action,http_status:r.status,code:String(d.code||'')});const known={LOGIN_REQUIRED:'사이트에 다시 로그인해 주세요.',MOBILE_PC_NOT_CONFIGURED:'본인의 PC에서 같은 사이트 계정으로 한 번 로그인해 주세요. 연결된 PC가 자동 등록됩니다.',PC_OFFLINE:'내 PC가 꺼져 있거나 연결되어 있지 않습니다. 출결은 저장되고 문자는 대기합니다.',PC_BUSY:'내 PC가 다른 요청을 처리 중입니다. 잠시 후 대기 알림 보내기를 눌러 주세요.',PC_UPDATE_REQUIRED:'내 PC의 연결 프로그램을 업데이트해야 합니다.',MSW_LINK_REQUIRED:'개인설정에서 본인의 엠스위치 계정을 먼저 연동하세요.',MSW_ACCOUNT_CHANGED:'엠스위치 계정이 변경되었습니다. 학부모 명단을 다시 확인하세요.'};const error=Error(['PGRST202','42P01','42883'].includes(d.code)?'연결 설정 업데이트가 필요합니다. 관리자에게 문의해 주세요.':Object.entries(known).find(([k])=>message.includes(k))?.[1]||'내 PC 연결 설정을 확인해 주세요.');if(message.includes('JOB_NOT_FOUND'))error.code='JOB_NOT_FOUND';throw error}if(['check','bind'].includes(action)&&d.user_relay_v1!==true)throw Error('연결 설정 업데이트가 필요합니다. 관리자에게 문의해 주세요.');return d;
}
async function bindMobile(){
 const u=cfg.user?.(),g=generation;if(mobile||!u||!['admin','teacher'].includes(u.role)||boundOwner===u.id)return;if(binding)return binding;
 const p=pairing();binding=(async()=>{await mobileRPC('bind',{device_id:p.id,device_key:p.key});if(g===generation&&cfg.user?.()?.id===u.id){boundOwner=u.id;log('mobile.personal_pc_registered',{automatic:true,owner_id:u.id})}})();try{return await binding}finally{if(g===generation)binding=null}
}
async function connectMobile(){
 if(connecting)return connecting;const g=generation;connecting=(async()=>{closeDialog();change('connecting');try{const d=await mobileRPC('check');if(g!==generation)return false;seenVersion=String(d.version||'');if(d.online&&d.protocol===PROTOCOL&&compare(d.version,MIN_VERSION)>=0){change('connected');log('mobile.connect.complete',{pc_version:d.version});cfg.connected?.();return true}change(d.online?'update':'offline',d.online?'내 PC 프로그램 업데이트가 필요합니다.':d.configured?'내 컴퓨터의 응답이 없습니다. 컴퓨터가 꺼져 있거나 인터넷 연결이 끊겨 있을 수 있습니다.':'본인의 PC에서 같은 사이트 계정으로 한 번 로그인해 주세요. 연결된 PC가 자동 등록됩니다.');return false}catch(e){if(g===generation){change('offline',e.message);log('mobile.connect.failed',{message:e.message})}return false}})();try{return await connecting}finally{if(g===generation)connecting=null;startTimer()}
}
async function mountSettings(node){
 if(!node||!cfg.user?.())return;node.innerHTML='<h2>내 PC · 모바일 문자 연결</h2><p>본인의 PC에서 사이트에 로그인하면 연결된 PC가 자동 등록됩니다. 휴대폰에서도 같은 계정으로 로그인하면 그 PC에만 문자 요청을 보냅니다. PC 선택이나 별도 허용 절차는 없습니다.</p><p>문자를 보낼 때는 내 PC와 연결기가 켜져 있어야 합니다. PC의 사이트 창은 닫아도 됩니다. 여러 PC를 사용하면 최근에 로그인해 연결한 PC를 사용합니다.</p><p data-mobile-info role="status">연결 확인 중…</p>';
 try{const d=await mobileRPC('check');if(node.isConnected)node.querySelector('[data-mobile-info]').textContent=d.online?'내 PC 연결됨 · '+(d.name||'PC')+' · 버전 '+d.version:d.configured?'내 PC가 현재 연결되어 있지 않습니다. 다른 사람의 PC로 요청을 보내지 않습니다.':'본인의 PC에서 같은 사이트 계정으로 한 번 로그인해 주세요.'}catch(e){if(node.isConnected)node.querySelector('[data-mobile-info]').textContent=e.message}
}
async function rpc(action,data={},timeout=8000){
 if(mobile)return mobileRPC(action,data,Math.max(100,timeout));
 const c=window.MIRAE_CONFIG||{},p=pairing(),key=c.SUPABASE_KEY,headers={apikey:key,'Content-Type':'application/json'};if(key?.startsWith('eyJ'))headers.Authorization='Bearer '+key;
 let r;try{r=await fetch(c.SUPABASE_URL.replace(/\/$/,'')+'/rest/v1/rpc/mirae_pc_bridge',{method:'POST',headers,credentials:'omit',signal:AbortSignal.timeout(Math.max(100,timeout)),body:JSON.stringify({p_device:p.id,p_key:p.key,p_action:action,p_data:data})})}catch(e){throw Error(e.name==='TimeoutError'?'PC 연결 응답 시간이 초과되었습니다.':'PC 연결 응답을 받지 못했습니다.')}
 const d=await r.json();if(!r.ok){const m=String(d.message||'');log('relay.failed',{action,http_status:r.status,code:String(d.code||'')});if(['PGRST202','42P01','42883'].includes(d.code))throw Error('연결 설정 업데이트가 필요합니다. 관리자에게 문의해 주세요.');if(m.includes('PC_OFFLINE'))throw Error('PC 연결이 끊겼습니다. 연결을 다시 확인해 주세요.');if(m.includes('PC_BUSY'))throw Error('PC에서 다른 작업을 처리 중입니다. 잠시 후 다시 시도하세요.');if(m.includes('PC_UPDATE_REQUIRED'))throw Error('PC 프로그램 업데이트가 필요합니다.');const error=Error('PC 연결 설정을 확인해 주세요.');if(m.includes('JOB_NOT_FOUND'))error.code='JOB_NOT_FOUND';throw error}return d;
}
function paint(){const b=$('#pc-header-button');if(!b)return;b.classList.add('pc-indicator');b.dataset.state=state;const labels=mobile?{connected:'내 PC 연결됨',connecting:'문자 연결 확인',update:'내 PC 업데이트',offline:'PC 연결 없음',limited:'PC 연결 없음',idle:'문자 연결 확인'}:{connected:'PC연동 활성화',connecting:'PC 연결 확인 중',update:'PC 업데이트 필요',offline:'PC 미연결',limited:'제한 모드',idle:'PC 연결 확인'};b.innerHTML='<span class="pc-light" aria-hidden="true"></span><span>'+labels[state]+'</span>';b.title=(seenVersion?'PC 버전 '+seenVersion+' · ':'')+(detail||'PC 연결 상태 보기');}
function change(next,message=''){state=next;detail=message;paint();mobileNotice();window.dispatchEvent(new CustomEvent('mirae-pc-state',{detail:{state,version:seenVersion}}))}
function mobileNotice(){const u=cfg.user?.(),host=document.querySelector('.workspace');let box=document.querySelector('#mobile-pc-notice');if(!mobile||!host||!u||!['admin','teacher'].includes(u.role)||!cfg.enabled?.()||!['offline','update','limited'].includes(state)){box?.remove();return}if(!box){box=document.createElement('aside');box.id='mobile-pc-notice';box.className='mobile-pc-notice';box.setAttribute('role','status');host.querySelector('.topbar')?.after(box)}box.innerHTML='<strong>선생님의 컴퓨터에 연결할 수 없습니다.</strong><span>컴퓨터가 꺼져 있거나 인터넷 연결이 끊겨 있을 수 있습니다. 지금은 저장된 정보로 이용합니다. 출결 저장·앱푸시는 가능하며, 새 학생 조회와 문자·카톡 발송은 컴퓨터가 연결되면 진행할 수 있습니다.</span><button type="button" class="btn sm">다시 확인</button>';box.querySelector('button').onclick=()=>connectMobile();}
function closeDialog(){const el=$('#pc-dialog');el?.remove();if(!$('.modal-overlay'))document.body.classList.remove('modal-open')}
function dialog(){if(!cfg.user?.())return;if(mobile){closeDialog();cfg.toast?.(detail||'내 PC 연결을 확인해 주세요.');return;}closeDialog();const el=document.createElement('div');el.id='pc-dialog';el.className='modal-overlay pc-dialog';el.innerHTML=`<section class="modal" role="dialog" aria-modal="true" aria-labelledby="pc-dialog-title"><div class="pc-dialog-content"><span class="pc-dialog-kicker">PC 연결</span><h2 id="pc-dialog-title">${state==='update'?'프로그램 업데이트가 필요합니다.':'PC에 연결되지 않았습니다.'}</h2><p>${esc(detail||'약 10초 동안 응답을 기다렸지만 이 브라우저에 연결된 프로그램을 찾지 못했습니다.')}</p><p class="muted">타임넷 조회와 엠스위치 발송에는 PC 프로그램이 필요합니다. 학생·수업·성적 관리는 제한 모드에서도 이용할 수 있습니다.</p><div class="pc-dialog-actions"><button class="btn primary" data-pc-retry>연결 재시도</button><button class="btn" data-pc-install>${state==='update'?'새 버전 설치':'프로그램 설치'}</button><button class="btn ghost" data-pc-limited>설치하지 않고 제한 모드로 실행</button></div><p data-pc-install-status role="status"></p><small>필요 버전 ${MIN_VERSION}${seenVersion?' · 확인한 버전 '+esc(seenVersion):''}</small></div></section>`;document.body.append(el);document.body.classList.add('modal-open');el.querySelector('[data-pc-retry]').onclick=()=>connect(true);el.querySelector('[data-pc-install]').onclick=()=>install(el);el.querySelector('[data-pc-limited]').onclick=()=>{limited=true;change('limited');closeDialog()};el.querySelector('button').focus();el.addEventListener('keydown',e=>{if(e.key==='Escape'){limited=true;change('limited');closeDialog()}if(e.key==='Tab'){const buttons=[...el.querySelectorAll('button:not(:disabled)')];if(e.shiftKey&&document.activeElement===buttons[0]){buttons.at(-1).focus();e.preventDefault()}else if(!e.shiftKey&&document.activeElement===buttons.at(-1)){buttons[0].focus();e.preventDefault()}}})}
async function connect(show=true){
 if(mobile)return connectMobile();
 if(connecting)return connecting;const g=generation;connecting=(async()=>{
  closeDialog();limited=false;seenVersion='';change('connecting');log('connect.start',{wait_seconds:10,required_version:MIN_VERSION});const end=Date.now()+10000,nonce=crypto.randomUUID();let last='',ok=false;
  try{await rpc('register',{site_url:siteURL()},Math.min(3000,end-Date.now()));await rpc('check',{nonce},Math.min(3000,end-Date.now()));while(Date.now()<end&&g===generation){const d=await rpc('check',{},Math.min(1800,end-Date.now()));seenVersion=String(d.version||'');if(d.online&&d.nonce===nonce){if(d.protocol!==PROTOCOL||compare(d.version,MIN_VERSION)<0){change('update','사이트와 PC 프로그램의 버전이 맞지 않습니다. 프로그램은 자동 업데이트를 확인합니다. 설치 버튼으로 즉시 갱신할 수도 있습니다.');log('version.mismatch',{actual:d.version,required:MIN_VERSION});break}ok=true;change('connected');log('connect.complete',{pc_version:d.version,required_version:MIN_VERSION});closeDialog();break}await sleep(Math.min(750,Math.max(0,end-Date.now())))}}catch(e){last=e.message;const left=end-Date.now();if(left>0)await sleep(left)}
  if(g!==generation)return false;if(!ok&&state!=='update'){change('offline',last||'약 10초 동안 이 PC의 응답을 확인하지 못했습니다. 프로그램을 설치했거나 켜 둔 상태라면 연결을 다시 시도해 주세요.');log('connect.failed',{message:detail})}if(!ok&&show)dialog();if(ok){try{await bindMobile()}catch(e){log('mobile.pc_registration_failed',{message:e.message})}if(g===generation)cfg.connected?.();}return ok
 })();try{return await connecting}finally{if(g===generation)connecting=null;startTimer()}
}
function startTimer(){if(timer||!cfg.user?.())return;timer=setInterval(async()=>{if(connecting||!cfg.user?.())return;const g=generation;try{const d=await rpc('check');if(g!==generation)return;seenVersion=String(d.version||'');if(d.online&&d.protocol===PROTOCOL&&compare(d.version,MIN_VERSION)>=0){if(state!=='connected'){change('connected');closeDialog();if(!mobile)try{await bindMobile()}catch(e){log('mobile.pc_registration_failed',{message:e.message})}if(g===generation)cfg.connected?.()}else if(!mobile&&boundOwner!==cfg.user?.()?.id){try{await bindMobile()}catch(e){log('mobile.pc_registration_failed',{message:e.message})}}}else if(state==='connected'){change(d.online?'update':'offline',d.online?'프로그램 업데이트가 필요합니다.':'PC 프로그램의 응답이 끊겼습니다.');log('disconnected');if(!limited&&!mobile)dialog()}}catch(e){if(g===generation&&state==='connected'){change('offline',e.message);if(!limited&&!mobile)dialog()}}},20000)}
async function auto(){const u=cfg.user?.();if(!u||cfg.enabled?.()===false||!['admin','teacher'].includes(u.role)||loginOwner===u.id)return;loginOwner=u.id;return connect(true)}
async function install(el=$('#pc-dialog')){
 if(state==='connected'&&compare(seenVersion,MIN_VERSION)>=0){cfg.toast?.('이미 호환되는 PC 프로그램이 연결되어 있습니다. 다시 설치할 필요가 없습니다.');return}
 if(mobile){cfg.toast?.('휴대폰에는 PC 프로그램을 설치하지 않습니다.');return}
 const status=el?.querySelector('[data-pc-install-status]'),b=el?.querySelector('[data-pc-install]');if(b)b.disabled=true;try{
  if(location.protocol!=='https:')throw Error('GitHub Pages 등 HTTPS로 배포한 사이트에서 설치 파일을 내려받아 주세요.');if(status)status.textContent='이 PC용 설치 파일을 준비하고 있습니다…';const p=pairing();await rpc('register',{site_url:siteURL()});
  const res=await fetch(new URL('downloads/MiraeConnectorSetup.exe',siteURL()),{cache:'no-store',credentials:'omit'});if(!res.ok)throw Error('설치 파일을 찾지 못했습니다. web/downloads 폴더도 사이트에 올려 주세요.');const raw=new Uint8Array(await res.arrayBuffer());if(raw.length<1000000||raw[0]!==77||raw[1]!==90)throw Error('설치 파일이 올바르지 않습니다. downloads 폴더를 다시 올려 주세요.');
  const c=window.MIRAE_CONFIG||{},data=new TextEncoder().encode(JSON.stringify({api_url:c.SUPABASE_URL.replace(/\/$/,''),public_key:c.SUPABASE_KEY,site_url:siteURL(),token:p.key,device_id:p.id,protocol:PROTOCOL})),length=new Uint8Array(4);new DataView(length.buffer).setUint32(0,data.length,true);
  const blob=new Blob([raw,data,length,new TextEncoder().encode('MIRAE-PC-CONFIG-2.1')],{type:'application/octet-stream'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='미래탐구_PC연결_설치.exe';a.click();setTimeout(()=>URL.revokeObjectURL(u),60000);log('installer.downloaded',{version:MIN_VERSION});if(status)status.textContent='내려받은 설치 파일을 한 번 실행해 주세요. 설치가 끝나면 이 창에서 자동으로 연결을 확인합니다.';startTimer();
 }catch(e){if(status)status.textContent=e.message;else cfg.toast?.(e.message,true);log('installer.failed',{message:e.message})}finally{if(b)b.disabled=false}
}
async function run(kind,payload={},options={}){
 const timeout=typeof options==='number'?options:1200000,onProgress=typeof options==='object'?options.onProgress:null;
 if(kind.startsWith('mswitch.contact.')&&!cfg.can?.('mswitch_contact')||kind.startsWith('mswitch.')&&!kind.startsWith('mswitch.contact.')&&!cfg.can?.('sms')&&!cfg.can?.('attendance_notify')&&!(cfg.can?.('mswitch_contact')&&['mswitch.login','mswitch.roster','mswitch.search','mswitch.diagnostics'].includes(kind))||kind==='mswitch.attendance'&&!cfg.can?.('attendance_notify')||kind.startsWith('timenet.')&&!cfg.can?.('timenet'))throw Error('이 기능을 사용할 권한이 없습니다.');if(mobile&&!kind.startsWith('mswitch.'))throw Error('새 타임넷 명단은 컴퓨터에서 불러와 주세요. 휴대폰에서도 이미 저장된 명단으로 학생을 등록할 수 있습니다.');
 const u=cfg.user?.(),g=generation;if(!u||['parent','student'].includes(u.role))throw Error('강사 또는 관리자 로그인이 필요합니다.');if(state!=='connected'){if(!await connect(!mobile))throw Error(mobile?(detail||'내 PC 연결을 확인해 주세요.'):'PC 연결을 먼저 완료해 주세요.')}
 if(g!==generation||cfg.user?.()?.id!==u.id||payload._site_owner&&payload._site_owner!==u.id)throw Error('사이트 계정이 변경되어 작업을 중단했습니다.');
 if(kind.endsWith('.roster')){const caps=await rpc('check');if(!caps.roster_progress)throw Error('명단 연결 업데이트가 필요합니다. 관리자에게 문의해 주세요.')}
 if(kind==='mswitch.attendance'){const caps=await rpc('check');if(!caps.attendance_v1)throw Error('출결 연결 업데이트가 필요합니다. 관리자에게 문의해 주세요.')}
 const id=options.requestId||crypto.randomUUID(),owner=u.id;let lastProgress='';const reportProgress=p=>{onProgress?.(p);const text=JSON.stringify(p);if(text!==lastProgress){lastProgress=text;log('job.progress',{request_id:id,kind,...p})}};log('job.submit',{request_id:id,kind});const auth_session=kind.startsWith('mswitch.contact.')?(await window.MiraePush.ensureSession()).session:undefined;await rpc('submit',{id,owner_id:owner,kind,payload,auth_session});const end=Date.now()+timeout;
 while(Date.now()<end&&g===generation&&cfg.user?.()?.id===owner){await sleep(1000);let d;try{d=await rpc('status',{id,owner_id:owner})}catch(e){log('job.status_wait',{request_id:id,message:e.message});await sleep(1500);continue}if(g!==generation||cfg.user?.()?.id!==owner)break;if(d.state==='queued')reportProgress({stage:1,label:'PC가 앞선 작업을 마치고 시작하기를 기다리는 중'});else if(d.progress?.stage)reportProgress(d.progress);if(['done','failed','unknown'].includes(d.state)){const r=d.result||{};for(const line of r.logs||[]){const {event,...fields}=line;window.MiraeStore.log(event,fields)}log('job.result',{request_id:id,state:d.state,ok:r.ok===true});if(!r.ok){const error=Error(r.message||'PC 작업을 완료하지 못했습니다. 연결 상태를 확인해 주세요.');error.result=r;throw error}return r}}
 log('job.unknown',{request_id:id,kind});throw Error(kind==='mswitch.send'?'발송 결과를 확인하지 못했습니다. 자동 재발송하지 않았습니다. 엠스위치 발송내역을 확인해 주세요.':'PC 작업 결과를 확인하지 못했습니다. 연결 상태를 확인한 뒤 다시 시도해 주세요.');
}
function reset(){window.MiraeProgress?.reset();generation++;loginOwner='';boundOwner='';binding=null;connecting=null;limited=false;if(timer)clearInterval(timer);timer=null;closeDialog();change('idle')}
window.MiraePC={requiredVersion:MIN_VERSION,siteVersion:VERSION,configure(c){cfg=c},get isMobile(){return mobile},mountSettings,auto,connect,run,status:async id=>{const u=cfg.user?.();if(!u)throw Error('로그인이 필요합니다.');try{return await rpc('status',{id,owner_id:u.id})}catch(e){throw e}},install,paint(){paint();mobileNotice()},reset,open(){if(mobile){cfg.toast?.(detail||('내 PC 연결됨 · 버전 '+seenVersion));return}if(state==='connected'){cfg.toast?.('PC연동 활성화 · 버전 '+seenVersion);return}dialog()},get state(){return state},get version(){return seenVersion},compare};
})();
