/* Outbound HTTPS relay. No localhost requests, protocol launch, or browser policy changes. */
(()=>{'use strict';
const VERSION='2.1.2',PROTOCOL=1,MIN_VERSION='2.1.2',PAIR='mirae-pc-pair-v21';
let cfg={},pair=null,state='idle',detail='',seenVersion='',timer=null,generation=0,connecting=null,loginOwner='',limited=false;
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const log=(event,d={})=>window.MiraeStore.log('pc.'+event,d),sleep=ms=>new Promise(r=>setTimeout(r,ms));
function compare(a,b){const x=String(a).split('.').map(Number),y=String(b).split('.').map(Number);if(x.length!==3||y.length!==3||[...x,...y].some(n=>!Number.isInteger(n)||n<0))return-1;for(let i=0;i<3;i++){if(x[i]!==y[i])return x[i]>y[i]?1:-1}return 0}
function siteURL(){return new URL('.',location.href).href}
function pairing(){const c=window.MIRAE_CONFIG||{},project=c.SUPABASE_URL;try{pair=JSON.parse(localStorage.getItem(PAIR)||'null')}catch{}if(!pair||pair.project!==project||!/^[a-f0-9]{64}$/.test(pair.key||'')){const b=new Uint8Array(32);crypto.getRandomValues(b);pair={id:crypto.randomUUID(),key:[...b].map(x=>x.toString(16).padStart(2,'0')).join(''),project};localStorage.setItem(PAIR,JSON.stringify(pair))}return pair}
async function rpc(action,data={},timeout=8000){
 const c=window.MIRAE_CONFIG||{},p=pairing(),key=c.SUPABASE_KEY,headers={apikey:key,'Content-Type':'application/json'};if(key?.startsWith('eyJ'))headers.Authorization='Bearer '+key;
 let r;try{r=await fetch(c.SUPABASE_URL.replace(/\/$/,'')+'/rest/v1/rpc/mirae_pc_bridge',{method:'POST',headers,credentials:'omit',signal:AbortSignal.timeout(Math.max(100,timeout)),body:JSON.stringify({p_device:p.id,p_key:p.key,p_action:action,p_data:data})})}catch(e){throw Error(e.name==='TimeoutError'?'PC 연결 응답 시간이 초과되었습니다.':'Supabase PC 연결 응답을 받지 못했습니다.')}
 const d=await r.json();if(!r.ok){const m=String(d.message||'');log('relay.failed',{action,http_status:r.status,code:String(d.code||'')});if(['PGRST202','42P01','42883'].includes(d.code))throw Error('PC 연결용 SQL을 먼저 추가해야 합니다. 03_v2_1_pc_bridge.sql을 실행해 주세요.');if(m.includes('PC_OFFLINE'))throw Error('PC 연결이 끊겼습니다. 연결을 다시 확인해 주세요.');if(m.includes('PC_BUSY'))throw Error('PC에서 다른 작업을 처리 중입니다. 잠시 후 다시 시도하세요.');if(m.includes('PC_UPDATE_REQUIRED'))throw Error('PC 프로그램 업데이트가 필요합니다.');throw Error('PC 연결 설정을 확인해 주세요. ('+String(d.code||r.status)+')')}return d;
}
function paint(){const b=$('#pc-header-button');if(!b)return;b.classList.add('pc-indicator');b.dataset.state=state;const labels={connected:'PC연동 활성화',connecting:'PC 연결 확인 중',update:'PC 업데이트 필요',offline:'PC 미연결',limited:'제한 모드',idle:'PC 연결 확인'};b.innerHTML='<span class="pc-light" aria-hidden="true"></span><span>'+labels[state]+'</span>';b.title=(seenVersion?'PC 버전 '+seenVersion+' · ':'')+(detail||'PC 연결 상태 보기');}
function change(next,message=''){state=next;detail=message;paint();window.dispatchEvent(new CustomEvent('mirae-pc-state',{detail:{state,version:seenVersion}}))}
function closeDialog(){const el=$('#pc-dialog');el?.remove();if(!$('.modal-overlay'))document.body.classList.remove('modal-open')}
function dialog(){if(!cfg.user?.())return;closeDialog();const el=document.createElement('div');el.id='pc-dialog';el.className='modal-overlay pc-dialog';el.innerHTML=`<section class="modal" role="dialog" aria-modal="true" aria-labelledby="pc-dialog-title"><div class="pc-dialog-content"><span class="pc-dialog-kicker">PC 연결</span><h2 id="pc-dialog-title">${state==='update'?'프로그램 업데이트가 필요합니다.':'PC에 연결되지 않았습니다.'}</h2><p>${esc(detail||'약 10초 동안 응답을 기다렸지만 이 브라우저에 연결된 프로그램을 찾지 못했습니다.')}</p><p class="muted">타임넷 조회와 엠스위치 발송에는 PC 프로그램이 필요합니다. 학생·수업·성적 관리는 제한 모드에서도 이용할 수 있습니다.</p><div class="pc-dialog-actions"><button class="btn primary" data-pc-retry>연결 재시도</button><button class="btn" data-pc-install>${state==='update'?'새 버전 설치':'프로그램 설치'}</button><button class="btn ghost" data-pc-limited>설치하지 않고 제한 모드로 실행</button></div><p data-pc-install-status role="status"></p><small>필요 버전 ${MIN_VERSION}${seenVersion?' · 확인한 버전 '+esc(seenVersion):''}</small></div></section>`;document.body.append(el);document.body.classList.add('modal-open');el.querySelector('[data-pc-retry]').onclick=()=>connect(true);el.querySelector('[data-pc-install]').onclick=()=>install(el);el.querySelector('[data-pc-limited]').onclick=()=>{limited=true;change('limited');closeDialog()};el.querySelector('button').focus();el.addEventListener('keydown',e=>{if(e.key==='Escape'){limited=true;change('limited');closeDialog()}if(e.key==='Tab'){const buttons=[...el.querySelectorAll('button:not(:disabled)')];if(e.shiftKey&&document.activeElement===buttons[0]){buttons.at(-1).focus();e.preventDefault()}else if(!e.shiftKey&&document.activeElement===buttons.at(-1)){buttons[0].focus();e.preventDefault()}}})}
async function connect(show=true){
 if(connecting)return connecting;const g=generation;connecting=(async()=>{
  closeDialog();limited=false;seenVersion='';change('connecting');log('connect.start',{wait_seconds:10,required_version:MIN_VERSION});const end=Date.now()+10000,nonce=crypto.randomUUID();let last='',ok=false;
  try{await rpc('register',{site_url:siteURL()},Math.min(3000,end-Date.now()));await rpc('check',{nonce},Math.min(3000,end-Date.now()));while(Date.now()<end&&g===generation){const d=await rpc('check',{},Math.min(1800,end-Date.now()));seenVersion=String(d.version||'');if(d.online&&d.nonce===nonce){if(d.protocol!==PROTOCOL||compare(d.version,MIN_VERSION)<0){change('update','사이트와 PC 프로그램의 버전이 맞지 않습니다. 프로그램은 자동 업데이트를 확인합니다. 설치 버튼으로 즉시 갱신할 수도 있습니다.');log('version.mismatch',{actual:d.version,required:MIN_VERSION});break}ok=true;change('connected');log('connect.complete',{pc_version:d.version,required_version:MIN_VERSION});closeDialog();break}await sleep(Math.min(750,Math.max(0,end-Date.now())))}}catch(e){last=e.message;const left=end-Date.now();if(left>0)await sleep(left)}
  if(g!==generation)return false;if(!ok&&state!=='update'){change('offline',last||'약 10초 동안 이 PC의 응답을 확인하지 못했습니다. 프로그램을 설치했거나 켜 둔 상태라면 연결을 다시 시도해 주세요.');log('connect.failed',{message:detail})}if(!ok&&show)dialog();if(ok)cfg.connected?.();return ok
 })();try{return await connecting}finally{if(g===generation)connecting=null;startTimer()}
}
function startTimer(){if(timer||!cfg.user?.())return;timer=setInterval(async()=>{if(connecting||!cfg.user?.())return;const g=generation;try{const d=await rpc('check');if(g!==generation)return;seenVersion=String(d.version||'');if(d.online&&d.protocol===PROTOCOL&&compare(d.version,MIN_VERSION)>=0){if(state!=='connected'){change('connected');closeDialog();cfg.connected?.()}}else if(state==='connected'){change(d.online?'update':'offline',d.online?'프로그램 업데이트가 필요합니다.':'PC 프로그램의 응답이 끊겼습니다.');log('disconnected');if(!limited)dialog()}}catch(e){if(g===generation&&state==='connected'){change('offline',e.message);if(!limited)dialog()}}},20000)}
async function auto(){const u=cfg.user?.();if(!u||loginOwner===u.id)return;loginOwner=u.id;return connect(true)}
async function install(el=$('#pc-dialog')){
 const status=el?.querySelector('[data-pc-install-status]'),b=el?.querySelector('[data-pc-install]');if(b)b.disabled=true;try{
  if(location.protocol!=='https:')throw Error('GitHub Pages 등 HTTPS로 배포한 사이트에서 설치 파일을 내려받아 주세요.');if(status)status.textContent='이 PC용 설치 파일을 준비하고 있습니다…';const p=pairing();await rpc('register',{site_url:siteURL()});
  const res=await fetch(new URL('downloads/MiraeConnectorSetup.exe',siteURL()),{cache:'no-store',credentials:'omit'});if(!res.ok)throw Error('설치 파일을 찾지 못했습니다. web/downloads 폴더도 사이트에 올려 주세요.');const raw=new Uint8Array(await res.arrayBuffer());if(raw.length<1000000||raw[0]!==77||raw[1]!==90)throw Error('설치 파일이 올바르지 않습니다. downloads 폴더를 다시 올려 주세요.');
  const c=window.MIRAE_CONFIG||{},data=new TextEncoder().encode(JSON.stringify({api_url:c.SUPABASE_URL.replace(/\/$/,''),public_key:c.SUPABASE_KEY,site_url:siteURL(),token:p.key,device_id:p.id,protocol:PROTOCOL})),length=new Uint8Array(4);new DataView(length.buffer).setUint32(0,data.length,true);
  const blob=new Blob([raw,data,length,new TextEncoder().encode('MIRAE-PC-CONFIG-2.1')],{type:'application/octet-stream'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='미래탐구_PC연결_설치.exe';a.click();setTimeout(()=>URL.revokeObjectURL(u),60000);log('installer.downloaded',{version:VERSION});if(status)status.textContent='내려받은 설치 파일을 한 번 실행해 주세요. 설치가 끝나면 이 창에서 자동으로 연결을 확인합니다.';startTimer();
 }catch(e){if(status)status.textContent=e.message;else cfg.toast?.(e.message,true);log('installer.failed',{message:e.message})}finally{if(b)b.disabled=false}
}
async function run(kind,payload={},timeout=270000){
 const u=cfg.user?.(),g=generation;if(!u||['parent','student'].includes(u.role))throw Error('강사 또는 관리자 로그인이 필요합니다.');if(state!=='connected'){if(!await connect(true))throw Error('PC 연결을 먼저 완료해 주세요.')}
 if(g!==generation||cfg.user?.()?.id!==u.id||payload._site_owner&&payload._site_owner!==u.id)throw Error('사이트 계정이 변경되어 작업을 중단했습니다.');
 const id=crypto.randomUUID(),owner=u.id;log('job.submit',{request_id:id,kind});await rpc('submit',{id,owner_id:owner,kind,payload});const end=Date.now()+timeout;
 while(Date.now()<end&&g===generation&&cfg.user?.()?.id===owner){await sleep(1000);let d;try{d=await rpc('status',{id,owner_id:owner})}catch(e){log('job.status_wait',{request_id:id,message:e.message});await sleep(1500);continue}if(['done','failed','unknown'].includes(d.state)){const r=d.result||{};for(const line of r.logs||[]){const {event,...fields}=line;window.MiraeStore.log(event,fields)}log('job.result',{request_id:id,state:d.state,ok:r.ok===true});if(!r.ok){const error=Error(r.message||'PC 작업을 완료하지 못했습니다. 아래 로그를 확인해 주세요.');error.result=r;throw error}return r}}
 log('job.unknown',{request_id:id,kind});throw Error(kind==='mswitch.send'?'발송 결과를 확인하지 못했습니다. 자동 재발송하지 않았습니다. 엠스위치 발송내역을 확인해 주세요.':'PC 작업 결과를 확인하지 못했습니다. 설정 · 로그를 확인해 주세요.');
}
function reset(){generation++;loginOwner='';connecting=null;limited=false;if(timer)clearInterval(timer);timer=null;closeDialog();change('idle')}
window.MiraePC={configure(c){cfg=c},auto,connect,run,install,paint,reset,open(){if(state==='connected'){cfg.toast?.('PC연동 활성화 · 버전 '+seenVersion);return}dialog()},get state(){return state},get version(){return seenVersion},compare};
})();
