/* A single visible operation, with server-reported stages and real counts. */
(()=>{'use strict';
let active=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function begin(title){
 if(active&&!active.finished){active.show();return null}active?.remove();
 const el=document.createElement('div');el.className='transfer-overlay';el.innerHTML=`<section class="transfer-panel" role="dialog" aria-modal="true" aria-labelledby="transfer-title"><div class="transfer-kicker">PC ↔ 사이트</div><h2 id="transfer-title">${esc(title)}</h2><p class="transfer-description">단계별로 연결 상태와 실제 수신 수량을 확인합니다.</p><div class="transfer-line"><span>연결된 PC</span><i aria-hidden="true"></i><span>명단 서비스</span></div><p class="transfer-stage" role="status" aria-live="polite"></p><div class="transfer-track"><div></div></div><p class="transfer-count"></p><ol class="transfer-history"></ol><p class="transfer-note">응답을 기다리는 중에도 창을 접어 둘 수 있습니다.</p><div class="transfer-actions"><button class="btn" data-transfer-hide>접어 두기</button><button class="btn primary" data-transfer-retry hidden>받은 명단 저장만 재시도</button></div></section>`;
 const chip=document.createElement('button');chip.className='transfer-chip';chip.hidden=true;document.body.append(el,chip);
 let last='',finished=false,retry=null;const history=el.querySelector('.transfer-history');
 const op={get finished(){return finished},show(){el.hidden=false;chip.hidden=true;el.querySelector('[data-transfer-hide]').focus()},remove(){el.remove();chip.remove()},update(p={}){if(finished)return;const stage=Number(p.stage)||1,stages=Number(p.stages)||5,label=p.label||'PC 응답 대기';el.querySelector('.transfer-stage').textContent=`단계 ${stage} / ${stages} · ${label}`;el.querySelector('.transfer-track div').style.width=((stage-1)/stages*100)+'%';el.querySelector('.transfer-count').textContent=Number.isFinite(p.total)?`${Number(p.done)||0} / ${p.total} ${p.unit||'건'}${p.received!=null&&p.unit!=='학생'?' · 수신 '+p.received+'명':''}`:p.received!=null?'현재 수신 '+p.received+'명':'전체 수량은 응답을 받은 뒤 표시합니다.';chip.textContent=title+' · '+label+' ↗';if(last!==label){last=label;const li=document.createElement('li');li.textContent=label;history.append(li);if(history.children.length>5)history.firstChild.remove()}},done(message){finished=true;el.classList.add('is-done');el.querySelector('.transfer-stage').textContent=message;el.querySelector('.transfer-track div').style.width='100%';el.querySelector('.transfer-note').textContent='명단을 사용할 준비가 되었습니다.';el.querySelector('[data-transfer-hide]').textContent='명단 보기';chip.textContent=title+' · 완료 ↗'},fail(message,saveRetry){finished=true;el.classList.add('is-failed');el.querySelector('.transfer-stage').textContent=message;el.querySelector('.transfer-note').textContent=saveRetry?'이 탭에 받은 명단을 보관했습니다. 타임넷을 다시 조회하지 않고 저장만 재시도할 수 있습니다.':'이전에 불러온 명단은 그대로 유지됩니다. 설정 · 로그에서 오류 기록을 복사할 수 있습니다.';el.querySelector('[data-transfer-hide]').textContent='닫기';retry=saveRetry;el.querySelector('[data-transfer-retry]').hidden=!retry;chip.textContent=title+' · 확인 필요 ↗'},resume(){finished=false;el.classList.remove('is-failed');el.querySelector('[data-transfer-retry]').hidden=true;op.show()}};
 el.querySelector('[data-transfer-hide]').onclick=()=>{el.hidden=true;chip.hidden=finished&&!retry};chip.onclick=()=>op.show();el.querySelector('[data-transfer-retry]').onclick=()=>retry?.();el.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();el.querySelector('[data-transfer-hide]').click()}if(e.key==='Tab'){const buttons=[...el.querySelectorAll('button')].filter(b=>!b.hidden&&!b.disabled);if(e.shiftKey&&document.activeElement===buttons[0]){buttons.at(-1).focus();e.preventDefault()}else if(!e.shiftKey&&document.activeElement===buttons.at(-1)){buttons[0].focus();e.preventDefault()}}});active=op;op.update();op.show();return op;
}
window.MiraeProgress={begin,reset(){active?.remove();active=null}};
})();
