(()=>{'use strict';const P=window.MiraePush,esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let cfg={},timer=null;
const labels={queued:'대기',sending:'접수 확인 중',push_waiting:'도착 확인 중',received:'기기 도착 확인',accepted:'접수 완료 · 도착 미확인',sms_wait:'문자 보완 대기',sms_sending:'문자 접수 확인 중',sms_accepted:'문자 접수 완료',sms_failed:'문자 접수 전 실패',sms_unknown:'문자 결과 확인 필요',sms_match_required:'학생 수신자 확인 필요',failed:'실패',uncertain:'결과 확인 필요',no_device:'수신 기기 없음',expired:'처리 기한 지남'};
function state(status){const d=status?.devices||[],m=d.filter(x=>x.mobile),latest=m[0];if(status?.mobile_active>0)return{tone:'good',text:'앱 알림 가능'};if(!m.length)return{tone:'bad',text:'휴대폰 기록 없음'};if(m.some(x=>x.installed&&x.permission==='denied'))return{tone:'bad',text:'알림 차단'};if(m.some(x=>x.installed&&x.permission==='granted'&&x.registered&&x.opted_in))return{tone:'',text:'최근 확인 필요'};if(m.some(x=>x.installed))return{tone:'',text:'알림 설정 필요'};return{tone:'',text:latest.installed===false?'앱 미설치':'설치 미확인'}}
function badge(id){const r=P.rows.find(x=>x.id===id);if(!id)return'<span class="push-badge bad">학부모 미배정</span>';const s=state(r?.status);return`<span class="push-badge ${s.tone}">${esc(s.text)}</span>`}
function checked(r){const date=r.status?.devices?.[0]?.last_checked;return date?new Date(date).toLocaleString('ko-KR'):'확인 기록 없음'}
function role(r){return r.role==='parent'?'학부모':r.role==='admin'?'관리자':'강사·임직원'}
async function mountStatus(node){clearInterval(timer);node.innerHTML='<div class="page-head"><div><h1>알림 수신 상태</h1><p>학부모와 임직원의 앱 설치 · 알림 상태를 확인합니다.</p></div></div><section class="section"><div class="push-target-tools"><input class="input" data-push-query placeholder="이름 · 아이디 검색"><select class="input" data-push-group><option value="all">전체</option><option value="parent">학부모</option><option value="staff">강사·임직원</option></select><button class="btn" data-push-refresh>상태 새로고침</button></div><div data-push-status role="status">상태를 확인하고 있습니다.</div><div class="push-table-scroll" data-push-table></div><p class="push-note">상태는 마지막으로 앱을 실행했을 때 확인한 기록입니다. 앱 삭제나 휴대폰 설정 변경을 즉시 알아낼 수는 없습니다. 휴대폰에서 설치한 앱의 알림을 허용하고 실제 수신 기기가 등록되어야 “앱 알림 가능”으로 표시합니다. PC의 알림 허용만으로 출결 문자 대신 푸시를 보내지는 않습니다.</p></section>';
 let rows=[];const draw=()=>{if(!node.isConnected)return;const q=node.querySelector('[data-push-query]').value.toLowerCase(),group=node.querySelector('[data-push-group]').value,list=rows.filter(r=>(group==='all'||(group==='parent')===(r.role==='parent'))&&(!q||(r.name+' '+r.login_id).toLowerCase().includes(q)));node.querySelector('[data-push-table]').innerHTML=`<table class="push-status-table"><thead><tr><th>이름</th><th>구분</th><th>설치</th><th>알림</th><th>수신 상태</th><th>마지막 확인</th></tr></thead><tbody>${list.map(r=>{const d=(r.status.devices||[]).filter(x=>x.mobile),i=d.some(x=>x.installed===true),p=d.some(x=>x.permission==='granted'),s=state(r.status);return`<tr><td>${esc(r.name)}<small class="muted"> ${esc(r.login_id)}</small></td><td>${role(r)}</td><td>${i?'설치 확인':'미확인'}</td><td>${p?'허용':d.some(x=>x.permission==='denied')?'차단':'미확인'}</td><td><span class="push-badge ${s.tone}">${s.text}</span></td><td>${esc(checked(r))}</td></tr>`}).join('')}</tbody></table>`;node.querySelector('[data-push-status]').textContent='조회 '+list.length+'명'};
 async function load(){try{rows=await P.refreshList();draw();if(P.config?.missing_sql)node.querySelector('[data-push-status]').textContent='앱 알림 추가 설치가 필요합니다. 관리자에게 문의해 주세요.'}catch(e){node.querySelector('[data-push-status]').textContent=e.message}}
 node.querySelector('[data-push-query]').oninput=draw;node.querySelector('[data-push-group]').onchange=draw;node.querySelector('[data-push-refresh]').onclick=load;await load();timer=setInterval(()=>{if(!node.isConnected||cfg.view?.()!=='push_status'){clearInterval(timer);return}load()},30000);
}
async function mountSend(node){clearInterval(timer);node.innerHTML='<div class="page-head"><div><h1>앱푸시 보내기</h1><p>알림을 받을 수 있는 대상에게 회의 · 수업 · 학원 안내를 보냅니다.</p></div></div><div class="push-layout"><section class="section"><h2>받는 사람</h2><input class="input" data-push-search placeholder="이름 검색"><div class="push-target-tools"><button class="btn sm" data-select="parent">학부모 전체</button><button class="btn sm" data-select="staff">강사·임직원 전체</button><button class="btn sm" data-select="clear">선택 해제</button></div><div class="push-targets" data-push-targets></div><p data-push-count></p></section><section class="section push-message"><h2>안내 내용</h2><form data-push-form><label>제목<input class="input" name="title" maxlength="80" required value="미래탐구 안내"></label><label>내용<textarea class="input" name="content" maxlength="3000" required placeholder="예: 오늘 오후 6시, 상담실에서 강사 회의가 있습니다."></textarea></label><p class="push-note">이 메뉴는 앱 알림만 보냅니다. 알림이 꺼져 있는 대상은 목록에 표시되지만 발송에서 제외됩니다. 문자가 필요하면 문자보내기를 이용하세요.</p><button class="btn primary" data-push-send>앱푸시 보내기</button></form><div class="push-result" data-push-result role="status"></div><div class="push-history" data-push-history></div></section></div>';
 const selected=new Set();let rows=[],request=null,lastBody='';
 function draw(){const q=node.querySelector('[data-push-search]').value.toLowerCase();node.querySelector('[data-push-targets]').innerHTML=rows.filter(r=>!q||r.name.toLowerCase().includes(q)).map(r=>`<label class="push-target"><input type="checkbox" data-person="${esc(r.id)}" ${selected.has(r.id)?'checked':''}><span><b>${esc(r.name)}</b><small>${role(r)} · ${esc(r.login_id)}</small></span>${badge(r.id)}</label>`).join('')||'<p class="push-note">대상자가 없습니다. 설치 설정과 권한을 확인해 주세요.</p>';node.querySelectorAll('[data-person]').forEach(c=>c.onchange=()=>{c.checked?selected.add(c.dataset.person):selected.delete(c.dataset.person);count()});count()}
 function count(){const eligible=rows.filter(r=>selected.has(r.id)&&r.status.mobile_active>0).length;node.querySelector('[data-push-count]').textContent='선택 '+selected.size+'명 · 발송 가능 '+eligible+'명 · 제외 '+(selected.size-eligible)+'명'}
 async function history(){if(!node.isConnected)return;try{const r=await P.rpc('history');node.querySelector('[data-push-history]').innerHTML='<h3>최근 발송</h3>'+r.rows.filter(x=>x.kind==='manual').slice(0,30).map(x=>`<p>${esc(rows.find(r=>r.id===x.recipient_id)?.name||'대상자')} · ${esc(x.title)}<br><small>${esc(labels[x.state]||'확인 중')} · ${esc(new Date(x.created_at).toLocaleString('ko-KR'))}</small></p>`).join('')}catch{}}
 node.querySelector('[data-push-search]').oninput=draw;node.querySelectorAll('[data-select]').forEach(b=>b.onclick=()=>{if(b.dataset.select==='clear')selected.clear();else rows.filter(r=>(r.role==='parent')===(b.dataset.select==='parent')).forEach(r=>selected.add(r.id));draw()});
 node.querySelector('[data-push-form]').onsubmit=async e=>{e.preventDefault();const button=node.querySelector('[data-push-send]'),out=node.querySelector('[data-push-result]'),ids=rows.filter(r=>selected.has(r.id)&&r.status.mobile_active>0).map(r=>r.id);if(!ids.length){out.textContent='알림을 받을 수 있는 대상자를 선택하세요.';return}if(ids.length>500){out.textContent='한 번에 최대 500명까지 선택하세요.';return}const form=new FormData(e.target),body={ids,title:form.get('title').trim(),content:form.get('content').trim()},fingerprint=JSON.stringify(body);if(fingerprint!==lastBody){request=crypto.randomUUID();lastBody=fingerprint}button.disabled=true;out.textContent='알림을 접수하는 중입니다.';try{await P.rpc('send',{...body,request_id:request});out.textContent='알림 '+ids.length+'건을 접수했습니다. 아래에서 도착 상태를 확인하세요.';await history()}catch(e){out.textContent=e.message+' 같은 내용으로 다시 누르면 중복 접수를 방지합니다.'}finally{button.disabled=false}};
 rows=await P.refreshList();draw();await history();timer=setInterval(()=>{if(!node.isConnected||cfg.view?.()!=='push'){clearInterval(timer);return}history()},10000);
}
async function settings(node){if(!cfg.isAdmin?.())return;const section=document.createElement('section');section.className='section push-settings';section.innerHTML='<h2>앱 · 알림 설정</h2><p class="push-note">처음 한 번만 설정합니다. 자세한 순서는 제공된 “v3 설치 안내.html”을 여세요. 키는 저장 후 화면에 다시 표시하지 않습니다.</p><form data-push-config><div class="push-config-grid"><label>OneSignal App ID<input class="input" name="app_id" placeholder="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" required></label><label>App API Key<input class="input" type="password" autocomplete="new-password" name="api_key" placeholder="최초 입력 · 이후 비우면 기존 키 유지"></label><label>사이트 주소 · 끝에 / 포함<input class="input" type="url" name="site_url" required></label><label>최근 상태 확인 유효기간<select class="input" name="fresh_days"><option value="7">7일</option><option value="14">14일</option><option value="30">30일</option></select></label></div><p><label><input type="checkbox" name="enabled"> 앱푸시 사용</label> <label><input type="checkbox" name="reminders"> 매일 밤 10시 30분 출결 미입력 안내</label></p><p class="push-note">푸시 도착 확인이 3분 내 없으면 출결 문자를 보완합니다. 문자 보완에는 출결을 저장한 강사의 PC가 켜져 있어야 합니다.</p><button class="btn primary">알림 설정 저장</button></form><p data-push-config-result role="status"></p><hr><h3>내 알림 설정</h3><button class="btn" data-my-notify>알림 설정하기</button><button class="btn" data-my-check>내 상태 다시 확인</button><hr><h3>앱 아이콘 업데이트</h3><p class="push-note">이미지를 선택하면 배포용 아이콘 묶음을 만듭니다. 기존 사이트에 묶음을 덮어 올리세요. 이미 설치한 앱의 홈 화면 아이콘은 운영체제에 따라 바로 바뀌지 않아 재설치가 필요할 수 있습니다. 배경이 투명한 정사각형 PNG를 권장합니다.</p><input type="file" accept="image/png,image/jpeg,image/webp" data-icon-file><button class="btn" data-icon-export disabled>아이콘 업데이트 파일 받기</button><div data-icon-preview></div>';node.append(section);const form=section.querySelector('form'),out=section.querySelector('[data-push-config-result]');
 try{const r=await P.rpc('config');form.elements.app_id.value=r.app_id||'';form.elements.site_url.value=r.site_url||new URL('./',location.href).href;form.elements.enabled.checked=r.enabled;form.elements.reminders.checked=r.reminders;form.elements.fresh_days.value=r.fresh_days||7;out.textContent=(r.key_saved?'키 저장됨 · ':'')+(r.cron?.length===2?'예약 작업 2개 준비됨':'예약 작업 설치 확인 필요')}catch{form.elements.site_url.value=new URL('./',location.href).href;out.textContent='알림 추가 SQL 설치 후, 사이트에서 로그아웃하고 다시 로그인해 주세요.'}
 form.onsubmit=async e=>{e.preventDefault();const b=form.querySelector('button');b.disabled=true;out.textContent='설정 저장 중';try{await P.rpc('config',{app_id:form.elements.app_id.value.trim(),api_key:form.elements.api_key.value.trim(),site_url:form.elements.site_url.value.trim(),enabled:form.elements.enabled.checked,reminders:form.elements.reminders.checked,fresh_days:Number(form.elements.fresh_days.value),fallback_seconds:180});form.elements.api_key.value='';await P.readConfig();out.textContent='저장완료 · 휴대폰 앱에서 로그인하고 알림을 켜 주세요. 이미 접속한 기기는 새로고침해 주세요.';P.startUser(cfg.user())}catch(e){out.textContent=e.message}finally{b.disabled=false}};
 section.querySelector('[data-my-notify]').onclick=P.enableNotifications;section.querySelector('[data-my-check]').onclick=async()=>{await P.syncDevice();out.textContent=state(P.self).text};let icon=null;const file=section.querySelector('[data-icon-file]'),exportButton=section.querySelector('[data-icon-export]');file.onchange=async()=>{exportButton.disabled=true;const f=file.files[0];if(!f)return;if(f.size>12000000){out.textContent='12MB 이하 이미지를 선택하세요.';return}try{icon=await createImageBitmap(f);section.querySelector('[data-icon-preview]').innerHTML='';const canvas=document.createElement('canvas');canvas.width=canvas.height=70;canvas.getContext('2d').drawImage(icon,0,0,70,70);section.querySelector('[data-icon-preview]').append(canvas);exportButton.disabled=false}catch{out.textContent='이미지를 읽지 못했습니다.'}};exportButton.onclick=()=>window.MiraeIconExport.export(icon).catch(e=>out.textContent=e.message);
}
window.MiraePushUI={VERSION:'3.0.0',configure(c){cfg=c},state,badge,mountStatus,mountSend,settings};
})();
