(()=>{'use strict';
const VERSION='3.0.1',ROOT=new URL('./',document.currentScript.src),db=window.MiraeStore;
let cfg={},publicConfig=null,session=null,sdk=null,ready=null,installEvent=null,user=null,generation=0,summary=[],heartbeat=null,bound=false,identity=Promise.resolve(),connection={phase:'idle',message:'알림 연결을 준비하고 있습니다.'};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const mobile=()=>/Android|iPhone|iPad|iPod/i.test(navigator.userAgent)||navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1;
const ios=()=>/iPhone|iPad|iPod/i.test(navigator.userAgent)||navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1;
const standalone=()=>!!navigator.standalone||matchMedia('(display-mode: standalone)').matches;
const emit=()=>{window.dispatchEvent(new Event('mirae-push-status'));paintPrompt()};
function connectionState(phase,message,error){connection={phase,message,error_kind:error?.name||'',error_detail:error?.message||'',time:new Date().toISOString()};emit()}
function deviceID(){let id=localStorage.getItem('mirae-v3-device');if(!id){id=crypto.randomUUID();localStorage.setItem('mirae-v3-device',id)}return id}
async function rpc(action,data={}){if(!session?.session)throw Error('알림 연결을 확인하려면 다시 로그인해 주세요.');return db.rpc('mirae_push_bridge',{p_session:session.session,p_action:action,p_data:data})}
async function readConfig(){try{const previous=publicConfig;publicConfig=await db.rpc('mirae_push_public',{});if(!sdk&&(!publicConfig.enabled||!previous?.enabled||previous.app_id!==publicConfig.app_id))ready=null;if(sdk&&previous?.app_id&&previous.app_id!==publicConfig.app_id)connectionState('reload','알림 설정이 변경되었습니다. 새로고침해 주세요.');return publicConfig}catch(e){publicConfig={enabled:false,missing_sql:true};connectionState('failed','알림 설정을 확인하지 못했습니다. 잠시 뒤 새로고침해 주세요.',e);return publicConfig}}
function rememberReceiptConfig(){const c=db.config||{},req=indexedDB.open('mirae-push-worker',1);req.onupgradeneeded=()=>req.result.createObjectStore('config');req.onsuccess=()=>{const d=req.result,t=d.transaction('config','readwrite');t.objectStore('config').put({url:c.SUPABASE_URL,key:c.SUPABASE_KEY},'public');t.oncomplete=()=>d.close()}}
async function initSDK(){if(sdk)return sdk;const c=publicConfig||await readConfig();if(c.missing_sql)return null;if(!c.enabled||!c.app_id){ready=null;connectionState('disabled','학원에서 알림 기능을 아직 활성화하지 않았습니다.');return null}if(ready)return ready;
 connectionState('loading','알림 서비스와 연결하고 있습니다.');
 ready=(async()=>{rememberReceiptConfig();window.OneSignalDeferred=window.OneSignalDeferred||[];
  return new Promise((resolve,reject)=>{let settled=false;const finish=(ok,value)=>{if(settled)return;settled=true;clearTimeout(timeout);document.removeEventListener('securitypolicyviolation',policyError);ok?resolve(value):reject(value)};
   const policyError=e=>{if(String(e.effectiveDirective||'').startsWith('script-src')&&/^https:\/\/(?:api|cdn)\.onesignal\.com(?:\/|$)/.test(e.blockedURI||'')){const error=Error('OneSignal script blocked by Content Security Policy: '+e.blockedURI);error.name='PushPolicyError';finish(false,error)}};
   const timeout=setTimeout(()=>{const error=Error('OneSignal initialization did not finish within 30 seconds.');error.name='PushTimeout';finish(false,error)},30000);document.addEventListener('securitypolicyviolation',policyError);
   window.OneSignalDeferred.push(async os=>{try{await os.init({appId:c.app_id,serviceWorkerPath:new URL('push/OneSignalSDKWorker.js',ROOT).pathname.replace(/^\/+/,''),serviceWorkerParam:{scope:new URL('push/',ROOT).pathname},notifyButton:{enable:false},welcomeNotification:{disable:true},promptOptions:{slidedown:{prompts:[{type:'push',autoPrompt:false}]}}});if(settled)return;sdk=os;os.Notifications.addEventListener('permissionChange',()=>syncDevice());os.User.PushSubscription.addEventListener('change',()=>syncDevice());finish(true,os)}catch(e){finish(false,e)}});
   if(!document.querySelector('[data-onesignal-sdk]')){const script=document.createElement('script');script.dataset.onesignalSdk='';script.src='https://cdn.onesignal.com/sdks/web/v16/OneSignalSDK.page.js';script.defer=true;script.onerror=()=>finish(false,Error('OneSignal SDK script could not be loaded.'));document.head.append(script)}
  })})().catch(e=>{connectionState('failed',e.name==='PushPolicyError'?'사이트 설정이 알림 연결을 차단했습니다. 관리자에게 업데이트를 요청해 주세요.':e.name==='PushTimeout'?'알림 연결 응답이 늦어 확인하지 못했습니다. 새로고침 후 다시 시도해 주세요.':'알림 서비스에 연결하지 못했습니다. 새로고침 후 다시 시도해 주세요.',e);return null});return ready}
async function authenticate(login,password){session=await db.rpc('mirae_push_login',{p_login:login,p_password:password});sessionStorage.setItem('mirae-v3-push-session',JSON.stringify(session));return session}
async function startUser(u){const g=++generation;user=u;bound=false;clearInterval(heartbeat);
 try{const c=publicConfig||await readConfig();if(c.missing_sql||connection.phase==='reload'){paintPrompt();return}if(!ready||sdk)connectionState('account','알림 사용자 정보를 확인하고 있습니다.');
  try{session=JSON.parse(sessionStorage.getItem('mirae-v3-push-session')||'null')}catch{session=null}
  if(session?.owner_id!==u.id)session=null;
  if(session){try{await rpc('self')}catch{session=null}}
  if(!session){const creds=cfg.credentials?.();if(creds?.login&&creds?.password)await authenticate(creds.login,creds.password)}
  if(g!==generation)return;const os=await initSDK();if(g!==generation)return;if(!os){if(!['parent','student'].includes(u.role)&&session)await refreshList();emit();return}
  if(os&&session){const external=session.external_id;identity=identity.catch(()=>{}).then(()=>g===generation?os.login(external):null);await identity}if(g!==generation)return;bound=true;connectionState('ready','알림 서비스 연결이 확인되었습니다.');
  await syncDevice();if(!['parent','student'].includes(u.role))await refreshList();
  if(g!==generation)return;heartbeat=setInterval(()=>{if(document.visibilityState==='visible')syncDevice()},60000);emit();
 }catch(e){if(g===generation)connectionState('failed','알림 사용자 연결을 확인하지 못했습니다. 로그아웃 후 다시 로그인해 주세요.',e)}
}
async function syncDevice(){if(!session||!user||!bound)return;const g=generation,os=sdk,sub=os?.User?.PushSubscription;
 const supported=!!os&&os.Notifications.isPushSupported();let installed=standalone()?true:null;
 if(localStorage.getItem('mirae-v3-install-observed')==='yes')installed=true;
 const permission=supported?('Notification'in window?Notification.permission:(os.Notifications.permission?'granted':'default')):'unsupported';
 try{const r=await rpc('device',{device_id:deviceID(),subscription_id:sub?.id||'',platform:ios()?'iOS':/Android/i.test(navigator.userAgent)?'Android':'PC',mobile:mobile(),installed,permission,supported,opted_in:!!sub?.optedIn});if(g!==generation)return;window.MiraePush.self=r;emit()}catch{}
}
async function refreshList(){const g=generation;try{const r=await rpc('list');if(g!==generation)return[];summary=r.rows||[];emit();return summary}catch{return summary}}
async function logout(){const old=session,os=sdk,sub=os?.User?.PushSubscription;const unlink=identity=identity.catch(()=>{}).then(()=>os?.logout());++generation;user=null;bound=false;session=null;summary=[];window.MiraePush.self=null;clearInterval(heartbeat);sessionStorage.removeItem('mirae-v3-push-session');paintPrompt();if(old?.session){try{await db.rpc('mirae_push_bridge',{p_session:old.session,p_action:'device',p_data:{device_id:deviceID(),subscription_id:sub?.id||'',mobile:mobile(),platform:ios()?'iOS':'Android/PC',installed:standalone()?true:null,permission:'Notification'in window?Notification.permission:'unsupported',supported:!!os&&os.Notifications.isPushSupported(),opted_in:false}})}catch{}}try{await unlink}catch{}if(old?.session)db.rpc('mirae_push_bridge',{p_session:old.session,p_action:'logout',p_data:{}}).catch(()=>{})}
function help(title,html){document.querySelector('.pwa-help')?.remove();const box=document.createElement('div');box.className='modal-overlay pwa-help';box.innerHTML=`<section class="modal"><header class="modal-head"><h2>${esc(title)}</h2><button class="btn" data-close>닫기</button></header><div class="modal-body">${html}</div></section>`;document.body.append(box);box.querySelector('[data-close]').onclick=()=>box.remove()}
async function install(){if(standalone()){help('미래탐구 앱','<p>이미 앱으로 사용 중입니다.</p>');return}if(installEvent){const e=installEvent;installEvent=null;await e.prompt();await e.userChoice;paintPrompt();return}
 help('미래탐구 앱 설치',ios()?'<ol><li>Safari에서 이 사이트를 여세요.</li><li>공유 버튼을 누른 뒤 <b>홈 화면에 추가</b>를 선택하세요. iOS 버전에 따라 먼저 메뉴의 더보기를 펼쳐야 합니다.</li><li>앱 이름이 미래탐구인지 확인하고 추가하세요.</li><li>홈 화면의 미래탐구 아이콘으로 실행한 뒤 로그인하고 알림을 켜세요.</li></ol><p>아이폰은 버튼만으로 자동 설치할 수 없습니다. iOS 16.4 이상에서 앱 알림을 지원합니다.</p>':'<ol><li>Chrome 또는 Samsung Internet에서 사이트를 여세요.</li><li>브라우저 메뉴에서 <b>앱 설치</b> 또는 <b>홈 화면에 추가</b>를 선택하세요.</li><li>설치한 미래탐구 아이콘으로 실행하세요.</li></ol><p>카카오톡 등 앱 안의 브라우저에서는 메뉴의 “다른 브라우저로 열기”를 먼저 선택해 주세요.</p>')}
function enableNotifications(){if(!user){help('알림 설정','<p>먼저 로그인해 주세요.</p>');return}if(mobile()&&!standalone()){install();return}
 if(!sdk||connection.phase==='reload'){const failed=['failed','reload'].includes(connection.phase),detail=JSON.stringify({version:VERSION,site:location.origin,app_id:publicConfig?.app_id||'',connection,release:window.MiraeReleaseStatus||null},null,2);help(failed?'알림 연결 확인':'알림 연결 안내',`<p>${esc(connection.message)}</p>${failed?'<p><button class="btn" data-push-reload>새로고침</button></p><details><summary>문제 확인을 위한 진단 내용</summary><textarea class="input" readonly rows="9" style="width:100%">'+esc(detail)+'</textarea></details>':'<p>연결 중인 경우 잠시 뒤 다시 눌러 주세요.</p>'}`);document.querySelector('[data-push-reload]')?.addEventListener('click',()=>location.reload());return}
 if(!sdk.Notifications.isPushSupported()){help('이 환경에서는 알림을 지원하지 않습니다','<p>최신 운영체제와 브라우저를 사용해 주세요. 아이폰에서는 홈 화면에 설치한 앱으로 실행해야 합니다. 출결 알림은 기존 문자 방식으로 보완합니다.</p>');return}
 if('Notification'in window&&Notification.permission==='denied'){help('알림 허용하기',ios()?'<p>휴대폰 <b>설정 → 알림 → 미래탐구 → 알림 허용</b>을 켠 다음 앱을 다시 여세요.</p>':'<p>휴대폰 <b>설정 → 앱 → 미래탐구 → 알림</b>에서 알림을 켜 주세요. Chrome 사이트 설정의 알림도 허용해 주세요.</p>');return}
 // Call immediately in the click handler: iOS requires a direct user gesture.
 sdk.Notifications.requestPermission().then(()=>sdk.User.PushSubscription.optIn()).then(syncDevice).catch(()=>help('알림 설정 확인','<p>휴대폰 또는 브라우저 설정에서 미래탐구 알림을 허용한 뒤 다시 열어 주세요.</p>'));
}
function paintPrompt(){let box=document.querySelector('#pwa-prompt');if(!box){box=document.createElement('aside');box.id='pwa-prompt';document.body.append(box)}
 if(!mobile()){box.hidden=true;return}const installed=standalone(),s=window.MiraePush?.self,d=s?.devices?.find(x=>x.device_id===deviceID()),active=d?.installed&&d?.permission==='granted'&&d?.registered&&d?.opted_in;
 if(!installed){box.hidden=false;box.innerHTML='<img src="'+new URL('icons/mirae-192.png',ROOT)+'" alt=""><span><b>미래탐구 앱으로 편하게</b><small>홈 화면에서 바로 이용하세요</small></span><button class="btn sm" data-install>앱 설치</button>';box.querySelector('[data-install]').onclick=install;return}
 if(!user||active||!publicConfig?.enabled){box.hidden=true;return}box.hidden=false;box.innerHTML='<span><b>수업 안내를 놓치지 마세요</b><small>알림을 켜면 수업 상태를 안내받을 수 있습니다</small></span><button class="btn sm" data-enable>알림 설정하기</button>';box.querySelector('[data-enable]').onclick=enableNotifications;
}
async function attendance(ids,retry=false){if(!session||publicConfig?.missing_sql)return null;const all=[];for(let i=0;i<ids.length;i+=200){const r=await rpc(retry?'retry':'attendance',{ids:ids.slice(i,i+200)});all.push(...(r.rows||[]))}return{ok:true,rows:all}}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installEvent=e;paintPrompt()});window.addEventListener('appinstalled',()=>{localStorage.setItem('mirae-v3-install-observed','yes');syncDevice();paintPrompt()});window.addEventListener('focus',()=>{if(user)syncDevice()});document.addEventListener('visibilitychange',()=>{if(!document.hidden&&user)syncDevice()});
if('serviceWorker'in navigator&&!window.MIRAE_CONFIG?.TEST_MODE){navigator.serviceWorker.register(new URL('app-worker.js',ROOT),{scope:ROOT.pathname}).then(reg=>{reg.addEventListener('updatefound',()=>{const w=reg.installing;w?.addEventListener('statechange',()=>{if(w.state==='installed'&&navigator.serviceWorker.controller){let b=document.querySelector('#pwa-update');if(!b){b=document.createElement('button');b.id='pwa-update';b.className='btn';b.textContent='새 버전 준비됨 · 새로고침';b.onclick=()=>location.reload();document.body.append(b)}}})})}).catch(()=>{})}
window.MiraePush={VERSION,configure(c){cfg=c},mobile,standalone,readConfig,authenticate,startUser,logout,syncDevice,refreshList,rpc,attendance,install,enableNotifications,get rows(){return summary},get config(){return publicConfig},get connection(){return {...connection}},self:null};readConfig().then(paintPrompt);new MutationObserver(()=>{const box=document.querySelector('#pwa-prompt');if(box)box.classList.toggle('at-login',document.body.classList.contains('at-login'))}).observe(document.body,{attributes:true,attributeFilter:['class']});paintPrompt();
})();
