(()=>{'use strict';let cfg={};const P=window.MiraePush,esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const DEFAULT='<$학생명> 학부모님. <$날짜>에 진행한 <$수업명>에 대한 수업 레포트가 발행되었습니다.';
const labels={queued:'발송 대기',sending:'접수 확인 중',accepted:'접수 완료 · 도착 미확인',received:'기기 도착 확인',failed:'실패',no_device:'수신 기기 없음',expired:'처리 기한 지남',uncertain:'결과 확인 필요'};
function inPeriod(c,day){return !!c?.start_date&&c.start_date<=day&&(!c.end_date||new Date(c.end_date+'T00:00:00+09:00').getTime()+10*86400000>=new Date(day+'T00:00:00+09:00').getTime())}
function own(c,u){return u?.role==='admin'||MiraeTeam.has(c,u?.id)}
async function open(id){await P.ensureSession();let r;try{r=await P.rpc('report_preview',{lesson_id:id})}catch(e){cfg.toast?.('이 강좌의 알림 상태를 확인할 수 없습니다. 개강일과 종강 후 10일 범위를 확인해 주세요.',true);return}
 const box=document.createElement('div');box.className='modal-overlay report-overlay';box.innerHTML='<section class="modal wide report-notify-modal" role="dialog" aria-modal="true" aria-labelledby="report-title"><header class="modal-head"><div><h2 id="report-title">레포트 발송 · 알림 상태</h2><small>'+esc(r.class.name)+' · '+esc(r.lesson.lesson_date)+' · '+esc(r.lesson.title)+'</small></div><button class="btn" data-close>닫기</button></header><div class="modal-body"><p class="report-copy" data-copy></p><p class="management-intro">앱 알림을 받을 수 있는 학부모에게 발행 사실을 안내합니다. 수신할 수 없는 학부모는 아래에 표시됩니다.</p><div class="contact-batch-tools"><label><input type="checkbox" data-all checked> 발송 가능한 학생 전체 선택</label><button class="btn sm" data-refresh>상태 새로고침</button></div><div class="table-scroll" data-report-list></div><p class="report-result" data-result role="status"></p></div><footer class="modal-footer"><button class="btn" data-close>닫기</button><button class="btn primary" data-send>레포트 발행 알림 보내기</button></footer></section>';document.body.append(box);const owner=cfg.user?.()?.id;let sentMessage='',busy=false,selected=new Set(r.rows.filter(x=>x.eligible&&!x.result).map(x=>x.student_id)),timer=null;
 const $=s=>box.querySelector(s),close=()=>{if(busy)return;clearInterval(timer);box.remove()};box.querySelectorAll('[data-close]').forEach(b=>b.onclick=close);box.onkeydown=e=>{if(e.key==='Escape')close();if(e.key==='Tab'){const a=[...box.querySelectorAll('button:not(:disabled),input:not(:disabled)')].filter(x=>x.offsetParent),first=a[0],last=a.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};
 function draw(){if(!box.isConnected)return;$('[data-copy]').textContent=r.rows[0]?.content||'이 수업일의 수강 학생이 없습니다.';$('[data-report-list]').innerHTML='<table class="one-line-table"><thead><tr><th></th><th>학생</th><th>학부모</th><th>알림 수신 상태</th><th>발송 결과</th><th>발신자</th></tr></thead><tbody>'+r.rows.sort((a,b)=>a.student_name.localeCompare(b.student_name,'ko')).map(x=>'<tr><td><input type="checkbox" data-student="'+esc(x.student_id)+'" aria-label="'+esc(x.student_name)+' 선택" '+(selected.has(x.student_id)?'checked':'')+' '+(!r.can_send||!x.eligible||x.result?'disabled':'')+'></td><td>'+esc(x.student_name)+'</td><td>'+esc(x.parent_name||'학부모 미배정')+'</td><td><span class="push-badge '+(x.eligible?'good':'bad')+'">'+(x.eligible?'앱 알림 가능':x.parent_id?'알림 설정 확인 필요':'학부모 미배정')+'</span></td><td title="'+esc(x.result?.detail||'')+'">'+esc(x.result?.received_at?'기기 도착 확인':labels[x.result?.state]||'미발송')+'</td><td>'+esc(x.result?.sender_name||'—')+'</td></tr>').join('')+'</tbody></table>';box.querySelectorAll('[data-student]').forEach(x=>x.onchange=()=>{x.checked?selected.add(x.dataset.student):selected.delete(x.dataset.student);count()});count()}
 function count(){const n=r.rows.filter(x=>selected.has(x.student_id)&&x.eligible&&!x.result).length;$('[data-send]').disabled=busy||!r.can_send||!n;$('[data-result]').textContent=sentMessage||((r.lesson.published===false?'학부모 공개로 저장한 뒤 발송할 수 있습니다. · ':'')+'학부모 '+r.rows.length+'명 · 발송 가능 '+r.rows.filter(x=>x.eligible&&!x.result).length+'명 · 수신 설정 확인 필요 '+r.rows.filter(x=>!x.eligible).length+'명 · 선택 '+n+'명')}
 async function refresh(){try{const v=await P.rpc('report_preview',{lesson_id:id});if(!box.isConnected)return;r=v;selected=new Set([...selected].filter(s=>r.rows.some(x=>x.student_id===s&&x.eligible&&!x.result)));draw()}catch(e){if(box.isConnected)$('[data-result]').textContent='상태를 다시 확인하지 못했습니다.'}}
 $('[data-all]').onchange=e=>{selected=e.target.checked?new Set(r.rows.filter(x=>x.eligible&&!x.result).map(x=>x.student_id)):new Set();draw()};$('[data-refresh]').onclick=refresh;
 $('[data-send]').onclick=async()=>{const ids=[...selected].filter(id=>r.rows.some(x=>x.student_id===id&&x.eligible&&!x.result));if(busy||!r.can_send||!ids.length)return;if(!confirm(ids.length+'명의 학부모에게 레포트 발행 알림을 보낼까요?'))return;busy=true;count();try{const v=await P.rpc('report_send',{lesson_id:id,expected_version:String(r.lesson.version||1),student_ids:ids});selected.clear();await refresh();sentMessage='발송 요청 '+v.queued+'명 · 이미 발송 '+v.existing+'명 · 수신 불가 제외 '+v.excluded+'명';cfg.toast?.('레포트 안내 발송 요청 완료')}catch(e){$('[data-result]').textContent=/REPORT_CHANGED/.test(e.message)?'수업 기록이 변경되었습니다. 상태를 다시 불러온 뒤 발송해 주세요.':'발송 결과를 확인하지 못했습니다. 새로고침으로 발송 상태를 먼저 확인해 주세요.'}finally{busy=false;count()}};
 timer=setInterval(()=>{if(!box.isConnected){clearInterval(timer);return}if(cfg.user?.()?.id!==owner){box.remove();clearInterval(timer);return}if(!busy&&document.visibilityState==='visible')refresh()},10000);draw();$('[data-close]').focus();
}
async function settings(node){return MiraeMessages.settings(node,cfg)}
window.MiraeReportNotify={VERSION:'261009',DEFAULT,inPeriod,own,configure(c){cfg=c},open,settings};})();
