(function(root){'use strict';
const CAP={dashboard:'오늘의 클래스',students:'학생 목록',student_edit:'학생 등록·수강 변경',parents:'학부모 목록',parent_edit:'학부모 등록·배정',classes:'수강반 목록',class_edit:'반 개설·일정 수정',lessons:'수업·코멘트 보기',lesson_edit:'수업·과제·개별 코멘트 입력',exams:'시험·성적 보기',exam_edit:'시험 개설·점수 입력',consultations:'상담 보기',consultation_edit:'상담 답변·상태 변경',videos:'영상 보기',video_edit:'영상 등록·수정',reports:'학습 리포트',attendance:'출결 보기',attendance_edit:'출결 기록 수정',attendance_notify:'출결 문자 발송',sms:'문자보내기',timenet:'타임넷 명단 갱신',syllabus_edit:'강의계획 수정',login_design:'로그인·메인 화면 편집',staff_manage:'강사 추가·직급·퇴사 관리',oversight:'강사 입력 현황 대시보드',all_classes:'모든 반·학생 열람 및 담당 범위 확대',export:'목록 내려받기',audit:'변경 기록 보기'};
const teacher=Object.keys(CAP).filter(k=>!['login_design','staff_manage','oversight','all_classes','audit'].includes(k));
function defaults(){return{ranks:[{id:'admin',name:'관리자',permissions:Object.keys(CAP)},{id:'teacher',name:'강사',permissions:teacher}]}}
function policy(raw){const out=raw?.ranks;if(!Array.isArray(out)||out.length<2||out.length>20)return defaults();return{ranks:out.map((r,i)=>({id:i===0?'admin':i===1?'teacher':String(r.id),name:String(r.name||'직급 '+(i+1)).slice(0,40),permissions:i===0?Object.keys(CAP):(r.permissions||[]).filter(k=>k in CAP)}))}}
function rank(a,p){p=policy(p);return p.ranks.find(r=>r.id===(a.role==='admin'?'admin':a.rank_id||'teacher'))||{id:'removed',name:'미배정',permissions:[]}}
function allows(a,k,p){const deps={students:['student_edit'],parents:['parent_edit'],classes:['class_edit','syllabus_edit'],lessons:['lesson_edit'],exams:['exam_edit'],consultations:['consultation_edit'],videos:['video_edit'],attendance:['attendance_edit','attendance_notify']};const perms=a?rank(a,p).permissions:[];return !!a&&(a.role==='admin'||a.role==='teacher'&&k!=='audit'&&(perms.includes(k)||(deps[k]||[]).some(x=>perms.includes(x))||k==='login_design'&&!a.rank_id&&a.can_edit_login===true))}
function validate(next,accounts){if(!next||!Array.isArray(next.ranks)||next.ranks.length<2||next.ranks.length>20)throw Error('직급은 2개부터 20개까지 설정하세요.');const ids=new Set(),names=new Set();next.ranks.forEach((r,i)=>{if(r.id!==(i===0?'admin':i===1?'teacher':r.id)||!/^[-a-z0-9_]{1,40}$/.test(r.id)||ids.has(r.id))throw Error('직급 구성을 확인하세요.');if(!String(r.name||'').trim()||names.has(r.name.trim()))throw Error('직급 이름은 서로 다르게 입력하세요.');if(!Array.isArray(r.permissions)||r.permissions.some(x=>!(x in CAP)))throw Error('권한을 확인하세요.');ids.add(r.id);names.add(r.name.trim())});for(const a of accounts)if(a.role==='teacher'&&a.rank_id&&!ids.has(a.rank_id))throw Error('삭제할 직급에 배정된 사람이 있습니다. 다른 직급으로 변경한 뒤 줄여 주세요.');return policy(next)}
const api={CAP,defaults,policy,rank,allows,validate};root.MiraeRoles=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
