(()=>{'use strict';
const form=document.querySelector('#setup'),result=document.querySelector('#result'),section=document.querySelector('#first-admin'),admin=document.querySelector('#admin');let store=null,checked='';
form.elements.url.value=window.MIRAE_CONFIG?.SUPABASE_URL||'';form.elements.key.value=window.MIRAE_CONFIG?.SUPABASE_KEY||'';
function config(){const u=new URL(form.elements.url.value.trim());if(u.protocol!=='https:'||u.pathname!=='/')throw Error('Supabase 프로젝트 기본 URL을 입력하세요.');const key=form.elements.key.value.trim();if(!key||key.startsWith('sb_secret_'))throw Error('Publishable 또는 anon 키를 입력하세요.');return{VERSION:'3.3.0',BRAND:'미래탐구',SUPABASE_URL:u.origin,SUPABASE_KEY:key}}
function remember(c){try{localStorage.setItem('mirae-v2-connection',JSON.stringify(c))}catch{}}
form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('[type=submit]');button.disabled=true;try{const c=config();store=new window.MiraeStore.Store(c);const d=await store.run(false,s=>s);checked=JSON.stringify(c);remember(c);section.hidden=d.accounts.length>0;result.textContent=d.accounts.length?'연결 성공. 기존 v2 계정 '+d.accounts.length+'개가 있습니다. config.js를 내려받아 교체한 뒤 로그인하세요.':'연결 성공. 아래에서 첫 관리자 계정을 만들어 주세요.'}catch(err){result.textContent=err.message;section.hidden=true}finally{button.disabled=false}};
document.querySelector('#download').onclick=()=>{try{const c=config();if(checked!==JSON.stringify(c))throw Error('먼저 연결 확인 버튼을 눌러 주세요.');const url=URL.createObjectURL(new Blob(['window.MIRAE_CONFIG = '+JSON.stringify(c,null,2)+';\n'],{type:'text/javascript;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='config.js';a.click();remember(c);setTimeout(()=>URL.revokeObjectURL(url),3000);result.textContent='config.js를 내려받았습니다. web 폴더의 기존 config.js를 이 파일로 교체해 주세요.'}catch(e){result.textContent=e.message}};
admin.onsubmit=async e=>{e.preventDefault();const button=admin.querySelector('button');button.disabled=true;try{if(!store||checked!==JSON.stringify(config()))throw Error('연결을 먼저 다시 확인하세요.');const name=admin.elements.name.value.trim(),id=admin.elements.login_id.value.normalize('NFKC').trim().toLowerCase(),pw=admin.elements.password.value;if(!name||!pw||!/^[a-z0-9가-힣._@-]{1,100}$/.test(id))throw Error('이름·아이디·비밀번호를 확인하세요.');await store.run(true,s=>{if(s.accounts.length)throw Error('관리자가 이미 생성됐습니다. 기존 아이디로 로그인하세요.');const now=new Date().toISOString();s.accounts.push({id:crypto.randomUUID(),name,login_id:id,password:pw,role:'admin',status:'active',version:1,auth_version:1,must_change:false,preferences:{},created_at:now,updated_at:now})});admin.elements.password.value='';section.hidden=true;result.textContent='관리자 계정 생성 완료. config.js를 내려받아 교체한 후 클래스룸을 여세요.'}catch(e){result.textContent=e.message}finally{button.disabled=false}};
window.addEventListener('mirae-log',()=>{document.querySelector('#setup-log').value=window.MiraeStore.logs()});
})();
