(function(root){'use strict';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),norm=s=>String(s??'').normalize('NFKC').replace(/\s/g,'').toLowerCase();
function resolve(name,directory,picked=null){const key=norm(name);if(!key)return{kind:'blank',matches:[]};const matches=directory.filter(s=>norm(s.name)===key);const chosen=picked&&matches.find(s=>s.student_no===picked);return{kind:chosen||matches.length===1?'matched':matches.length?'ambiguous':'missing',matches,student:chosen||matches.length===1&&matches[0]||null}}
function classify(rows,directory,enrollments,students,classID){const seen=new Set(),registered=new Set(enrollments.filter(e=>e.class_id===classID).map(e=>students.find(s=>s.id===e.student_id)?.student_no));return rows.map(row=>{const r=resolve(row.name,directory,row.student_no);if(r.kind!=='matched')return r;const no=r.student.student_no;if(registered.has(no))return{...r,kind:'registered'};if(seen.has(no))return{...r,kind:'duplicate'};seen.add(no);return{...r,kind:'ready'}})}
function mount(host,cfg){const owner=cfg.user().id;let directory=[],rows=Array.from({length:20},()=>({name:'',student_no:''})),results=[],ready=false,saving=false,dialog=null;const $=s=>host.querySelector(s),classes=cfg.base().classes.filter(c=>c.status==='active'),defaultClass=cfg.classID&&classes.some(c=>c.id===cfg.classID)?cfg.classID:classes[0]?.id||'';
 host.innerHTML='<p class="sheet-help">이름을 입력하고 Enter를 누르면 아래 행으로 이동합니다. 여러 이름을 복사해 이름 셀에 붙여넣을 수도 있습니다.</p><div class="enroll-controls"><label>등록할 반<select data-enroll-class>'+classes.map(c=>`<option value="${esc(c.id)}" ${c.id===defaultClass?'selected':''}>${esc(c.name)}</option>`).join('')+'</select></label><label>수강 시작일<input type="date" data-enroll-date value="'+cfg.today+'"></label></div><p data-enroll-message role="status">타임넷 명단을 불러오는 중</p><div class="spreadsheet-scroll enroll-scroll"><table class="enroll-sheet"><thead><tr class="sheet-index"><th></th><th>A</th><th>B</th><th>C</th><th>D</th><th>E</th></tr><tr><th>행</th><th>학생명</th><th>학교</th><th>학년</th><th>타임넷 수강반</th><th>확인</th></tr></thead><tbody></tbody></table></div><div class="enroll-footer"><button type="button" class="btn" data-enroll-add>행 추가</button><span data-enroll-count></span><button type="button" class="btn primary" data-enroll-save disabled>등록하기</button></div>';
 const current=()=>host.isConnected&&cfg.user()?.id===owner;
 function draw(){host.querySelector('tbody').innerHTML=rows.map((r,i)=>`<tr data-enroll-row="${i}"><th>${i+1}</th><td><input data-enroll-name="${i}" value="${esc(r.name)}" aria-label="${i+1}행 학생명" autocomplete="off" maxlength="100"></td><td data-enroll-school></td><td data-enroll-grade></td><td data-enroll-classes></td><td data-enroll-state></td></tr>`).join('');host.querySelectorAll('[data-enroll-name]').forEach(input=>{input.oninput=()=>{const i=+input.dataset.enrollName;rows[i]={name:input.value,student_no:''};check()};input.onkeydown=e=>{if(e.isComposing||e.keyCode===229)return;if(['Enter','ArrowDown','ArrowUp','Tab'].includes(e.key)){e.preventDefault();const i=+input.dataset.enrollName;check();let next=i+(e.key==='ArrowUp'||e.shiftKey?-1:1);if(next===rows.length&&rows.length<500){rows.push({name:'',student_no:''});draw();check()}const node=$(`[data-enroll-name="${Math.max(0,Math.min(rows.length-1,next))}"]`);node?.focus();node?.select()}};input.onpaste=e=>{const text=root.MiraePlan.clipboard(e);if(!/[\n\r\t]/.test(text))return;e.preventDefault();try{let names=cfg.parse(text,'\t').map(c=>c[0]);if(['학생명','이름'].includes(names[0]?.trim()))names.shift();const start=+input.dataset.enrollName;if(start+names.length>500)throw Error('한 번에 최대500명을 입력하세요.');while(rows.length<start+names.length)rows.push({name:'',student_no:''});names.forEach((name,i)=>rows[start+i]={name,student_no:''});draw();check();$(`[data-enroll-name="${start}"]`)?.focus()}catch(err){$('[data-enroll-message]').textContent=err.message}}})}
 function check(){if(!current())return;results=classify(rows,directory,cfg.base().enrollments,cfg.base().students,$('[data-enroll-class]').value);const labels={ready:['ok','추가 가능'],registered:['warn','이미 등록'],missing:['danger','없는 학생'],ambiguous:['warn','선택 필요'],duplicate:['warn','중복 입력'],blank:['','']};results.forEach((r,i)=>{const tr=$(`[data-enroll-row="${i}"]`),s=r.student;tr.querySelector('[data-enroll-school]').textContent=s?.school||'';tr.querySelector('[data-enroll-grade]').textContent=s?.grade||'';tr.querySelector('[data-enroll-classes]').textContent=(s?.classes||[]).map(c=>typeof c==='string'?c:c.name||c.class_name||'').join(' · ');const [tone,text]=labels[r.kind],state=tr.querySelector('[data-enroll-state]');state.innerHTML=r.kind==='ambiguous'?'<button type="button" class="btn sm enroll-select" data-select-enroll="'+i+'">선택 필요</button>':'<strong class="connection-state '+tone+'">'+text+'</strong>';state.querySelector('button')?.addEventListener('click',()=>choose(i,r.matches))});const count=results.filter(r=>r.kind==='ready').length,blocked=results.some(r=>['ambiguous','missing','duplicate'].includes(r.kind));$('[data-enroll-count]').textContent='추가 가능 '+count+'명 · 이미 등록 '+results.filter(r=>r.kind==='registered').length+'명';$('[data-enroll-save]').disabled=!ready||saving||!count||blocked||!$('[data-enroll-class]').value}
 function choose(i,matches){dialog?.remove();dialog=document.createElement('div');dialog.className='modal-overlay roster-picker-modal enroll-choose';dialog.innerHTML='<section class="modal" role="dialog" aria-modal="true" aria-label="동명이인 학생 선택"><header class="modal-head"><h2>'+esc(rows[i].name)+' · 학생 선택</h2><button type="button" class="btn" data-choice-close>닫기</button></header><div class="modal-body"><p>학교·학년·수강반을 확인하고 한 명을 선택하세요.</p><div class="enroll-candidates">'+matches.map((s,n)=>'<button type="button" class="choice-row roster-one-line" data-choice="'+n+'"><strong>'+esc(s.name)+'</strong><span>'+esc(s.school)+'</span><span>'+esc(s.grade)+'</span><small>'+esc((s.classes||[]).map(c=>typeof c==='string'?c:c.name||c.class_name||'').join(' · '))+'</small></button>').join('')+'</div></div></section>';document.body.append(dialog);const close=()=>{dialog?.remove();dialog=null;$(`[data-enroll-name="${i}"]`)?.focus()};dialog.querySelector('[data-choice-close]').onclick=close;dialog.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{rows[i].student_no=matches[+b.dataset.choice].student_no;close();check()});dialog.onkeydown=e=>{if(e.key==='Escape'){e.stopPropagation();close()}if(e.key==='Tab'){const nodes=[...dialog.querySelectorAll('button')];if(e.shiftKey&&document.activeElement===nodes[0]){nodes.at(-1).focus();e.preventDefault()}else if(!e.shiftKey&&document.activeElement===nodes.at(-1)){nodes[0].focus();e.preventDefault()}}};dialog.querySelector('[data-choice]')?.focus()}
 $('[data-enroll-add]').onclick=()=>{if(rows.length>=500)return;rows.push(...Array.from({length:Math.min(10,500-rows.length)},()=>({name:'',student_no:''})));draw();check()};$('[data-enroll-class]').onchange=check;
 $('[data-enroll-save]').onclick=async()=>{check();if($('[data-enroll-save]').disabled)return;const selected=results.filter(r=>r.kind==='ready');saving=true;cfg.setBusy?.(true);check();host.querySelectorAll('input,select,[data-enroll-add]').forEach(x=>x.disabled=true);try{if(!root.MiraeAttendanceCore.validDay($('[data-enroll-date]').value))throw Error('수강 시작일을 확인하세요.');await cfg.api('/api/timenet/enroll',{method:'POST',body:{rows:selected.map(r=>({student_no:r.student.student_no,class_id:$('[data-enroll-class]').value,joined_on:$('[data-enroll-date]').value}))}});if(current())await cfg.saved(selected.length)}catch(error){if(current())$('[data-enroll-message]').textContent=error.message}finally{saving=false;cfg.setBusy?.(false);if(current()){host.querySelectorAll('input,select,[data-enroll-add]').forEach(x=>x.disabled=false);check()}}};
 draw();cfg.directory().then(data=>{if(!current())return;directory=data;ready=true;$('[data-enroll-message]').textContent=directory.length?'타임넷 명단 '+directory.length+'명':'타임넷 명단이 없습니다. PC에서 명단을 먼저 불러와 주세요.';check()}).catch(e=>{if(current())$('[data-enroll-message]').textContent=e.message});return{dispose(){dialog?.remove()}};
}
const api={resolve,classify,mount};root.MiraeEnroll=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
