(function(root){'use strict';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function dates(c){const A=root.MiraeAttendanceCore;if(!A.validDay(c.start_date)||!A.validDay(c.end_date)||c.start_date>c.end_date||!c.weekdays?.length)return[];const from=new Date(c.start_date+'T12:00:00Z'),to=new Date(c.end_date+'T12:00:00Z');if((to-from)/86400000>1095)throw Error('강의계획은 3년 이내의 수업 일정으로 작성하세요.');const out=[];for(let d=from;d<=to;d.setUTCDate(d.getUTCDate()+1)){const date=d.toISOString().slice(0,10);if(c.weekdays.includes(d.getUTCDay()))out.push(date)}return out}
function merge(c,rows=[]){const old=new Map(rows.map(r=>[r.date,r]));return dates(c).map(date=>({date,content:old.get(date)?.content||'',note:old.get(date)?.note||''}))}
function validate(c,rows){if(!Array.isArray(rows)||rows.length>1000)throw Error('강의계획을 확인하세요.');const allowed=new Set(dates(c)),seen=new Set();for(const r of rows){if(!allowed.has(r.date)||seen.has(r.date))throw Error('강의계획 날짜가 수업 일정과 맞지 않습니다.');if(String(r.content||'').length>4000||String(r.note||'').length>1000)throw Error('수업내용 또는 비고가 너무 깁니다.');seen.add(r.date)}return merge(c,rows)}
function mount(form,initial,parse){const host=form.querySelector('[data-plan-editor]');if(!host)return;let rows=initial||[];const schedule=()=>({start_date:form.elements.start_date.value,end_date:form.elements.end_date.value,weekdays:[...form.querySelectorAll('[data-class-day]:checked')].map(e=>+e.dataset.classDay)});
 const capture=()=>host.querySelectorAll('[data-plan-date]').length?[...host.querySelectorAll('[data-plan-date]')].map(tr=>({date:tr.dataset.planDate,content:tr.querySelector('[data-plan-content]').value,note:tr.querySelector('[data-plan-note]').value})):rows;
 function draw(){try{rows=merge(schedule(),capture());host.innerHTML='<p>수업 일정에 맞춰 날짜가 자동으로 채워집니다. 내용·비고 두 열 또는 날짜·내용·비고 세 열을 붙여넣으세요.</p><textarea data-plan-paste class="input" rows="3" placeholder="엑셀·한글 표에서 복사해 여기에 붙여넣기"></textarea><p data-plan-result role="status"></p><div class="plan-scroll"><table class="plan-table"><thead><tr><th>수업일</th><th>수업내용</th><th>비고</th></tr></thead><tbody>'+rows.map(r=>'<tr data-plan-date="'+r.date+'"><th>'+r.date+'</th><td><textarea data-plan-content rows="2" maxlength="4000">'+esc(r.content)+'</textarea></td><td><textarea data-plan-note rows="2" maxlength="1000">'+esc(r.note)+'</textarea></td></tr>').join('')+'</tbody></table></div>';host.querySelector('[data-plan-paste]').onpaste=e=>{const plain=e.clipboardData.getData('text/plain');let text=plain;if(!text){const doc=new DOMParser().parseFromString(e.clipboardData.getData('text/html'),'text/html');text=[...doc.querySelectorAll('tr')].map(tr=>[...tr.querySelectorAll('th,td')].map(td=>'"'+td.textContent.replaceAll('"','""')+'"').join('\t')).join('\n')}e.preventDefault();try{const grid=parse(text,'\t');if(grid[0]?.some(x=>/^(날짜|수업일|수업내용|비고)$/.test(x.trim())))grid.shift();const next=capture(),byDate=new Map(next.map(r=>[r.date,r]));if(grid.length>next.length)throw Error('붙여넣은 행이 수업 횟수보다 많습니다.');for(let i=0;i<grid.length;i++){const cells=grid[i];if(cells.length>3)throw Error('내용·비고 또는 날짜·내용·비고 열만 붙여넣으세요.');const dated=cells.length===3&&/^\d{4}[.-]\d{1,2}[.-]\d{1,2}$/.test(cells[0].trim());if(cells.length===3&&!dated)throw Error('첫 열의 날짜를 YYYY-MM-DD 또는 YYYY.MM.DD 형식으로 붙여넣으세요.');const date=dated?cells[0].trim().replaceAll('.','-').split('-').map((x,n)=>n?x.padStart(2,'0'):x).join('-'):null;const r=date?byDate.get(date):next[i];if(!r)throw Error('수업 일정에 없는 날짜가 있습니다.');r.content=cells[dated?1:0]||'';r.note=cells[dated?2:1]||''}rows=validate(schedule(),next);host.querySelectorAll('[data-plan-date]').forEach(tr=>{const r=rows.find(x=>x.date===tr.dataset.planDate);tr.querySelector('[data-plan-content]').value=r.content;tr.querySelector('[data-plan-note]').value=r.note});host.querySelector('[data-plan-result]').textContent=grid.length+'행을 붙여넣었습니다. 저장 버튼을 눌러 주세요.'}catch(error){host.querySelector('[data-plan-result]').textContent=error.message}}}catch(e){host.textContent=e.message}}
 form.addEventListener('change',e=>{if(['start_date','end_date'].includes(e.target.name)||e.target.matches('[data-class-day]'))draw()});form._planRead=()=>validate(schedule(),capture());draw();
}
const api={dates,merge,validate,mount};root.MiraePlan=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
