(()=>{'use strict';
const tn=window.MiraeTimeNet,esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
tn.mount=async ctx=>{
 const {node,user,api,fieldsHtml,btn,toast}=ctx,actorID=user()?.id;if(!node)return;tn.save=null;
 const $=s=>node.querySelector(s),$$=s=>[...node.querySelectorAll(s)],current=()=>node.isConnected&&actorID===user()?.id;
 try{const d=await api('/api/timenet/settings');if(!current())return;
 if(user().role!=='admin'){node.innerHTML='<h2>타임넷 학생 명단</h2><p>'+(d.managed?'최고관리자가 연결한 공통 계정으로 전체 학생 명단을 가져옵니다.':'최고관리자가 타임넷 공통 연결을 설정해야 합니다.')+'</p><p class="muted">학원 인터넷(외부 IP 119.196.240.*)에서 전체 학생을 조회합니다. 시트나 비밀번호를 직접 입력할 필요가 없습니다.</p>'+btn('학생 목록 불러오기','timenet-refresh')+'<p id="timenet-result" role="status"></p>';return}
 const v={...d.timenet,centers:(d.timenet.centers||[]).join(',')};
 node.innerHTML='<h2>타임넷 공통 연결 · 최고관리자</h2><p>이 화면에서 연결 정보를 저장하면 프로그램이 직접 처리합니다. 별도의 Python 파일은 필요하지 않습니다. 관리자와 강사 모두 전체 학생을 조회합니다. 시트의 비밀번호를 변경하면 다음 학생 조회부터 새 값을 읽습니다.</p><form id="timenet-form">'+
 fieldsHtml([{key:'password_source',label:'아이디·비밀번호를 가져올 곳',type:'select',wide:true,options:[['google_sheets','스프레드시트에서 자동으로 읽기'],['direct','관리자가 직접 입력']],default:'google_sheets'},{key:'username',label:'고정 타임넷 아이디 · 아이디 셀이 없을 때 사용',wide:true}],v)+
 '<div data-tn-direct>'+fieldsHtml([{key:'password',label:v.password_set?'타임넷 비밀번호 · 저장됨, 변경할 때만 입력':'타임넷 비밀번호',type:'password',wide:true}],{})+'</div>'+
 '<div data-tn-sheet>'+fieldsHtml([{key:'sheet_id',label:'스프레드시트 주소 또는 ID',wide:true},{key:'sheet_username_range',label:'아이디 셀 · 비우면 고정 아이디 사용'},{key:'sheet_password_range',label:'비밀번호 셀',default:'데이터날짜!A2'},{key:'sheet_date_range',label:'갱신 날짜 셀 · 선택',default:'데이터날짜!A1'},{key:'sheet_auth',label:'Google 시트 읽기 인증',type:'select',wide:true,options:[['api_key','기존 Google Sheets API 키'],['service_account','비공개 시트 · 서비스 계정 JSON']]}],v)+
 '<div data-tn-api>'+fieldsHtml([{key:'google_api_key',label:v.google_api_key_set?'Google Sheets API 키 · 저장됨, 변경할 때만 입력':'Google Sheets API 키',type:'password',wide:true}],{})+'</div><div data-tn-service><label class="btn">서비스 계정 JSON 선택<input type="file" data-tn-service-file accept=".json" hidden></label> <span data-tn-service-status>'+(v.service_account_set?'등록되어 있습니다.':'아직 등록하지 않았습니다.')+'</span><p class="muted">시트는 비공개로 두고 서비스 계정 이메일에 읽기 권한을 주세요. 링크만으로 비공개 시트를 읽을 수는 없습니다.</p></div></div>'+
 '<details><summary>센터와 학원 인터넷 설정</summary>'+fieldsHtml([{key:'expected_ip',label:'타임넷 조회를 허용할 외부 IP 범위',default:'119.196.240.0/24',wide:true},{key:'centers',label:'센터 코드 · 쉼표로 구분',wide:true},{key:'rbu',label:'사업부 코드',wide:true}],v)+'<p class="muted"><b>119.196.240.0/24 = 119.196.240.xxx</b>입니다. 보통 기본값을 유지하면 됩니다. PC의 192.168.x.x 주소가 아니라 인터넷에서 보이는 외부 IP를 검사합니다. 이 설정이 타임넷의 IP 승인을 대신하지는 않습니다.</p></details>'+
 '<label class="check-label"><input type="checkbox" name="shared_enabled" '+(v.shared_enabled!==false?'checked':'')+'> 강사들이 이 공통 연결을 사용하도록 허용</label></form><div class="settings-actions">'+btn('공통 연결 저장','save-timenet')+btn('시트 읽기 확인','check-sheet')+btn('학생 목록 불러오기','timenet-refresh')+'</div><p id="timenet-result" role="status"></p>';
 const form=$('#timenet-form'),status=$('#timenet-result');let saving=false;
 tn.save=async()=>{if(saving||!current()||!form.isConnected||user().role!=='admin')return false;try{if(!form.reportValidity())return false;saving=true;const value={};for(const el of form.elements)if(el.name&&!el.disabled)value[el.name]=el.type==='checkbox'?el.checked:el.value;value.centers=String(value.centers||'').split(',').map(x=>x.trim()).filter(Boolean);if(form._serviceAccount)value.service_account=form._serviceAccount;await api('/api/timenet/settings',{method:'POST',body:value});if(!current())return false;form._serviceAccount=null;toast('타임넷 공통 연결을 저장했습니다. 다음 조회부터 적용됩니다.');await tn.mount(ctx);return true}catch(e){if(current()){toast(e.message,true);status.textContent=e.message}return false}finally{saving=false}};
 form.onsubmit=e=>{e.preventDefault();tn.save?.()};
 function toggle(){const sheet=form.elements.password_source.value==='google_sheets',sa=form.elements.sheet_auth.value==='service_account';for(const [sel,visible]of [['[data-tn-sheet]',sheet],['[data-tn-direct]',!sheet],['[data-tn-api]',sheet&&!sa],['[data-tn-service]',sheet&&sa]]){const box=$(sel);box.hidden=!visible;box.querySelectorAll('input,select,button').forEach(el=>el.disabled=!visible)}form.elements.sheet_id.required=sheet;form.elements.sheet_password_range.required=sheet;form.elements.username.required=!sheet||!form.elements.sheet_username_range.value.trim();form.elements.password.required=!sheet&&!v.password_set;form.elements.google_api_key.required=sheet&&!sa&&!v.google_api_key_set}
 form.addEventListener('change',toggle);form.elements.sheet_username_range.addEventListener('input',toggle);toggle();
 $('[data-tn-service-file]').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>150000)throw Error('인증 파일이 너무 큽니다.');const imported={service_account:tn.validateService(JSON.parse(await file.text()))};if(!current()||!form.isConnected)return;if(!imported.service_account)throw Error('Google 서비스 계정 JSON을 선택하세요.');form._serviceAccount=imported.service_account;$('[data-tn-service-status]').textContent='파일을 읽었습니다. 공통 연결 저장을 눌러 적용하세요.'}catch(e){status.textContent=e.message}};
 }catch(e){if(current())node.textContent=e.message}
};
})();
